### ISSUE TITLE
Lazy loaded routes cause problems

### ISSUE THREAD

**Issue by joeldenning** [single-spa/single-spa-angular#102]
See https://github.com/joeldenning/coexisting-vue-microfrontends/issues/6#issuecomment-529284977. cc @yangangzhang

**Comment by arturovt** [comment]
@joeldenning is it related to this repo?

**Comment by joeldenning** [comment]
Honestly, I don't remember. Let's close this due to inactivity

**Comment by mmxstar** [comment]
angular has the same problem too. @joeldenning

**Comment by arturovt** [comment]
@mmxstar could you provide a _minimal reproducible example_?
