### ISSUE TITLE
How do you isolate your css of angular apps in angular 8?

### ISSUE THREAD

**Issue by cpasslack** [single-spa/single-spa-angular#126]
Since Angular 8 we ran into a problem were css from different angular apps were overwritten by other angular apps on other routes (mainly global css i think). Previously we had a dirty hack in our custom webpack config. We added a custom loader to module.rules matching all .js files and replacing every occurrence of  _ngcontent- and _nghost- with _ngcontent-appName and _nghost-appName. Unfortunately in the production build  this doesn't work anymore 😞 

Other attempts like [https://blog.pragmatists.com/independent-micro-frontends-with-single-spa-library-a829012dc5be](url) (see: CSS Stylesheets independence) don't work either.

Can anyone give some hints, tricks or workarounds for this problem? :smirk: Thanks in advance!

**Comment by joeldenning** [comment]
Approach 1 - angular style scopes

See https://angular.io/guide/component-styles#style-scope

Approach 2 - manually scope the css under container

```html
<div id="app1">
  <button class="primary" />
</div>
```

```css
#app1 .primary {
  background-color: blue;
}
```
