### ISSUE TITLE
Unable to export single spa life cycle methods in Angular aplication

### ISSUE THREAD

**Issue by SwapnilChidrawar** [single-spa/single-spa-angular#132]
I am creating angular application with the single spa. when we integrate single spa feature with the existing angular application, it creates it's new main file and considers that while starting the application. Now, my concern is I am using some async operation and providing that while starting the app like below in the main.js file:

```
resolveAsyncServices([
    {
        provide: XYZ,
        useFactory: () => XYZ.getUserLocale()
    },
    {
        provide: ABC,
        useFactory: (ABCData: Locale) => LocaleServiceNg.getUserTimezone(ABCData),
        deps: [PQR]
    },

])
  .then((providers: Array<StaticProvider>) => {
        platformBrowserDynamic(providers)
            .bootstrapModule(AppModule);
    })
    .catch(console.error);
```

when single spa loads its private main file to the app it looks like below:

```
const lifecycles = singleSpaAngular({
  bootstrapFunction: singleSpaProps => {
    singleSpaPropsSubject.next(singleSpaProps);
    return platformBrowserDynamic().bootstrapModule(AppModule);
  },
  template: '<app-root />',
  Router,
  NgZone: NgZone,
  AnimationEngine: AnimationEngine,
});

export const bootstrap = lifecycles.bootstrap;
export const mount = lifecycles.mount;
export const unmount = lifecycles.unmount;
```

i wanted to consider my resolveAsyncServices function with the help of single spa loader file. So for that I am trying below code:

```
resolveAsyncServices([
    {
        provide: XYZ,
        useFactory: () => XYZ.getUserLocale()
    },
    {
        provide: ABC,
        useFactory: (ABCData: Locale) => LocaleServiceNg.getUserTimezone(ABCData),
        deps: [PQR]
    },

])
  .then((providers: Array<StaticProvider>) => {
       const lifecycles = singleSpaAngular({
       bootstrapFunction: singleSpaProps => {
          singleSpaPropsSubject.next(singleSpaProps);
          return platformBrowserDynamic(providers).bootstrapModule(AppModule);
       },
       template: '<ct-root />',
       Router,
       NgZone: NgZone,
       AnimationEngine: AnimationEngine,
  });

  export const bootstrap = lifecycles.bootstrap;
  export const mount = lifecycles.mount;
  export const unmount = lifecycles.unmount; 
})
.catch(console.error);
```

in this case, .then function wont allow to export something to it. So is there any way through which i can export these lifecycle methods of single spa. because my angular application is loading them in async manner in main.ts file. So please provide workaround for this problem.

I am using Angular 8 and Single spa 3.1.0 version.

**Comment by joeldenning** [comment]
You should move your asynchronous logic into either the `bootstrap` or `mount` lifecycles ([documentation](https://single-spa.js.org/docs/building-applications#bootstrap)).

Example code:

```js
import { enableProdMode, NgZone } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { Router } from '@angular/router';
import { AppModule } from './app/app.module';
import { environment } from './environments/environment';
import singleSpaAngular from 'single-spa-angular';
import { singleSpaPropsSubject } from './single-spa/single-spa-props';

if (environment.production) {
  enableProdMode();
}

const angularLifecycles = singleSpaAngular({
  bootstrapFunction: singleSpaProps => {
    singleSpaPropsSubject.next(singleSpaProps);
    return platformBrowserDynamic().bootstrapModule(AppModule);
  },
  template: '<app1-root />',
  Router,
  NgZone: NgZone,
});

export const bootstrap = [
  lifecycles.bootstrap,
  () => resolveAsyncServices([
    {
        provide: XYZ,
        useFactory: () => XYZ.getUserLocale()
    },
    {
        provide: ABC,
        useFactory: (ABCData: Locale) => LocaleServiceNg.getUserTimezone(ABCData),
        deps: [PQR]
    },
  ])
]
export const mount = lifecycles.mount;
export const unmount = lifecycles.unmount;
```

**Comment by SwapnilChidrawar** [comment]
Hi, Thanks for the solution but unfortunately it is also not working. After integrating your solution, I got below error:

![another error](https://user-images.githubusercontent.com/17702699/75130757-fecc4e80-56f5-11ea-817b-1729796ad47c.PNG)

I tried debugging that it seems to be in lifecycle helper file

![another error code](https://user-images.githubusercontent.com/17702699/75130773-1277b500-56f6-11ea-8b66-3ae00d3bd1e5.PNG)

**Comment by joeldenning** [comment]
That error indicates that your array of lifecycle functions is incorrect. Each item in the array must be a function, but one of the items in your array is not.

**Comment by gabriel-bucalon** [comment]
Did anyone manage to solve it?
