### ISSUE TITLE
single-spa-angular schematics output fails lint for Angular CLI projects

### ISSUE THREAD

**Issue by matt-gold** [single-spa/single-spa-angular#138]
#### Description
Adding single-spa-angular to a fresh Angular CLI app fails lint with the Angular CLI default tslint.json.
This is caused by missing semicolons and newlines in asset-url.ts, single-spa-props.ts, and a missing property shorthand in main.single-spa.ts 

#### To Reproduce
- Create a fresh Angular app from the CLI
        ```ng new sample-app```
- Add single-spa-angular using the schematics
        ```ng add single-spa-angular```
- Run the lint script generated by Angular CLI
        ```npm run lint```

#### Versions
single-spa-angular: 3.1.0
@angular/cli: 8.2.1
node: 10.15.3

**Comment by joeldenning** [comment]
Hi @matt-gold, thanks for the good bug report. Would you be willing to submit a pull request fixing the lint issues? The files to modify are found in https://github.com/single-spa/single-spa-angular/tree/master/src/schematics/ng-add/_files
