### ISSUE TITLE
Dynamic HTMLElements as app mounting points

### ISSUE THREAD

**Issue by krzyswiatkowski** [single-spa/single-spa-angular#145]
### **What's wrong?**
`domElementGetter` expects to find DOM element immediately. Dynamically created DOM element causes throwing error: `domElementGetter did not return a valid dom element`

### **Expected behaviour**
`domElementGetter` should take into account that DOM element on which app will be mounted might be created dynamically.

### **Suggested solution**
Call `domElementGetter` with reasonable amount of retries in case of DOM element not found immediately

#### **Implemented solution**
PR: https://github.com/single-spa/single-spa-angular/pull/146

**Comment by krzyswiatkowski** [comment]
@joeldenning I Would much appreciate if you could take a look on this issue & implemented solution as we're in desperate need of that fix :)

**Comment by joeldenning** [comment]
You can provide your own domElementGetter that ensures the dom element is created correctly. [Here is an example](https://github.com/react-microfrontends/navbar/blob/master/src/react-mf-navbar.js#L21)

```ts
const lifecycles = singleSpaAngular({
  bootstrapFunction: singleSpaProps => {
    return platformBrowserDynamic().bootstrapModule(AppModule);
  },
  template: '<app1-root />',
  Router,
  NgZone: NgZone,
  domElementGetter
});

function domElementGetter() {
  let domElement = document.getElementById('app1');
  if (!domElement) {
    domElement = document.createElement('div')
    domElement.id = 'app1'
    document.body.appendChild(domElement)
  }
  return domElement
}
}
```

Alternative:

```ts
const lifecycles = singleSpaAngular({
  bootstrapFunction: singleSpaProps => {
    return platformBrowserDynamic().bootstrapModule(AppModule);
  },
  template: '<app1-root />',
  Router,
  NgZone: NgZone,
  domElementGetter: () => document.getElementById('app1')
});

export const bootstrap = [
  () => {
    const domEl = document.createElement('div')
    domEl.id = 'app1'
    document.body.appendChild(domEl)
  }
]
export const mount = lifecycles.mount
export const unmount = lifecycles.unmount
```

**Comment by krzyswiatkowski** [comment]
@joeldenning Thank you for that, it does heelp. 
We had a case where DOMElement for our child-app was connected to parent-angular-router so when user left child-app-URL the element was destroyed (parent angular-router changed it for another one)

We will be creating DOMElement for child-app in `domElementGetter` - this might result in 2 same elements on page (one created by angular-router and one created by us) but as I checked it won't created any problems as one of the elements empty HTMLElement

**Comment by joeldenning** [comment]
👍 glad to hear it worked for you
