### ISSUE TITLE
url reference in CSS is relative to the root config but not to the micro-frontend

### ISSUE THREAD

**Issue by alalicon577** [single-spa/single-spa-angular#147]
hi Joel, I have images in my assets folder and I am able to display them using the pipe as you have mentioned in the documentation. However, in the CSS I could not use the pipe and so the images/svgs are not showing up because it's looking at the main root config url and not the micro-frontend's url. Do you have any solution to this?

thank you

**Comment by joeldenning** [comment]
Hi @alalicon577, you need to configure the webpack public path in order for asset URLs to work properly. More information is at https://single-spa.js.org/docs/ecosystem-angular#angular-assets
