### ISSUE TITLE
Angular 9 Prod Build Error with Terser. ERROR in polyfills-es5.js from Terser with Invalid assignment error. 

### ISSUE THREAD

**Issue by amilaI** [single-spa/single-spa-angular#148]
### Problem
I created a single-spa-angular app using following commands and updated it to Angular 9.0.7.
```
ng new my-app --routing --prefix my-app
ng update @angular/core @angular/cli
ng add single-spa-angular
```

When I build the app with via ```ng build --prod --deploy-url http://localhost:4203/```, I'm getting the following error, however, ```ng serve --disable-host-check --port 4203 --deploy-url http://localhost:4203/ --live-reload false``` works fine.

### Error Description
`
ERROR in polyfills-es5.js from Terser
Invalid assignment [polyfills-es5.js:9,19]
`

`
at ee (/Users/a/inspire/node_modules/terser/dist/bundle.min.js:1:19453)
at c (/Users/a/inspire/node_modules/terser/dist/bundle.min.js:1:27932)
at ze (/Users/a/inspire/node_modules/terser/dist/bundle.min.js:1:50127)
at qe (/Users/a/inspire/node_modules/terser/dist/bundle.min.js:1:50208)
at T (/Users/a/inspire/node_modules/terser/dist/bundle.min.js:1:33828)
at /Users/a/inspire/node_modules/terser/dist/bundle.min.js:1:30197
at /Users/a/inspire/node_modules/terser/dist/bundle.min.js:1:28664
at /Users/a/inspire/node_modules/terser/dist/bundle.min.js:1:32055
at /Users/a/inspire/node_modules/terser/dist/bundle.min.js:1:32118
at /Users/a/inspire/node_modules/terser/dist/bundle.min.js:1:28664
`
### Package.json
Here's my pacakge.json.
```
"@angular-builders/custom-webpack": "^8.4.1",
    "@angular/animations": "~9.0.7",
    "@angular/common": "~9.0.7",
    "@angular/compiler": "~9.0.7",
    "@angular/core": "~9.0.7",
    "@angular/forms": "~9.0.7",
    "@angular/platform-browser": "~9.0.7",
    "@angular/platform-browser-dynamic": "~9.0.7",
    "@angular/router": "~9.0.7",
    "rxjs": "~6.5.4",
    "single-spa-angular": "^3.3.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"

,
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.7",
    "@angular/cli": "~9.0.7",
    "@angular/compiler-cli": "~9.0.7",
    "@angular/language-service": "~9.0.7",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.7.5"
  }

```
Inside Node modules, I noticed the following versions related to terser.
```
terser@4.5.1
terser-webpack-plugin@2.3.3
```

**Comment by TheMcMurder** [comment]
We plan on supporting it soon, but we don't currently support Angular 9. 

I know it's frustrating, it's frustrating to us too. Every 6 months we have to refactor support for angular, because they make so many systemic changes to the build and don't allow normal customization of the build.

**Comment by TheMcMurder** [comment]
Actually I'm going to leave this open while we work on Angular 9

**Comment by amilaI** [comment]
> We plan on supporting it soon, but we don't currently support Angular 9.
> 
> I know it's frustrating, it's frustrating to us too. Every 6 months we have to refactor support for angular, because they make so many systemic changes to the build and don't allow normal customization of the build.

Is there any workaround that we can do?

**Comment by joeldenning** [comment]
No - single-spa-angular doesn't yet work in Angular 9

**Comment by webblocksapp** [comment]
You can build with `ng build --prod` setting the target to es5 in your `tsconfig.json` file while arrives support for es2015. The disadvantage is that you will get a lot of warnings in your browser because es5 uses SystemJS for importing your angular components, and es2015 uses `import` instead of `SystemJS.import()`

`"compilerOptions": {
    ...
    "target": "es5",
    ...
`

I'm working with es5 target while arrives single-spa-angular support for Angular 9 es2015 build --prod support.

I Hope it  helps.

**Comment by amilaI** [comment]
> You can build with `ng build --prod` setting the target to es5 in your `tsconfig.json` file while arrives support for es2015. The disadvantage is that you will get a lot of warnings in your browser because es5 uses SystemJS for importing your angular components, and es2015 uses `import` instead of `SystemJS.import()`
> 
> Here is as you can edit your `tsconfig.json`
> 
> `"compilerOptions": { ... "target": "es5", ... `
> 
> I'm working with es5 target while arrives single-spa-angular support for Angular 9 es2015 build --prod
> 
> I Hope it helps.

Yeah. It worked. This helps until we get a new single-spa-angular version. :) Thanks

**Comment by joeldenning** [comment]
This is now released in single-spa-angular@4

**Comment by andreas-becker** [comment]
For me the following helped to fix the problem.
Open the file "_extra-webpack.config.js_" in your preferred editor
Remove the line "_library: 'YourAppName'_"

Save and try to build again

**Comment by eafiontzi** [comment]
@andreas-becker your solution worked for me! Thanks a lot!

**Comment by sivaraman-s** [comment]
> For me the following helped to fix the problem.
> Open the file "_extra-webpack.config.js_" in your preferred editor
> Remove the line "_library: 'YourAppName'_"
> 
> Save and try to build again

Thank you!. It works

**Comment by waltbest2** [comment]
> For me the following helped to fix the problem.
> Open the file "_extra-webpack.config.js_" in your preferred editor
> Remove the line "_library: 'YourAppName'_"
> 
> Save and try to build again

I used this method , but got no lifecycle export ,such as mount, unmount , etc
