### ISSUE TITLE
Unresolved dependency in mounted Angular 8 app

### ISSUE THREAD

**Issue by SB17** [single-spa/single-spa-angular#149]
Hello,

I am facing an unresolved dependency issue in an Angular 8 application that I am trying to load into single-spa. I did the following:

1. Created a root config (using npm init single spa)

2. Converted an existing Angular 8 application using Angular schematics (ng add single-spa-angular)

3. Verified that all the schematics files have been created

4. Configured the routes (APP_BASE_HREF, EmptyRouteComponent etc)

5. Created a set-public-path.js file with a call to 'setPublicPath("lego1")' and imported it to root-config.js of Root application.

However, on trying to mount the application I get an 'Uncaught Error: application 'lego1' died in status SKIP_BECAUSE_BROKEN: Can't resolve all parameters for AbpUserConfigurationService: (?)'

![image](https://user-images.githubusercontent.com/30361684/77256392-4cc86980-6c44-11ea-8f74-936441b865eb.png)

The AbpUserConfigurationService comes from one of the node libraries that my angular application imports. 

Am I right in thinking that the unresolved dependency is due to the way my application is bundled? However setting public path does not seem to help me here (there are 1000+ chunks that build/serve creates). I also tried to limit the chunk to 1 using LimitChunkCountPlugin but was not successful. Is there something else that I can try?  

[angular.json.txt](https://github.com/single-spa/single-spa-angular/files/4365752/angular.json.txt)
[tsconfig.json.txt](https://github.com/single-spa/single-spa-angular/files/4365757/tsconfig.json.txt)

**Comment by joeldenning** [comment]
This seems related to AbpUserConfigurationService, not to single-spa. Do you know which parameter is missing from it? The `(?)` seems to indicate that the error message didn't report which parameter was missing.

**Comment by SB17** [comment]
Thanks for your quick reply. The AbpUserConfigurationService comes from a library packaged as npm which my code uses. It has an HttpClient injected into it.

I cloned that repo and commented the AbpUserConfigurationService and its references in its entirety. But doing so results in same error with some other class in that library. This is what led me to think that the library code itself is not being correctly loaded.

**Comment by joeldenning** [comment]
Hmm this is hard to diagnose with the information provided, and it doesn't necessarily seem related to single-spa or single-spa-angular.

I'm going to close this since I don't think it's an issue with single-spa-angular - if you discover that it is related then please reopen.
