### ISSUE TITLE
Support for Angular 9?

### ISSUE THREAD

**Issue by varora1406** [single-spa/single-spa-angular#151]
I want to upgrade my app to Angular 9, but can't do until unless singla spa angular library can support it's changes.

Can we link bugs/things to do in Angular 9 support.
Plus let me know if I could be of any help here, would love to contribute to this. 💯

**Comment by joeldenning** [comment]
Hi @varora1406, I'd love help in getting support for Angular 9. Here are the issues I am aware of. I'd gladly accept pull requests that address them.

- https://github.com/single-spa/single-spa-angular/issues/148
- https://github.com/single-spa/single-spa-angular/issues/130
- https://github.com/single-spa/single-spa-angular/issues/128

**Comment by tanviavula** [comment]
When i am trying build angular9  getting following error:
src\single-spa\asset-url.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

ERROR in polyfills-es5.cb08cc69731928070aff.js from Terser
Invalid assignment [polyfills-es5.cb08cc69731928070aff.js:9,40]

**Comment by joeldenning** [comment]
Angular 9 is now supported in single-spa-angular@4. See https://github.com/single-spa/single-spa-angular/releases/tag/v4.0.0

**Comment by learnwithlakshman** [comment]
While serve i am facing following issue

ERROR in The target entry-point "single-spa-angular" has missing dependencies:
 - single-spa

**Comment by joeldenning** [comment]
@learnwithlakshman you should do `npm install --save single-spa`. This is something we still need to document after the 4.0 change, but you can see some notes about it at https://github.com/single-spa/single-spa-angular/releases/tag/v4.0.0
