### ISSUE TITLE
Schematics + documentation : Having outputhash none by default for production build

### ISSUE THREAD

**Issue by celian-garcia** [single-spa/single-spa-angular#168]
Hi guys,
I'm new in microfrontends and I find it very cool, so first of all, nice job to make it works with so many frameworks support !
I basically struggled a moment to make my Angular app working in production mode until I find this interesting post : https://github.com/single-spa/single-spa/issues/443

Out of that, why the schematics and/or documentation wouldn't be updated with this ``--output-hashing none`` parameter ?

Thanks you again and best regards,

Célian GARCIA

**Comment by joeldenning** [comment]
I'm open to changing that. For the [recommended setup](https://single-spa.js.org/docs/recommended-setup) we usually turn off webpack chunk hashing in favor of using the CI pipeline to insert a hash as a directory, for easier imports with systemjs.

Would gladly accept a PR for this

**Comment by joeldenning** [comment]
This was implemented in https://github.com/single-spa/single-spa-angular/pull/169 and released in 4.0.0. See https://github.com/single-spa/single-spa-angular/releases/tag/v4.0.0

**Comment by celian-garcia** [comment]
Great ! Indeed it's even better to put it in the ``angular.json`` config, I'll do so in my projects too, thanks !
