### ISSUE TITLE
Multiple calls to platformBrowserDynamic().bootstrapModule in main.single-spa.ts

### ISSUE THREAD

**Issue by friendly-tech** [single-spa/single-spa-angular#186]
Im exporting multiple modules/entry points from my `main.single-spa.ts` file as my childApp exposes smaller modules with a single component to be used as parcels as well as a main module used as an application - reason for this is i have components i want to share as well as the main application.

```
export const main = singleSpaAngular({
  bootstrapFunction: (singleSpaProps: SingleSpaProps) => {
    singleSpaPropsSubject.next(singleSpaProps);
    return platformBrowserDynamic().bootstrapModule(AppModule);
  },
  template: '<my-app-web-app-root></my-app-web-app-root>',
  Router,
  NgZone,
  AnimationEngine,
});

export const component1 = singleSpaAngular({
  bootstrapFunction: (singleSpaProps: SingleSpaProps) => {
    singleSpaPropsSubject.next(singleSpaProps);
    return platformBrowserDynamic().bootstrapModule(Component1Module);
    return null;
  },
  template: '<my-app-component1></my-app-component1>',
  NgZone
});
```

The the other end after i do 
```
from(window.System.import(appName))
      .pipe(map(m => m.main)).subscribe( m=> mountRootParcel(m, {domElement}));
etc..
```

This all works fine when i run my apps using `ng serve` - but when in production (using npm run build --prod) i get the error 
`No NgModule metadata found for 'AppModule'`

Removing the second `platformBrowserDynamic()` and the problem goes away, its like just having more than one `platformBrowserDynamic()` and it exludes the NgModule meta data.

Is there any way i can force the build to keep/produce this meta data even when multiple calls to `platformBrowserDynamic` are made?

**Comment by joeldenning** [comment]
Don't have time for a full, proper response right now but here's how I usually expose both a main app and a parcel or component from main.single-spa.ts:

```js
const app = singleSpaAngular({...})
export const bootstrap = app.bootstrap;
export const mount = app.mount;
export const unmount = app.unmount;

export const someParcel = singleSpaAngular({...})
```

^ This way the entire in-browser module is an application, but it also contains some named exports that are parcels. It's also entirely possible and fine to do it the way you had where `main` is the application.

**Comment by friendly-tech** [comment]
I assume you are calling `return platformBrowserDynamic().bootstrapModule(SomeModule);` in your bootstrap function for each of the components (and the app) - you have a module per exposed parcel component.


Dont you get an error during mount time when your app is built with `npm run build --prod` and you have this in you angular.json.

```
{
 "buildOptimizer": true,
 "optimization": true,
}
```

**Comment by joeldenning** [comment]
> I assume you are calling return platformBrowserDynamic().bootstrapModule(SomeModule); in your bootstrap function for each of the components (and the app) - you have a module per exposed parcel component.

That's what I would expect, yes. I personally don't use single-spa-angular as heavily as some of the other frameworks, so the exports naming pattern I'm describing is what I've done with react/vue.

> Dont you get an error during mount time when your app is built with npm run build --prod and you have this in you angular.json.

What error are you getting?

**Comment by friendly-tech** [comment]
I get the error
‘No NgModule metadata found for 'Xy’ ‘

Note - Xy could be anything after optimisation but it’s pointing to AppModule

If I remove one of the calls to platformBrowserDynamic()... then everything works fine

Also the error is only in prod build.

Something to do with AOT not handling multiple calls to this...

**Comment by arturovt** [comment]
@friendly-tech 

You can't have more than 1 `bootstrapModule` expressions.

https://github.com/angular/angular-cli/blob/08ec8318c1494e2548eae522a4d8720a7e6ec8c9/packages/ngtools/webpack/src/transformers/replace_bootstrap.ts#L99-L100

The compiler is looking for the first matching `bootstrapModule` statement in `main.ts` file and replaces it with `platformBrowser().bootstrapModuleFactory(AppNgModuleFactory)`.

You can bootstrap 2 different components but not 2 modules.

**Comment by friendly-tech** [comment]
Interesting..
I dont see How you can expose multiple parcel from an angular app in this case, i tried adding multiple bootstrap components to single module but this leads to a few issues.

1.You need to dynamically choose the template in the bootstrap function based on passed in params, which you cant do - i tried a hack setting domElement.innerHTML inside bootstrap func but got error 2 below.

2.Bootstrapped components are expected to all be present in the dom - i just want to mount a specific one and have the other ignored i get errors about any bootstrapped component that isnt in the template.

3.Tried some hack with bootstrapping every available component and adding *ngIf and only showing the component i want but its smelly and i dont like it.

**Comment by arturovt** [comment]
Sorry, I don't know what you're trying to achieve. I just mentioned that the behaviour you're observing with multiple `bootstrapModule` calls is by design.

**Comment by friendly-tech** [comment]
Found a way to do it using [DoBootstrap](https://angular.io/api/core/DoBootstrap) and changing the html content of the dom element so they match up (essentially switching out the component you want to bootstrap and render based on args passed) - so one module with multiple entry components and a dynamic way to choose which is bootstrapped and rendered.

Something like

```
@NgModule({
  declarations: [
    AppComponent,
    TestComponent
  ],
  imports: [],
  bootstrap: [],
  entryComponents: [AppComponent, TestComponent]
})
export class AppModule implements DoBootstrap {
  public static componentName: string;
  ngDoBootstrap(appRef: ApplicationRef) {
    switch (AppModule.componentName) {
      case "app": {
        appRef.bootstrap(AppComponent);
      }
      case "test": {
        appRef.bootstrap(TestComponent);
      }
    }
  }
}
```


```
export const main = singleSpaAngular({
  bootstrapFunction: (singleSpaProps: SingleSpaProps) => {
    singleSpaPropsSubject.next(singleSpaProps);
    //This line decides what component is bootstrapped using DoBootstrap
    AppModule.componentName = "test";
    // Change the innerhtml of the Dom element to match the component you are rendering
    (singleSpaProps as any).domElement.innerHTML = '<test-component></test-component>';
    return platformBrowserDynamic().bootstrapModule(AppModule);
  },
  template: '<app-component></app-component>',
  Router,
  NgZone,
  AnimationEngine,
});

```

**Comment by arturovt** [comment]
Glad you've found a solution.

You could actually store that property in `singleSpaPropsSubject` thus you can avoid having static properties.
You could also have lazy-loadable components, since if you've got 10 components and you wanna render only 1 then other 9 will be bundled too. `switch + import(...).then(...)` will do the trick.
