### ISSUE TITLE
Custom props not allowed in mount lifecycle

### ISSUE THREAD

**Issue by aniketavhad** [single-spa/single-spa-angular#195]
I need to register `globalEventDistributor` as custom props to communicate between MFE's.
So for that, I were passing props to mount lifecycles, But unfortunately that is no longer works.
Here is my sample code,

```
export function mount(props) {
  bus.globalEventDistributor = props.globalEventDistributor;
  return lifecycles.mount(props);
}
```
But now its giving me error as saying,

> This expression is not callable.
>   Not all constituents of type 'LifeCycleFn<{}> | LifeCycleFn<{}>[]' are callable.
>     Type 'LifeCycleFn<{}>[]' has no call signatures

Can anybody help me, how to pass props to mount lifecycle

**Comment by joeldenning** [comment]
This looks like a typescript-only error, not a runtime error. Single-spa still passes props into the lifecycle functions.

What version of single-spa and single-spa-angular are you using? single-spa-angular@4 now uses the `LifeCycles` type from single-spa, which is defined in the single-spa repo:

https://github.com/single-spa/single-spa/blob/48034c1474cb2829359edc58747aecf7879933f9/typings/single-spa.d.ts#L54

**Comment by arturovt** [comment]
It doesn't work because the compiler tries to infer a _callable_ type and meets `LifeCycleFn<T> | Array<LifeCycleFn<T>>`. And its message is pretty clear `Type 'LifeCycleFn<{}>[]' has no call signatures`, that means that this type cannot be used as a function expression.

This will work:
```ts
export function mount<T = any>(props: any) {
  bus.globalEventDistributor = props.globalEventDistributor;
  return (lifecycles.mount as LifeCycleFn<T>)(props);
}
```
You have to tell the compiler that you know what you're doing and you're there is a function expression and not an array.

**Comment by aniketavhad** [comment]
> It doesn't work because the compiler tries to infer a _callable_ type and meets `LifeCycleFn<T> | Array<LifeCycleFn<T>>`. And its message is pretty clear `Type 'LifeCycleFn<{}>[]' has no call signatures`, that means that this type cannot be used as a function expression.
> 
> This will work:
> 
> ```ts
> export function mount(props: any) {
>   bus.globalEventDistributor = props.globalEventDistributor;
>   return (lifecycles.mount as LifeCycleFn<any>)(props);
> }
> ```
> 
> You have to tell the compiler that you know what you're doing and you're sure there is a function expression and not an array.
> 
> Or this:
> 
> ```ts
> export function mount(props: any) {
>   bus.globalEventDistributor = props.globalEventDistributor;
>   if (typeof lifecycles.mount === 'function') {
>     return lifecycles.mount(props);
>   } else {
>     return Promise.all(lifecycles.mount.map(mount => mount(props)));
>   }
> }
> ```

@arturovt  Thanks for the solution you provided, My issue got resolved.
