### ISSUE TITLE
Load image background url Sass

### ISSUE THREAD

**Issue by jimmyhdolores** [single-spa/single-spa-angular#202]
As they do in the case that Image by Sass is loaded for example

.body-row {

background: url ("/ assets / images / myimage.jpg") without repetition bottom right;
}

I set the setPublicPath but keep throwing 404

Libs:
- @angular/core version: 9.1.7
- single-spa-angular version: 4.0.1

**Comment by joeldenning** [comment]
This question was first asked in https://github.com/single-spa/single-spa-angular/issues/59#issuecomment-634432405. I responded in https://github.com/single-spa/single-spa-angular/issues/59#issuecomment-634795136. Could you confirm if the options described there work?

**Comment by jimmyhdolores** [comment]
Hello, thanks for the prompt response, I will carry out the tests and we will confirm

**Comment by jimmyhdolores** [comment]
hello, I tried the options that I provide, but angular 8 and 9 apparently forces to put a '/' forward and because of that it gives the following error
 
más detalle aqui https://github.com/angular/angular-cli/issues/10004

![prueba1](https://user-images.githubusercontent.com/10909792/83057417-7e7ef780-a01c-11ea-8c87-85d9089d3116.png)

Because of that, you cannot concatenate the public variable PATCH either, even if you put it in a Sass variable, after searching and reviewing the angular.json file, you get to this option: "rebaseRootRelativeCssUrls": true

https://github.com/angular/angular-cli/issues/14758#issuecomment-501693532

agregar esta propiedad no fue suficiente, tube que modificar el atributo "output" de esta maneras:

ANTES
![prueba2](https://user-images.githubusercontent.com/10909792/83058319-d0744d00-a01d-11ea-9b40-85c10b71ee18.jpg)

THEN
![prueba3](https://user-images.githubusercontent.com/10909792/83058373-e3871d00-a01d-11ea-8c15-576562eb9fff.jpg)

add "/" to "assets", that way it manages to load the images and I don't have to modify anything in Sass
![prueba4](https://user-images.githubusercontent.com/10909792/83058651-5395a300-a01e-11ea-822d-33b787b18fa4.jpg)

Hope this helps someone else, thanks for listening @joeldenning

**Comment by filoxo** [comment]
This appears to be solved.

**Comment by jimmyhdolores** [comment]
This information should be added to your documentation, unless you have found a better way to use the routes in Sass.

**Comment by joeldenning** [comment]
Sure, would you like to add it to the documentation? Here is the file to change: https://github.com/single-spa/single-spa.js.org/blob/master/website/versioned_docs/version-5.x/ecosystem-angular.md

**Comment by jimmyhdolores** [comment]
Thank you, I will make the pull request
