### ISSUE TITLE
How to use Angular RouteReuseStrategy with Single-SPA?

### ISSUE THREAD

**Issue by Sally-yu** [single-spa/single-spa-angular#203]
I make a demo based on coexisting-angular-microfrontends project; there 3 applications ,like this:

        singleSpa.registerApplication(
            'app1',
            function () {
                return System.import('app1');
            },
            function (location) {
                return location.pathname.startsWith('/app1');
            }
        );

        singleSpa.registerApplication(
            'app2',
            function () {
                return System.import('app2');
            },
            function (location) {
                return location.pathname.startsWith('/app2');
            }
        );

        singleSpa.registerApplication(
            'app3',
            function () {
                return System.import('app3');
            },
            function (location) {
                return location.pathname.startsWith('/app3');
            }
        )

        singleSpa.start();
It works all good without using RouteReuseStrategy,I can correctly navigate between app1,app2,app3... 
When using RouteReuseStrategy in app1,it's also fine navigating inside app1, and components can be restored. 
But there is an error when navigate to app1 from app2 or app3, then app1 components crash

the error looks like this:

`Cannot reattach ActivatedRouteSnapshot created from a different route`

I try to decalre a global RouteReuseStrategy var and initlize it in root-html file, then use it in app1, but also the same result.

So, how to use Angular RouteReuseStrategy with Single-SPA? I need reuse app1's components when navigate from other appliactions.

**Comment by Sally-yu** [comment]
angualr ver is 8.2.3

**Comment by arturovt** [comment]
Could you provide a minimal reproducible example? *Please* :slightly_smiling_face:

**Comment by Sally-yu** [comment]
@arturovt  OK, here is the repo 
[https://github.com/Sally-yu/angular-with-single-spa](url)

**Comment by arturovt** [comment]
Thank you, I will have a look asap!

**Comment by Sally-yu** [comment]
@arturovt  THX a lot!
just run 
`npm i`
`npm start`
or the yarn command in /app1  /app2 /app3 /navbar /root-html-file, just like coexisting-angular-microfrontends. 

some tips like this image;
![image](https://user-images.githubusercontent.com/20413765/83134460-faf60100-a116-11ea-9b47-8f78f44ac29d.png)


If use static cache in reusestrategy, the same error

I try to hack mount & unmout function to keep app1's module and Router, but failed.

**Comment by arturovt** [comment]
You didn't tell any steps to reproduce:

![image](https://user-images.githubusercontent.com/7337691/83296820-138b1780-a1fa-11ea-8fcf-5440864ade03.png)

What should I do to reproduce it?

**Comment by Sally-yu** [comment]
I have hacked single-spa-angular for my own project,Thx a lot.

**Comment by TTQ99** [comment]
@Sally-yu   遇到同样的问题， 请问最后如何解决的
