### ISSUE TITLE
Schematics generate a buggy template for the 'bootstrapFunction'

### ISSUE THREAD

**Issue by Vallerious** [single-spa/single-spa-angular#209]
### Demonstration

1. Create a new angular 8 project
2. Run "ng add single-spa-angular@3.0.0"
3. Do the manual steps described in the docs.
4. Register the application in 'coexisting-angular-microfrontends'
5. Try the new route

### Expected Behavior
The new route works and content is seen.
### Actual Behavior
Observe error:
```
zone.js:192 Uncaught Error: 	
            single-spa-angular: could not retrieve extra providers from the platform injector. Did you call platformBrowserDynamic(getSingleSpaExtraProviders()).bootstrapModule() when creating platform?	
          
    at single-spa-angular.js:178
    at ZoneDelegate.invoke (zone.js:386)
    at Zone.run (zone.js:143)
    at zone.js:891
    at ZoneDelegate.invokeTask (zone.js:421)
    at Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.invokeTask [as invoke] (zone.js:507)
    at invokeTask (zone.js:1671)
    at HTMLScriptElement.globalZoneAwareCallback (zone.js:1697)
```

### Workaround:
As seen from the error message, we have to call 'getSingleSpaExtraProviders' in our bootstrapFunction, which is not scaffolded that way by default.

Am I using the wrong version combination of Angular and single-spa-angular?

**Comment by filoxo** [comment]
Which version of single-spa-angular ends up in your project's package.json?

**Comment by filoxo** [comment]
We currently check to see if your project has routing, and only inject the getSingleSpaExtraProviders based on that. https://github.com/single-spa/single-spa-angular/blob/master/schematics/ng-add/_files/src/main.single-spa.ts.template#L8

**Comment by joeldenning** [comment]
It looks like we implemented this in single-spa-angular@4, but not in single-spa-angular@3. See the code below from the 3.x branch that shows that the schematics are wrong:

https://github.com/single-spa/single-spa-angular/blob/fd72066faf3b3c632126f2e0eeca70ce4ec51a40/src/schematics/ng-add/_files/src/main.single-spa.ts.template#L19

I would gladly review a PR to fix this.

**Comment by Vallerious** [comment]
Wow @filoxo that was fast 🗡️ I wanted to make a contri.

**Comment by filoxo** [comment]
Sorry @Vallerious! We definitely would love to have you contribute sometime. #208 perhaps?

**Comment by joeldenning** [comment]
This fix is released in https://github.com/single-spa/single-spa-angular/releases/tag/v3.5.2
