### ISSUE TITLE
Loading Angular8 app with React 16 application

### ISSUE THREAD

**Issue by hiaparna** [single-spa/single-spa-angular#212]
### Environment
Angular application:
    "single-spa": "5.2.0",
    "single-spa-angular": "4.2.0",
React application:
     "single-spa": "5.0.0",
    "single-spa-react": "2.9.0",

Getting this error when I try to load. Pls let me know if any more details are required.
 ```
UNMOUNTING: Cannot read property 'injector' of undefined
    at main.js:198203
    at Generator.next (<anonymous>)
    at main.js:198526
    at new Promise (<anonymous>)
    at __awaiter (main.js:198522)
    at unmount (main.js:198200)
    at single-spa.min.js:2

SKIP_BECAUSE_BROKEN: In this configuration Angular requires Zone.js
    at new NgZone (main.js:52438)
    at getNgZone (main.js:53649)
    at PlatformRef.bootstrapModuleFactory (main.js:53472)
    at main.js:53557
```

**Comment by joeldenning** [comment]
> In this configuration Angular requires Zone.js

See https://single-spa.js.org/docs/ecosystem-angular#zonejs and https://github.com/joeldenning/coexisting-angular-microfrontends/blob/2f0df6313e665de07a469e9bc569967e7707e756/root-html-file/index.html#L22

You must include ZoneJS as a global script in order for Angular to work.

**Comment by arturovt** [comment]
@hiaparna was the issue resolved?
@joeldenning can we close this issue due to inactivity?

**Comment by joeldenning** [comment]
Sure let's close this. Feel free to reopen or comment further
