### ISSUE TITLE
Webpack config has hard-coded "app3" library name

### ISSUE THREAD

**Issue by KevinCathcart** [single-spa/single-spa-angular#220]
The Webpack configuration has a hard-coded library name of "app3" as seen here:

https://github.com/single-spa/single-spa-angular/blob/6e3f36c22afbf5a75526aa5bf8e140dff6f85553/src/webpack/index.ts#L5-L9

That is both really weird, and is likely to cause problems in some scenarios.

It definitely causes problems if one decides they want a `libraryTarget` of `system` instead of `umd`, (perhaps because one would rather not pull in the amd extra for SystemJs), because this will force a named registration, requiring the named extra.

Not to mention the whole registering different modules with the same name thing under umd's amd mode or when using named `System.register` syntax.

Last but not least, this sets the webpack JSONP function to be `webpackJsonpapp3`, for all apps.

Looks like [this was noticed](https://github.com/single-spa/single-spa-angular/commit/52f55ce62e831274d0df05639f15b7b8e0580f27#r36137959) a while back, but did not get resolved. 

As reported there putting "libraryName" directly under Options fails due to builder schema validation failure. Custom properties passed to custom webpack builder must be placed in the "customWebpackConfig" object, which allows for unknown properties.

Of course, even better would be some way to actually get the Angular project name, and use that. There is a way, but only when using `@angular-builders/custom-webpack` version 9. If using that, the custom webpack config function gets a third argument, which includes the target project name, which could be passed into `singleSpaAngularWebpack()`. Sadly, this only works for Angular 9.

**Comment by joeldenning** [comment]
Agreed that's weird - I'm not sure when/how that snuck in. Let's change it. I just verified that this is in both single-spa-angular@3 and single-spa-angular@4.

> Of course, even better would be some way to actually get the Angular project name, and use that. There is a way, but only when using @angular-builders/custom-webpack version 9. If using that, the custom webpack config function gets a third argument, which includes the target project name, which could be passed into singleSpaAngularWebpack(). Sadly, this only works for Angular 9.

Can we not get the Angular project name via something like this?

```ts
require(path.join(process.cwd(), 'angular.json'))
```

Would that perhaps not work with Angular Workspaces?

**Comment by joeldenning** [comment]
> Not to mention the whole registering different modules with the same name thing under umd's amd mode or when using named System.register syntax.

Yes for systemjs usage, the output.library  option should be deleted via custom webpack builder

**Comment by KevinCathcart** [comment]
Yeah, in a multiple project workspace, there is no easy way to tell which of the various projects just invoked the custom-webpack builder, except using the new third parameter.

That said, multi-project workspaces are probably not common under single-spa. I’d personally be fine with having the default pull from there if there is only one project, and error for the multi-project workspace case if the user has not manually specified a name. The cases I care about are all single project.

The other part about that approach i’m not entirely sure about is if the CWD is guaranteed to be the directory with angular.json if invoked by `ng build` while in some subdirectory. I’d not be surprised to hear it is always set to that directory, but also not be surprised if that was not the case.

As for deleting library, yeah, that is what I ended up doing. I would appreciate it if the default (once updated) redundantly set `jsonpFunction`, so that both deleting the variable does not require manually setting  `jsonpFunction` as well.

**Comment by joeldenning** [comment]
> I would appreciate it if the default (once updated) redundantly set jsonpFunction, so that deleting the library property does not also require manually setting jsonpFunction as well.

Yes, I agree. Let's add jsonpFunction to the single-spa-angular webpack config.

Do you think we should consider switching the libraryTarget from `umd` to `system`? For Vue we have it set to UMD, but for react we have it set to `system`. The single-spa recommended setup encourages SystemJS, and when the libraryTarget is system it is no longer required (or encouraged) to set `output.library`, which would mean we wouldn't have to come up with a project name for it at all. Making that change would be a breaking change to single-spa-angular, but might be worth it?

https://github.com/single-spa/vue-cli-plugin-single-spa/blob/3fae56e6cd6cfdd509ee51ec53e536b8e6f70867/index.js#L14

https://github.com/single-spa/create-single-spa/blob/f043b6d40f9a365ebf35528304a39754ba670073/packages/webpack-config-single-spa/lib/webpack-config-single-spa.js#L32

> That said, multi-project workspaces are probably not common under single-spa. I’d personally be fine with having the default pull from there if there is only one project, and error for the multi-project workspace case if the user has not manually specified a name.

I agree it's not very common for single-spa-angular users to use Angular Workspaces, but it is something that we support. See related https://github.com/single-spa/single-spa-angular/issues/220. If we end up still needing to choose a library name, I think we'd want to check for third argument, then check for angular json file, then use a default name if none of those work.

**Comment by KevinCathcart** [comment]
I'm not sure the benefits of not having to set library is really that significant, given that we would still want to set the jsonpFunction to something unique. 

Honestly, though, I'm rather indifferent about the default libraryTarget. 

It turns out that that third parameter to `extra-webpack.config.js`, only applies to @angular-builders/custom-webpack 9.2 which is still only in beta. 

Perhaps it is worth taking a step back.

In reality multiple projects don't share a single extra-webpack.config.js, unless the user manually changes angular.json to make it do so. So, a better approach for the first step might be to have the template that generates extra-webpack.config.js specify the project name in the template as a new parameter to `singleSpaAngularWebpack(...)`. At schematic time, you definitely have access to the project name. This does not need to be a breaking change as explained at the end of this post.

Therefore, I'm now proposing that change, with a fall back to angular.json, and then a default. 

The angular.json approach can work for the common case of only one project. However, `require(path.join(process.cwd(), 'angular.json'))`, is not quite good enough, as cwd is indeed not always the same directory as angulat.json. However a simple [findUp](https://github.com/angular/angular-cli/blob/master/packages/angular/cli/utilities/find-up.ts) function like angular-cli uses for this very purpose can solve that problem. 

Lastly, a fallback default. For this case, I'd suggest also printing a warning, advising the developer that they may want to update their `extra-webpack.config.js` to pass the argument. 

-----

Obviously updating the template does fix things for users who run the schematics. But they can fall back angular.json lookups 99% of the time, so in practice they will get fixed. And worse case, they fall back to the default, and can manually update their extra-webpack.config.js to match the template again, if they want to avoid this issue.
The default fallback should not break anybody who is not already broken by the "app3", so this would not be a breaking change.

There is one last tricky part: the additional parameter to `singleSpaAngularWebpack(...)` would need to account for the fact that there used to be an (unused) options argument passed by older versions of the template. A simple type check check on the parameter could differentiate.

Thoughts?

**Comment by akhilshastri** [comment]
@joeldenning & team firstly, thanks for this amazing project. i was trying to build nx workspace using single-spa,  while debugging, found this issue. I just want to highlight another use case of Angular workspace with nx. 
I think, it would be useful if this plugin also respect "customWebpackConfig" configuration, which will give developer more control to customise.

![image](https://user-images.githubusercontent.com/8503650/84580057-218f8980-adf1-11ea-99c4-5093fb58c2bf.png)

**Comment by KevinCathcart** [comment]
@akhilshastri I’m not clear on what you mean. single-spa-angular is already using the custom-webpack builder. When you run the schematic, it generates an extra-webpack.config.js file, in which it calls a function that applies some webpack changes. You can then apply any additional customizations you want. You can access any custom properties set in`customWebpackConfig` by adding a second parameter to the function in the file.

Currently the function that applies the webpack changes does not use any values from that part of angular.json. It could. I’m planning on writing a pull request to fix this, perhaps on Monday, unless somebody beats me to it. I could code it to use a property in customWebpackConfig. It is basically equivalent to what I proposed with changing the extra-webpack.config.json template, and perhaps slightly cleaner, since that argument used to be passed in, but simply was unused, so it later got removed. But adding it back again is hardly a problem.

If nx has some standardized set of names for such properties in customWebpackConfig or something like that, I’d be willing to code it to use them, assuming you can point me to any documentation about that.

**Comment by akhilshastri** [comment]
@KevinCathcart   nx does not have anything similar but what you are proposing i agree. my intention was to give control to developer for setting value of libraryName.

**Comment by KevinCathcart** [comment]
Yeah fair. I’ll go with that approach for the PR. It is basically
equivalent to what I proposed, and is cleaner.

So a value set there would be the first source. If not present, it will
fall back to trying to auto detect from angular.json. (Mostly for the
benefit of existing users). If that fails, it will use a hard coded
default, and print a message, suggesting the user may want to set the value
in angular.json. And also instructing them how to modify
custom-webpack.config.json if needed, since we can detect if options are
being passed through or not.

If going with this approach, we can also offer libraryTarget as an option,
making it easier to specify system, if the user wants it. Another advantage
of that, is that by changing what the schematic puts in
customWebpackConfig, it is possible to change the default libraryTarget
without it being a breaking change, since it would only impact new projects.

**Comment by joeldenning** [comment]
@akhilshastri 

> I just want to highlight another use case of Angular workspace with nx.

This sounds unrelated to this issue and should be discussed in a different issue or in the [single-spa slack workspace](https://join.slack.com/t/single-spa/shared_invite/enQtODAwNTIyMzc4OTE1LWUxMTUwY2M1MTY0ZGMzOTUzMGNkMzI1NzRiYzYwOWM1MTEzZDM1NDAyNWM3ZmViOTAzZThkMDcwMWZmNTFmMWQ)

@KevinCathcart 

> In reality multiple projects don't share a single extra-webpack.config.js, unless the user manually changes angular.json to make it do so. So, a better approach for the first step might be to have the template that generates extra-webpack.config.js specify the project name in the template as a new parameter to singleSpaAngularWebpack(...). At schematic time, you definitely have access to the project name. This does not need to be a breaking change as explained at the end of this post.

Sure, I think that this change makes sense.

> There is one last tricky part: the additional parameter to singleSpaAngularWebpack(...) would need to account for the fact that there used to be an (unused) options argument passed by older versions of the template. A simple type check check on the parameter could differentiate.

Agreed.

Do you have interest in submitting a pull request to make this change? We have both the 3.x and master branches, which would both need to change.

**Comment by KevinCathcart** [comment]
I’m working on a pull request, have something mostly done, was hoping to
push it as a draft yesterday, but was a bit too busy.

Hopefully I can get to it this evening.

**Comment by joeldenning** [comment]
This is released in https://github.com/single-spa/single-spa-angular/releases/tag/v4.3.1 for Angular versions 9-10.

We should also make this change in the `3.x` branch for Angular versions 2-8. I'll keep this issue open to track that.

**Comment by joeldenning** [comment]
Just saw the 3.x PR. It is at https://github.com/single-spa/single-spa-angular/pull/236

**Comment by filoxo** [comment]
Closing as this has also been released in https://github.com/single-spa/single-spa-angular/releases/tag/v3.6.0 for Angular 8 and below.
