### ISSUE TITLE
Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?

### ISSUE THREAD

**Issue by kiddliu** [single-spa/single-spa-angular#221]
### Demonstration

After spending hours on shared dependencies, I finally managed to get it working with Angular@9.1.9 + zone.js@0.10.3 + single-spa@5.5.3 + SystemJS@6.3.2, except a warning 'Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?'

In my root config file, it's
```html
  <script src="https://cdn.jsdelivr.net/npm/zone.js@0.10.3/dist/zone.js"></script>
  <meta name="importmap-type" content="systemjs-importmap" />
  <script type="systemjs-importmap">
    {
      "imports": {
        "single-spa": "https://cdn.jsdelivr.net/npm/single-spa@5.5.3/lib/system/single-spa.dev.js",
        "rxjs": "https://cdn.jsdelivr.net/npm/@esm-bundle/rxjs@6.5.5-fix.1/system/es2015/rxjs.min.js",
        "rxjs/operators": "https://cdn.jsdelivr.net/npm/@esm-bundle/rxjs@6.5.5-fix.1/system/es2015/rxjs-operators.min.js",
        "@angular/core": "https://cdn.jsdelivr.net/npm/@esm-bundle/angular__core@9.1.9/system/es2015/angular-core.js",
        "@angular/common": "https://cdn.jsdelivr.net/npm/@esm-bundle/angular__common@9.1.9/system/es2015/angular-common.js",
        "@angular/platform-browser": "https://cdn.jsdelivr.net/npm/@esm-bundle/angular__platform-browser@9.1.9/system/es2015/angular-platform-browser.js",
        "@angular/router": "https://cdn.jsdelivr.net/npm/@esm-bundle/angular__router@9.1.9/system/es2015/angular-router.js"
      }
    }
  </script>
  <link rel="preload" href="https://cdn.jsdelivr.net/npm/single-spa@5.5.3/lib/system/single-spa.dev.js" as="script" crossorigin="anonymous" />
  <link rel="preload" href="https://cdn.jsdelivr.net/npm/@esm-bundle/angular__common@9.1.9/system/es2015/angular-common.js" as="script" crossorigin="anonymous" />
  <link rel="preload" href="https://cdn.jsdelivr.net/npm/@esm-bundle/angular__core@9.1.9/system/es2015/angular-core.js" as="script" crossorigin="anonymous" />
  <link rel="preload" href="https://cdn.jsdelivr.net/npm/@esm-bundle/angular__platform-browser@9.1.9/system/es2015/angular-platform-browser.js" as="script" crossorigin="anonymous" />
  <link rel="preload" href="https://cdn.jsdelivr.net/npm/@esm-bundle/angular__router@9.1.9/system/es2015/angular-router.js" as="script" crossorigin="anonymous" />
  <link rel="preload" href="https://cdn.jsdelivr.net/npm/@esm-bundle/rxjs@6.5.5-fix.1/system/es2015/rxjs.min.js" as="script" crossorigin="anonymous" />
  <link rel="preload" href="https://cdn.jsdelivr.net/npm/@esm-bundle/rxjs@6.5.5-fix.1/system/es2015/rxjs-shared.min.js" as="script" crossorigin="anonymous" />
  <link rel="preload" href="https://cdn.jsdelivr.net/npm/@esm-bundle/rxjs@6.5.5-fix.1/system/es2015/rxjs-operators.min.js" as="script" crossorigin="anonymous" />
  
  <% if (isLocal) { %>
  <script type="systemjs-importmap">
    {
      "imports": {
        "@example/root-config": "//localhost:9000/example-root-config.js"
      }
    }
  </script>
  <% } %>
  <script src="https://cdn.jsdelivr.net/npm/import-map-overrides@1.15.2/dist/import-map-overrides.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/systemjs@6.3.2/dist/system.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/systemjs@6.3.2/dist/extras/amd.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/systemjs@6.3.2/dist/extras/named-exports.js"></script>
</head>
<body>
  <main></main>
  <script>
    System.import('@example/root-config');
  </script>
```

### Expected Behavior
There should be no sunch warning.

### Actual Behavior
The warning is complaining that the bootstrapping to the default path of app1 is not triggered in the NgZone context.

I did some debugging and it looks like in the following code

```js
function bootstrap(opts, props) {
    return __awaiter(this, void 0, void 0, function* () {
        // Angular provides an opportunity to develop `zone-less` application, where developers
        // have to trigger change detection manually.
        // See https://angular.io/guide/zone#noopzone
        if (opts.NgZone === 'noop') {
            return;
        }
        // In order for multiple Angular apps to work concurrently on a page, they each need a unique identifier.
        opts.zoneIdentifier = `single-spa-angular:${props.name || props.appName}`;
        // This is a hack, since NgZone doesn't allow you to configure the property that identifies your zone.
        // See https://github.com/PlaceMe-SAS/single-spa-angular-cli/issues/33,
        // https://github.com/single-spa/single-spa-angular/issues/47,
        // https://github.com/angular/angular/blob/a14dc2d7a4821a19f20a9547053a5734798f541e/packages/core/src/zone/ng_zone.ts#L144,
        // and https://github.com/angular/angular/blob/a14dc2d7a4821a19f20a9547053a5734798f541e/packages/core/src/zone/ng_zone.ts#L257
        opts.NgZone.isInAngularZone = function () {
            // @ts-ignore
            return window.Zone.current._properties[opts.zoneIdentifier] === true;
        };
        opts.routingEventListener = () => {
            opts.bootstrappedNgZone.run(() => {
                // See https://github.com/single-spa/single-spa-angular/issues/86
                // Zone is unaware of the single-spa navigation change and so Angular change detection doesn't work
                // unless we tell Zone that something happened
            });
        };
    });
}
```
The hack is no longer working. After setting the `zoneIdentifier`, checking `NgZone.isInAngularZone` always returns false as the entries in `Zone.current._properties` are

```log
isAngularZone: true
maybeDelayChangeDetection: false
```

**Comment by filoxo** [comment]
This sounds like it could be related to #206.

**Comment by joeldenning** [comment]
This is a duplicate of https://github.com/single-spa/single-spa-angular/issues/53. As @arturovt said in that issue, this can be considered normal behavior. Angular has a hard assumption that there is only one zone on the page and only one router on the page - single-spa does not fit with those assumptions. I would accept a PR that patches Angular methods such that the warning is suppressed, but do not think it's very high priority to do so, which is why we closed #53.

> After spending hours on shared dependencies, I finally managed to get it working with Angular@9.1.9 + zone.js@0.10.3 + single-spa@5.5.3 + SystemJS@6.3.2

Are you using View Engine? Or Ivy Compiler? My understanding is that it is not possible to share dependencies with Angular 9's Ivy Compiler, so I'd guess you've turned it off in your project?

**Comment by arturovt** [comment]
This is one of the problems of sharing dependencies in Angular and why I'm not promoting it. `isInAngularZone` is a `static` method, not an instance method. When you share dependencies you basically get 1 `NgZone` class and N instances of `NgZone`, depending on the N of your applications.

When dependencies are shared then:
1) there are 1 `PLATFORM_INJECTOR`
2) there are N `NGZONE_INJECTOR`s

`isInAngularZone()` is used only by the `Router.navigateByUrl()` to check whether this method was called in the right context.

That warning that you see during bootstrapping is normal since it's applicable even to apps that do not share dependencies.
The `Router` class calls `navigateByUrl` under the hood inside `initialNavigation()` method to render the initial tree. We even have this warning in our integration apps but we don't observe any issues with routing and zones further.

**Comment by kiddliu** [comment]
> This is a duplicate of #53. As @arturovt said in that issue, this can be considered normal behavior. Angular has a hard assumption that there is only one zone on the page and only one router on the page - single-spa does not fit with those assumptions. I would accept a PR that patches Angular methods such that the warning is suppressed, but do not think it's very high priority to do so, which is why we closed #53.
> 
> > After spending hours on shared dependencies, I finally managed to get it working with Angular@9.1.9 + zone.js@0.10.3 + single-spa@5.5.3 + SystemJS@6.3.2
> 
> Are you using View Engine? Or Ivy Compiler? My understanding is that it is not possible to share dependencies with Angular 9's Ivy Compiler, so I'd guess you've turned it off in your project?

Yes, I turned off Ivy but leave AOT on.

**Comment by kiddliu** [comment]
> This is one of the problems of sharing dependencies in Angular and why I'm not promoting it. `isInAngularZone` is a `static` method, not an instance method. When you share dependencies you basically get 1 `NgZone` class and N instances of `NgZone`, depending on the N of your applications.
> 
> When dependencies are shared then:
> 
> 1. there is 1 `PLATFORM_INJECTOR`
> 2. there are N `NGZONE_INJECTOR`s

**Comment by arturovt** [comment]
There is not 1 zone, there are as many zones as bootstrapped applications.

Sharing dependencies with Angular doesn’t fit in single-spa scenario. Other solutions are possible and working since there are a lot of people that already have running single-spa apps.

And what do you mean by “for future apps”? What will change for future apps?

**Comment by kiddliu** [comment]
@arturovt I was thinking sharing deps may work now but not quite sure if it works tomorrow with future versions of Angular.

> Sharing dependencies with Angular doesn’t fit in single-spa scenario.

Thank you for confirming this. I'll close this ticket. You guys are truly wonderful creating single-spa and being so active in the community. Thank you!
