### ISSUE TITLE
unable to successfully run tests of this library

### ISSUE THREAD

**Issue by varora1406** [single-spa/single-spa-angular#222]
### Demonstration
clone the project, run `yarn install` and then `yarn test`

### Expected Behavior
All tests should pass

### Actual Behavior
index.spec.ts test is failing due to `/` in path

Below is the console information
> yarn run v1.22.0
> $ yarn clean && jest
> $ rimraf lib
>  PASS  schematics/ng-add/tests/issue-168.spec.ts (21.052s)
>  PASS  schematics/ng-add/tests/add-scripts.spec.ts (21.074s)
>  FAIL  schematics/ng-add/tests/index.spec.ts (21.127s)
>   ● ng-add › should modify angular.json
> 
>     expect(received).toEqual(expected) // deep equality
> 
>     Expected: "projects/ss-angular-cli-app/src/main.single-spa.ts"
>     Received: "projects\\ss-angular-cli-app\\src\\main.single-spa.ts"
> 
>       120 |     expect(ssApp.architect.serve.builder).toBe('@angular-builders/custom-webpack:dev-server');
>       121 |
>     > 122 |     expect(ssApp.architect.build.options.main).toEqual(
>           |                                                ^
>       123 |       'projects/ss-angular-cli-app/src/main.single-spa.ts',
>       124 |     );
>       125 |     expect(ssApp.architect.build.options.customWebpackConfig).toEqual({
> 
>       at schematics/ng-add/tests/index.spec.ts:122:48
>       at step (schematics/ng-add/tests/index.spec.ts:33:23)
>       at Object.next (schematics/ng-add/tests/index.spec.ts:14:53)
>       at fulfilled (schematics/ng-add/tests/index.spec.ts:5:58)
> 
> Test Suites: 1 failed, 2 passed, 3 total
> Tests:       1 failed, 13 passed, 14 total
> Snapshots:   0 total
> Time:        22.928s, estimated 53s
> Ran all test suites.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by arturovt** [comment]
:thinking: I'm on `master` w/o anything modified.

![image](https://user-images.githubusercontent.com/7337691/84688748-89a4b380-af48-11ea-9aa7-3b6688fdcf68.png)

**Comment by arturovt** [comment]
What OS are you using?

**Comment by varora1406** [comment]
Windows 10

**Comment by filoxo** [comment]
This does appear to be platform-specific. I wonder if the tests should attempt to convert those path strings into path objects (https://nodejs.org/api/path.html#path_path_parse_path) and then compare those.

@varora1406 would you be willing to contribute a fix?

**Comment by varora1406** [comment]
This is resolved with #228, closing this issue now
