### ISSUE TITLE
An unhandled exception occurred: Collection "single-spa-angular" cannot be resolved. See "/tmp/ng-VEvanI/angular-errors.log" for further details.

### ISSUE THREAD

**Issue by ajithgadgeon14** [single-spa/single-spa-angular#223]
### Demonstration

Tried to run -> ng add single-spa-angular in angular project version 8.2.
reference link: https://single-spa.js.org/docs/ecosystem-angular/#schematics

### Expected Behavior

Angular schematics are processed when you run ng add single-spa-angular.

The single-spa-angular schematics perform the following tasks:

Install single-spa-angular.
Generate a main.single-spa.ts in your project src/.
Generate single-spa-props.ts in src/single-spa/
Generate asset-url.ts in src/single-spa/
Generate an EmptyRouteComponent in src/app/empty-route/, to be used in app-routing.module.ts.
Add an npm script npm run build:single-spa.
Add an npm script npm run serve:single-spa

### Actual Behavior

An unhandled exception occurred: Collection "single-spa-angular" cannot be resolved. See "/tmp/ng-VEvanI/angular-errors.log" for further details.

**Comment by joeldenning** [comment]
Hi @ajithgadgeon14 - for Angular 8 you should use single-spa-angular@3.x instead of single-spa-angular@4. Try running either of the following commands, instead?

```sh
ng add single-spa-angular@angular-pre-9

# or
ng add single-spa-angular@3
```

**Comment by arturovt** [comment]
@ajithgadgeon14 was the issue resolved?

**Comment by arturovt** [comment]
@joeldenning can we close this issue due to inactivity?
