### ISSUE TITLE
¿How to load third-party text fonts

### ISSUE THREAD

**Issue by jimyhdolores** [single-spa/single-spa-angular#224]
### ¿How to load third-party text fonts
 I have a package installed and which I use its sources, and add them to the angular.json file

```json
"assets": [
              "src/favicon.ico",
              "src/assets",
              {
                "glob": "**/*",
                "input": "node_modules/@mylibrary/scss-theme/theme/assets",
                "output": "assets"
              },
            ],
```
When I test it locally it works, but in production it does not, it still points to the main path, that is, to the project that registers the applications, I hope you can help me.

Libs:
- @angular/core version: 9.1.7
- single-spa-angular version: 4.2.0

**Comment by joeldenning** [comment]
When you build for production, are you providing the `--deploy-url` flag? Example at https://github.com/joeldenning/coexisting-angular-microfrontends/blob/925dd8ec4f7f149eeba305f4e3cc4e9783abf3db/app1/package.json#L11

The `--deploy-url` flag tells Angular the base URL to use when loading assets in a production build.

**Comment by jimmyhdolores** [comment]
in your example you put --deploy-url / dist / app1 does this have to do with setting your angular.json?

"outputPath": "dist / app1"

or should the domain where the application in production is being deployed go? example:

--deploy-url mydomain.com

**Comment by jimmyhdolores** [comment]
Well, I tried it in various ways with --deploy-url but it doesn't take effect, it still makes the call from the root of the container (my root config application that registers to the other applications) some tip?

**Comment by joeldenning** [comment]
> in your example you put --deploy-url / dist / app1 does this have to do with setting your angular.json?

It has to do with where the code is hosted.

> Well, I tried it in various ways with --deploy-url but it doesn't take effect, it still makes the call from the root of the container (my root config application that registers to the other applications) some tip?

You can try Angular's `rebaseRootRelativeCssUrls` option. See https://github.com/single-spa/single-spa.js.org/pull/282/files and https://angular.io/cli/build

**Comment by eduardocalixtoviasoft** [comment]
As far as I know deploy url works, but still some cases are not cover by it, which means, for example, that css background url is not affected by it. Anyway our solution was to get all needed fonts in our loader, this way this files is available even if it's not getting from the app location. 
Another possible solution (we think about it but we currently do not need it) is to do a post build alteration, meaning that any missing asset url will be fixed after the app build

**Comment by filoxo** [comment]
Closing since a solution seems to have been reached.

**Comment by pearlpandz** [comment]
> When you build for production, are you providing the `--deploy-url` flag? Example at https://github.com/joeldenning/coexisting-angular-microfrontends/blob/925dd8ec4f7f149eeba305f4e3cc4e9783abf3db/app1/package.json#L11
> 
> The `--deploy-url` flag tells Angular the base URL to use when loading assets in a production build.

It took 2days to find this solution, anyway that's my fault to delete the single spa boilerplate code.
Really thank you @joeldenning 💯 working
