### ISSUE TITLE
Loading additional scripts in Angular 9 cli 

### ISSUE THREAD

**Issue by architechcro** [single-spa/single-spa-angular#230]
**Describe the bug or question**
Main application is done in preact, and "child" app is done in Angular 9 cli.
Adding additional scripts as described in https://single-spa.js.org/docs/ecosystem-angular#scripts
results in error:  "Unhandled Promise rejection: Unable to dynamically transpile ES module"
In standalone Angular app script is loaded as part of [scripts] in angular.json.

**To Reproduce**
For bugs, create a small git repo or codepen that reproduces the problem, and provide steps on how to see the issue. This is also helpful for questions.

**Comment by architechcro** [comment]
I am using Option 2

I've managed to solve it 

```
export function bootstrap(props) {
  return new Promise((resolve, reject) => {
    Promise.all(
      [
         loadScript('https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.js'),
         loadScript('https://cdnjs.cloudflare.com/ajax/libs/easy-pie-chart/2.1.6/easypiechart.min.js'),
         loadScript('https://cdnjs.cloudflare.com/ajax/libs/screenfull.js/5.0.2/screenfull.min.js'),
         loadScript('https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.min.js'),
      ]
    ).then( () => {
      Log.debug('Bootstrap resolve');
      resolve();
    }).catch(err => {
      Log.error('Bootrstrap error', err);
    });
  });
}
```

**Comment by joeldenning** [comment]
Happy to hear you solved it
