### ISSUE TITLE
Issue in single-spa-angular 3.5.3 with Angular 9 apps

### ISSUE THREAD

**Issue by phonethantko** [single-spa/single-spa-angular#233]
> [single-spa-angular@4 does not work with Angular 2-8. Only Angular 9](https://github.com/single-spa/single-spa-angular/releases/tag/v4.0.0). create-single-spa does not specify a version (because as a generic tool, it assumes the latest tooling versions). 
> 
> I was make some progress after this failure by:
> 
> - reverting the changes that happened before the process failed (`git reset --hard`)
> - running `ng add single-spa-angular@3.5.1`
> - add missing single-spa dependency `npm install single-spa -S`
> - running serve script `npm run serve:single-spa:[app name goes here]`
> 
> Then I get the following error:
> 
> ```sh 
> ~/dev/ng8test on  master ● ●
> ❯ npm run serve:single-spa:navbar
> 
> > navbar@0.0.0 serve:single-spa:navbar /Users/carlosfiloteo/dev/ng8test
> > ng s --project navbar --disable-host-check --port 4200 --deploy-url http://localhost:4200/ --live-reload false
> 
> WARNING: Running a server with --disable-host-check is a security risk. See https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a for more information.
> WARNING: --deploy-url and/or --base-href contain unsupported values for ng serve. Default serve path of '/' used. Use --serve-path to override.
> 10% building 1/1 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
> ℹ ｢wds｣: webpack output is served from /
> ℹ ｢wds｣: Content not from webpack is served from /Users/carlosfiloteo/dev/ng8test/src
> 
> chunk {main} main.js, main.js.map (main) 13.9 kB [entry] [rendered]
> Date: 2020-06-02T16:04:30.864Z - Hash: 29489b1cefc0d6b5a125 - Time: 2342ms
> 
> ERROR in node_modules/single-spa-angular/src/extra-providers.d.ts:2:10 - error TS2305: Module '"../../@angular/common/common"' has no exported member 'ɵBrowserPlatformLocation'.
> 
> 2 import { ɵBrowserPlatformLocation, LocationChangeEvent } from '@angular/common';
>            ~~~~~~~~~~~~~~~~~~~~~~~~
> 
> ** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
> ℹ ｢wdm｣: Failed to compile.
> ```

_Originally posted by @filoxo in https://github.com/single-spa/single-spa-angular/issues/208#issuecomment-637651944_

Hi, I am getting the same error from running the single-spa-angular 3.5.3 with the Angular 9 application. 

It appears that `ɵBrowserPlatformLocation` has been deprecated from '@angular/platform-browser' but the code from 3.5.3 release is still importing from that old package instead of '@angular/common'.

`
import { ɵBrowserPlatformLocation } from '@angular/platform-browser';`

Does it mean that for Angular 9 apps when we add the schematics should we use the single-spa-angular 4 instead?

**Comment by filoxo** [comment]
Yes, single-spa-angular@4 is intended to support Angular 9. You should use version 4 instead. 

For more info, read:
- [v4.0.0 release notes](https://github.com/single-spa/single-spa-angular/releases/tag/v4.0.0)
- [v4.2.0 release notes](https://github.com/single-spa/single-spa-angular/releases/tag/v4.2.0) which is the latest 4.x release at the time of this writing. 

I'm closing this since it is not a bug within single-spa-angular but feel free to reopen if I am mistaken.
