### ISSUE TITLE
getSingleSpaExtraProviders() not working with angular 8,spa3 and single-spa angular-3

### ISSUE THREAD

**Issue by rajanvisakh** [single-spa/single-spa-angular#242]
https://github.com/single-spa/single-spa-angular/blob/301906db79b369dd681bdfff86619c9bea83e9f8/schematics/ng-add/_files/src/main.single-spa.ts.template#L22
![ll](https://user-images.githubusercontent.com/68216146/87274294-094a8180-c4f9-11ea-8188-df7baac3f735.png)

**Comment by rajanvisakh** [comment]
im not able to acces the custom props value inside my angular component.Is this due to this?

**Comment by joeldenning** [comment]
> im not able to acces the custom props value inside my angular component.Is this due to this?

No, the extra single-spa providers are related to fixing navigation issues. Not related to props. You should be able to access props through the `singleSpaPropsSubject`. See https://single-spa.js.org/docs/ecosystem-angular#custom-props for more documentation on this.
