### ISSUE TITLE
Data path "" should NOT have additional properties(customWebpackConfig)

### ISSUE THREAD

**Issue by pravinparab** [single-spa/single-spa-angular#244]
while running single spa application, I am facing below issue

**Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(customWebpackConfig).**

**Comment by joeldenning** [comment]
Hi @pravinparab, could you provide more information about this error? What version of Angular are you using? What commands did you run locally? What version of single-spa-angular are you using?

**Comment by arturovt** [comment]
This error is thrown when you use the default Angular builder. You've got to use `@angular-builders/custom-webpack`.

**Comment by pravinparab** [comment]
Hi @joeldenning ,

Issue has been resolved, Thanks :)
