### ISSUE TITLE
`ng add single-spa-angular@4` fails on fresh angular@10 project

### ISSUE THREAD

**Issue by Den-dp** [single-spa/single-spa-angular#249]
### Demonstration
```
> npm i -g @angular/cli@10.0.3
> ng new ngcli1003
> cd .\ngcli1003\
```
```
> ng add single-spa-angular@4
Package has unmet peer dependencies. Adding the package may not succeed.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
? Does your application use Angular routing? Yes
? Does your application use BrowserAnimationsModule? Yes
    Added 'single-spa' as a dependency
    Added 'single-spa-angular' as a dependency
    Added '@angular-builders/custom-webpack' as a dependency
    Generated 'main.single-spa.ts
    Generated 'single-spa-props.ts
    Generated asset-url.ts
    Generated extra-webpack.config.js
    Using @angular-devkit/custom-webpack builder.
Unexpected token / in JSON at position 0
```

### Expected Behavior
`ng add single-spa-angular@4` should work for fresh project generated via @angular/cli@10

### Actual Behavior
`ng add single-spa-angular@4` fails with the following error:
```
Unexpected token / in JSON at position 0
```

----

After some debugging, I found that it fails while parsing the tsconfig
https://github.com/single-spa/single-spa-angular/blob/cc96477d0f526a61c6603a535a0d4b07741a416c/schematics/ng-add/index.ts#L159-L167
just because all tsconfig's in @angular@10 project contains `/* comments */`.
```
> cat .\tsconfig.app.json
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
```
tsconfig is json5 so comments are a valid thing https://github.com/json5/json5#comments

This is another piece that would be nice to resolve in order to fully support #232

**Comment by Den-dp** [comment]
And the workaround is to remove the comment from `tsconfig.app.json`

**Comment by Den-dp** [comment]
Also found that `ng add` inserts `"@angular-builders/custom-webpack": "^10"` 
https://github.com/single-spa/single-spa-angular/blob/cc96477d0f526a61c6603a535a0d4b07741a416c/schematics/ng-add/dependencies.ts#L40-L49
but there is no `@angular-builders/custom-webpack@10` right now so this part will be a problem for some time.

Tried `^9` but get

```
> spa-angular@0.0.0 build:single-spa:spa-angular C:\dev\playground\single-spa\spa-angular
> ng build spa-angular --prod


chunk {} main.js (main) 4.9 kB [entry] [rendered]
Date: 2020-07-20T23:02:28.274Z - Hash: f00cafcb1a71515b40f9 - Time: 4766ms

ERROR in Cannot read property 'flags' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spa-angular@0.0.0 build:single-spa:spa-angular: `ng build spa-angular --prod`
npm ERR! Exit status 1
```

Works with the latest beta `10.0.0-beta.1` tho.

**Comment by joeldenning** [comment]
Hi there - Angular 10 support hasn't landed yet, although it seems like you have made considerable progress here in diagnosing the issue! See related https://github.com/single-spa/single-spa-angular/issues/232 where other Angular 10 issues have been discussed.

Are you open to sending in a pull request that fixes this?

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/single-spa-angular/releases/tag/v4.3.2
