### ISSUE TITLE
ERROR in Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by pravinparab** [single-spa/single-spa-angular#259]
Hi,

While running single spa application i am getting below issue 

C:\New folder>npm run serve:single-spa:designer-app

> designer-ui@1.0.0 serve:single-spa:designer-app C:\New folder
> ng s --project designer-app --disable-host-check --port 4200 --deploy-url http://localhost:4200/ --live-reload false

WARNING: Running a server with --disable-host-check is a security risk. See https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a for more information.
WARNING: --deploy-url and/or --base-href contain unsupported values for ng serve. Default serve path of '/' used. Use --serve-path to override.

chunk {main} main.js, main.js.map (main) 1.58 MB [entry] [rendered]
Date: 2020-08-05T12:46:10.182Z - Hash: 45af8abc22315632a826 - Time: 3481ms

ERROR in Cannot read property 'flags' of undefined
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

**Comment by pravinparab** [comment]
Hi joeldenning,

**Actually when i am running application without converting into single spa its working fine

so when i ran --> ng serve
that time module is converting as below**
Compiling @angular/core : es2015 as esm2015
Compiling @angular/cdk/keycodes : es2015 as esm2015
Compiling primeng/dom : es2015 as esm2015

**& when i convert application in single spa
that time module converting below** 
Compiling @angular/animations/browser : module as esm5
Compiling @angular/animations/browser/testing : module as esm5
Compiling @angular/animations : module as esm5
Compiling @angular/core : module as esm5
Compiling @angular/cdk/collections : module as esm5

**Why i am getting different module conversion ?

Please check below angular version & cli version**

Angular CLI: 9.1.12
Node: 13.12.0
OS: win32 x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.5
@angular-devkit/build-angular     0.1000.5
@angular-devkit/build-optimizer   0.1000.5
@angular-devkit/build-webpack     0.1000.5
@angular-devkit/core              10.0.5
@angular-devkit/schematics        9.1.12
@angular/cdk                      9.2.4
@ngtools/webpack                  10.0.5
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.6.2
typescript                        3.8.3
webpack                           4.43.0

**Comment by joeldenning** [comment]
Thanks for the details - I don't plan on looking into this further but if anyone else has time to do so that would be appreciated.

**Comment by pravinparab** [comment]
Hi joeldenning,

Thanks :)
Issue has been resolved.
Actually issue with typescript version that is present in @angular-builder so i upgrade @angular/builder to 10.0.0
