### ISSUE TITLE
BrowserPlatformLocation not found ( Angular 10 )

### ISSUE THREAD

**Issue by thehunckerma** [single-spa/single-spa-angular#261]
Hello, I really appreciate the time and effort you put into this library.
I'm trying to use your library with an existing angular 10 app and i get the following errors:

![image](https://user-images.githubusercontent.com/59918011/90432363-52768e00-e0c2-11ea-847a-973f4b7e987d.png)

![image](https://user-images.githubusercontent.com/59918011/90434056-bac66f00-e0c4-11ea-8fff-ec025bd6398b.png)

I fixed them by changing the line 3 in extra-providers.d.ts:
![image](https://user-images.githubusercontent.com/59918011/90432430-6de19900-e0c2-11ea-8ddd-a02efbcc3fe4.png)
to this:
![image](https://user-images.githubusercontent.com/59918011/90432493-82be2c80-e0c2-11ea-8af0-e7554bf990b1.png)

And by changing the line 3 in single-spa-angular.js
![image](https://user-images.githubusercontent.com/59918011/90432616-b7ca7f00-e0c2-11ea-9db8-b1988c103efe.png)
to this:
![image](https://user-images.githubusercontent.com/59918011/90432652-c44ed780-e0c2-11ea-9f19-0ece1b9ebf1f.png)

And it worked.
Can you please update the library to support angular 10

**Comment by joeldenning** [comment]
I don't know what is causing that issue and no longer spend time diagnosing and fixing issues for this repository (was too many hours spent on stuff I don't enjoy). There are a few others who jump in to comment on things who may be able to help here. One thing that might help is providing a repository demonstrating the issue.

**Comment by thehunckerma** [comment]
Steps to reproduce ( with Angular CLI 10.0.5 ):
```ng new app```
```ng add single-spa-angular```
fix a small known issue by adding "main.single-spa.ts" to ```"files": [ ..``` in tsconfig.app.json
```npm run serve:single-spa```
and you get the errors.
Here's a repo 
https://github.com/thehunckerma/single-spa-angular-issue

**Comment by thehunckerma** [comment]
I will close this issue as angular 10 is not going to be supported.
for those who are looking for a solution i switched to Qiankun and it works perfectly.

**Comment by joeldenning** [comment]
> I will close this issue as angular 10 is not going to be supported.

This is untrue - we'd like Angular 10 to be supported. We've had a few PRs improving support for it and hopefully will fully support it over time.

**Comment by thehunckerma** [comment]
ah okey sorry 😅

**Comment by celian-garcia** [comment]
Hello @thehunckerma 

> for those who are looking for a solution i switched to Qiankun and it works perfectly.
By curiosity I had a look at [umijs/qiankun](https://github.com/umijs/qiankun) project . It is an interesting one that aim to industrialize the code of what we call sometimes a "portal" in Microfrontends (the core frontend that routes to the others) but it is using single-spa-angular actually. It is not a "concurrent".

Moreover it seems to be completely dependent on single-spa-angular regarding the compatibility to Angular 10 or not (which is a good architecture choice !)

Sorry for the intervention, I just wanted to clarify.

About your issue I will check your repo but I managed to make it work with Angular 10 in a personal project so I'm sure it's nothing ;)

**Comment by celian-garcia** [comment]
Okay looking at the sinlge-spa-angular code https://github.com/single-spa/single-spa-angular/blob/master/src/src/extra-providers.ts
It makes me think that your are not using the latest version. You should try something like 
``ng add single-spa-angular@4.4.2``

**Comment by thehunckerma** [comment]
@celian-garcia Hello, I know qiankun is based on single spa that s why i wanted to use single spa in the first place but doing exactly what the documentation says didn t make it work
but thank you for the clarifications i will try it in my next project :D

**Comment by arturovt** [comment]
Hey @thehunckerma 

Was your issue resolved? Can this issue be closed?

**Comment by thehunckerma** [comment]
Hello, yeah i guess so thanks :D
