### ISSUE TITLE
Sometimes some micro front end is not loaded properly in single spa framework

### ISSUE THREAD

**Issue by kush1995ptl** [single-spa/single-spa-angular#278]
### In my main index.html file, I had given following kind of `routes.`

`<single-spa-router>
    <div class="main-content">
        <route path="login">
          <application name="login"></application>
        </route>
        <route path="main">
          <application name="banner"></application>
          <application name="footerApp"></application>
        </route>
    </div>
</single-spa-router>`

<pre><code>
Libs:
- @angular/core version: ~9.0.0
- single-spa-angular version: ^4.3.1

When route 'main' is loaded it sometimes rendered only one microfront end either banner or footerApp. Any solution for it ?

**Comment by kush1995ptl** [comment]
Here is the code.

<single-spa-router>
    <div class="main-content">
        <route path="login">
          <application name="login"></application>
        </route>
        <route path="main">
          <application name="banner"></application>
          <application name="footerApp"></application>
        </route>
    </div>
</single-spa-router>

**Comment by kush1995ptl** [comment]
`<single-spa-router>
    <div class="main-content">
        <route path="login">
          <application name="login"></application>
        </route>
        <route path="main">
          <application name="banner"></application>
          <application name="footerApp"></application>
        </route>
    </div>
</single-spa-router>`

**Comment by joeldenning** [comment]
Hi @kush1995ptl, could you provide a demonstration of this issue? Sounds like a potential bug in single-spa-layout

**Comment by kush1995ptl** [comment]
Yes Here I captured a video of it with some code and actual issue.

[https://drive.google.com/file/d/1lqCyC18r4i78CvFrCkXNfkp1N6HbkK2r/view](url)

**Comment by joeldenning** [comment]
Hi @kush1995ptl - thanks for the video. Looks like it might be a bug in single-spa-layout. Could you share the code in a Github repo or zip file? I'll try it out locally and see if I can spot what's wrong

**Comment by kush1995ptl** [comment]
Yes code is available in this repo. 

[https://github.com/kush1995ptl/angularmfwithsinglespa](url)

I have mentioned steps to running the app in readme file of repo. Also the demo video as well as link of it is also attached in the repo.

**Comment by joeldenning** [comment]
Thanks for providing the Github repo. This issue turned out to be related to the component selector for the app-root colliding between the different application. Each single-spa application should have its own unique selector for the app-root.

I have created https://github.com/kush1995ptl/angularmfwithsinglespa/pull/1 which fixes the issue. Documentation for this is at https://single-spa.js.org/docs/ecosystem-angular#multiple-applications

**Comment by filoxo** [comment]
Is it possible/worthwhile to have single-spa throw a warning if the domElement it finds to mount an application to is not empty? (this is sort of a spitball idea)

**Comment by joeldenning** [comment]
Yeah that's a good idea.
