### ISSUE TITLE
how can use ngx-formly in single-spa application

### ISSUE THREAD

**Issue by Fox-Valentin** [single-spa/single-spa-angular#286]
### Question
I use formly as dynamic form tool in my project.Here is my project profile:
### Environment
angular:~8.2.13
"primeng": "^10.0.2"  // UI
"single-spa-angular": "^3.6.0",
"@ngx-formly/core": "^5.0.0",
### Detail
When i navigate to the route "app1", the systemJS in root-config-html fetched the http://localhost:4201/main,js, and the main.js is download as static resource, but the selector `<application name="app1">` didnt render on the browser, and the console didnt print any message, i wandering how to fix this. THANKS!!!

**Comment by joeldenning** [comment]
Hi @Fox-Valentin, where is `<application name="app1">` coming from? Is it part of a single-spa-layout Layout Definition? Or part of an angular template?

**Comment by Fox-Valentin** [comment]
> Hi @Fox-Valentin, where is `<application name="app1">` coming from? Is it part of a single-spa-layout Layout Definition? Or part of an angular template?

Hi @joeldenning `<application name="app1">` is on the root-config-html,the hole tag like this     
```
<template id="single-spa-layout">
      <single-spa-router>
        <div class="main-content">
          <route path="app1">
            <application name="app1"></application>
          </route>
          <route path="app2">
            <application name="app2"></application>
          </route>
        </div>
      </single-spa-router>
    </template>
```
the app2 is normal angular app and randering correctly,but app1 with using ngx-formly didnt rendering,and the code in the app component oninit function didnt run.Thanks for replaying!

**Comment by Fox-Valentin** [comment]
Hi @joeldenning ,i am sorry for bathering you or wasting time,i use the singleSpa.addErrorHandler to print the err message, and i found the err is about `Uncaught ReferenceError: __importDefault is not defined`; i mean that my issue is not refference with the single-spa

**Comment by joeldenning** [comment]
Glad to hear you figured out what was the problem.
