### ISSUE TITLE
IE11 Broken in 4.4.1+

### ISSUE THREAD

**Issue by stuartcargill** [single-spa/single-spa-angular#312]
Hey guys, I'm working on an Angular app that has recently been converted into an MFE using single-spa.  The app was running single-spa-angular 4.2.0 but I was getting the infinite loop redirect issue so upgraded to 4.6.0 and it fixed the issue.

However IE11 no longer works, I see you removed support for ES5 from 4.4.1 onward:

https://unpkg.com/browse/single-spa-angular@4.3.2/package.json - outputs ES5
https://unpkg.com/browse/single-spa-angular@4.4.1/package.json 

### Demonstration
Build an Angular ES5 app running as an MFE in any version from 4.4.1 onward.   

### Expected Behavior
App should load in IE11

### Actual Behavior
[https://img.imageupload.net/2020/11/26/IE11.png](https://img.imageupload.net/2020/11/26/IE11.png)
IE11 cannot parse the vendor file as it has ES2015 syntax within it.

I'm not sure if this is a bug or an expected change but I didnt see it mentioned in any release notes.  I've only tried IE11 but I guess this would impact other legacy browsers.

I noticed that single-spa-angular uses ng-packagr for building and it looks like it only supports FESM2015 and UMD formats.

Thoughts/suggestions on this? Any ideas on a workaround?

**Update**
I saw a [post](https://github.com/single-spa/single-spa-angular/issues/56) from @jlwerenskjold where he patched single-spa-angular. I followed a similar idea by using babel to transpile the code to ES5 then using patch-package and it is now working in IE11.  Not an ideal solution so any input or other ideas would be appreciated :)

**Comment by joeldenning** [comment]
@arturovt is there a way we can tell ng-packagr/typescript to compile to es5? Or output both es2015 and es5 builds?

**Comment by arturovt** [comment]
@stuartcargill the thing is that Angular officially dropped generation of ES5:

> :warning: BREAKING CHANGES
esm5 and fesm5 formats are no longer generated.
If you are not using Angular CLI to build your application or library, and you need to be able to build es5 artifacts, then you will need to downlevel the distributed Angular code to es5 on your own.
Angular CLI will automatically downlevel the code to es5.

**Comment by stuartcargill** [comment]
Thanks @joeldenning  & @arturovt for the quick replies.  Ill try your suggestion and see how that plays out.  Eventually, I would like to output my angular build in ES2015 and leverage differential loading out of the box but do you know if that is possible using SystemJS?

**Comment by arturovt** [comment]
Closing this as "not an issue", since it's actually not an issue and is related to Angular's `.browserslistrc` configuration. Feel free to reopen if I'm missing something.

**Comment by joeldenning** [comment]
> Eventually, I would like to output my angular build in ES2015 and leverage differential loading out of the box but do you know if that is possible using SystemJS?

This is possible by changing which import map is used in IE11 versus in other browsers. That can be done by having a dynamic server that checks user agent headers, or by having browser javascript dynamically inject the import map. It's also possible by creating a custom systemjs extra that uses the [systemjs resolve hook](https://github.com/systemjs/systemjs/blob/master/docs/hooks.md#resolveid-parenturl---string) to overwrite url resolution based on current browser.
