### ISSUE TITLE
Zone-less app error without zone.js

### ISSUE THREAD

**Issue by daniloesk** [single-spa/single-spa-angular#313]
### Demonstration
1. Build root-config (no included zone.js)
2. Build Angular 10 app
3. Make app zone-less
4. Register app on root-config
5. Serve them both
6. Access app route

Minimal demo: https://github.com/daniloesk/single-spa-errors/releases/tag/single-spa-angular%23313

### Expected Behavior
Runs without including zone.js on root-config.
One would expect that one of the benefits of running only Zone-less applications would not needing to import zone.js at all.

### Actual Behavior
Error:
```
Uncaught ReferenceError: application 'angular10-routing' died in status SKIP_BECAUSE_BROKEN: Zone is not defined
    at SingleSpaPlatformLocation.onPopState (single-spa-angular.js:61)
    at PathLocationStrategy.onPopState (common.js:383)
    at new Location (common.js:561)
    at Object.Location_Factory [as factory] (common.js:695)
    at R3Injector.hydrate (core.js:11300)
    at R3Injector.get (core.js:11121)
    at injectInjectorOnly (core.js:899)
    at ɵɵinject (core.js:903)
    at injectArgs (core.js:1001)
    at Object.factory (core.js:11389)
```

### Extra
It looks like SingleSpaPlatformLocation.onPopState does not check if Zone is noop, unlike other methods.

### Workaround
Import zone.js in root-config as instructed for Angular apps.

**Comment by daniloesk** [comment]
Forgot to mention that this only happens with Angular app with routing. When not using routing I found no error on zone-less app and no root zone.js.

**Comment by arturovt** [comment]
It's not an issue since you shouldn't call `getSingleSpaExtraProviders()` when using zone-less app, examples in documentation explicitly don't contain the `getSingleSpaExtraProviders` function call:
![image](https://user-images.githubusercontent.com/7337691/100393964-2022e800-3044-11eb-8409-462c5aec4cba.png)

**Comment by daniloesk** [comment]
Wow, missed that. I've read that line many times but missed that. Thanks. I'll teste ASAP.

**Comment by arturovt** [comment]
Closing as "not an issue" ;) Feel free to re-open if I'm missing anything.

**Comment by daniloesk** [comment]
Confirmed it works if I follow the instructions on the big yellow box. =P
Thanks and sorry about that.
