### ISSUE TITLE
singleSpaPropsSubject with ubuntu - not working

### ISSUE THREAD

**Issue by psoltesz** [single-spa/single-spa-angular#314]
Hi,

I'm using Docker for building my project, and discovered that when using Ubuntu images (tested with multiple versions), singleSpaPropsSubject will never emit any values, so subscriptions inside the app will never actually receive the props which are provided to children apps during mounting.

```
const lifecycles = singleSpaAngular({
  bootstrapFunction(singleSpaProps: SingleSpaProps) {
    singleSpaPropsSubject.next(singleSpaProps);
    console.log('singlespaprops.next called: ' + JSON.stringify(singleSpaProps.props)); // 'props' is my own custom property
    return platformBrowserDynamic(getSingleSpaExtraProviders()).bootstrapModule(AppModule);
  },
  template: '<child-app-root />',
  Router,
  NavigationStart,
  NgZone,
});
```

The value itself gets through from the parent app, so the console log displays the correct value, but subscriptions inside the child app will not be triggered.

```
export class RolesComponent implements OnInit {
  roles: any[];

  ngOnInit(): void {
      singleSpaPropsSubject.pipe(filter(v => !!v)).subscribe((value) => {
        console.log('props: ' + value); // this never happens
      });
  }
}
```

In Windows (both with 'ng serve' and by mapping the result of 'ng build --prod'), everything works.
I tested the different results by deploying the parent app and using [import-map-overrides](https://www.npmjs.com/package/import-map-overrides) to map the child app to the parent.
I also have strange warning messages for almost every .ts file when building in Ubuntu which are not present in Windows, like the following:

WARNING in D:\ubuntu-project\src\main.single-spa.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

It's almost as if the result of the exactly same code after building is somehow different.
I went on to publish the artifacts built with both Windows and Ubuntu images on Azure, and after downloading them, I compared the two main.js files with notepad++, and while the nuber of rows is identical, there is a number of differences (like the Angular Material module being present in a different place in one file than the other one).

**Comment by arturovt** [comment]
Could you provide a minimal reproducible example?

I don't think it's somehow related to `single-spa-angular` package itself and that this package somehow affects the `Subject` that's located inside your code.

**Comment by psoltesz** [comment]
Sure, here it is: [https://github.com/psoltesz/single-spa-angular-singleSpaPropsSubject-debug](https://github.com/psoltesz/single-spa-angular-singleSpaPropsSubject-debug)

Just start the shell with 'ng serve' and child-app with 'npm run serve:single-spa:child-app'.

**Comment by arturovt** [comment]
You've got invalid path inside your `angular.json`:

![image](https://user-images.githubusercontent.com/7337691/101172162-7ba73400-3649-11eb-93f5-64d4f1d51a94.png)

**Comment by psoltesz** [comment]
That did it, thanks! I didn't even think of checking that. However, I would like to point out that this was autogenerated. Just to be sure, I tested 'ng add single-spa-angular' on both Windows and Ubuntu (don't have a Mac), screenshots below. So it looks like the path generation is OS-specific, and the issue was that I'm developing on Windows and using a pipeline which has an Ubuntu-based Docker image. Maybe it would make sense to have '/' for Windows as well?

![linux-1](https://user-images.githubusercontent.com/22658433/101337501-0a02fc00-387c-11eb-911a-0b093701dc4a.png)
![linux-2](https://user-images.githubusercontent.com/22658433/101337492-08d1cf00-387c-11eb-8ee5-63b738a98b9b.png)
![windows-1](https://user-images.githubusercontent.com/22658433/101337498-096a6580-387c-11eb-8a81-a02f26d0b27c.png)
![windows-2](https://user-images.githubusercontent.com/22658433/101337500-096a6580-387c-11eb-9ebb-591180350e40.png)

**Comment by joeldenning** [comment]
Released in https://github.com/single-spa/single-spa-angular/releases/tag/v4.9.1

**Comment by psoltesz** [comment]
Thank you!
