### ISSUE TITLE
Angular 11 application unmount

### ISSUE THREAD

**Issue by VictorMontenegro** [single-spa/single-spa-angular#316]
I am having a problem with an Angular 11 application using single-spa-angular. The problem appears when I try to leave from the App working with Angular 11 to other application (in this case, working with Angular 8), where the App working with Angular 11 does not appear to do the unmount procedure, and both Apps are mounted at the same time.

Here is a video with the example:

https://im7.ezgif.com/tmp/ezgif-7-40b47f3dedd4.gif

If there is more required information (package.json from both apps, etc.) ask for it.

Thanks for the help!

**Comment by joeldenning** [comment]
Hi @VictorMontenegro, the gif link you shared isn't working for me. Could you provide a Github repository that demonstrates the issue?

**Comment by VictorMontenegro** [comment]
Hello @joeldenning , sorry for the wait, here is the repository with the issue:

https://github.com/VictorMontenegro/Angular11SingleSpaError

1.- Make "npm install" at the root folder, inside microfrontends, microfrontends_angular_11 and shell folders.

2.- Execute on the terminal "npm start" in the root folder of the project.

3.- In the browser, access to "http://localhost:9000/".

You can navigate from App1 to App2 without any problem. The problem appears when I navigate to the Angular 11 App and I try to go back to other applications (app1 or app2, working with Angular 8), where the Angular 11 App does not appear to do the unmount procedure, and both App1 or App2 and Angular 11 App are mounted at the same time.

**Comment by joeldenning** [comment]
@arturovt do you have time to look at this one?

**Comment by arturovt** [comment]
@VictorMontenegro 

Hey, your example doesn't work.

1) The `npm run start` just killed my PC :confused: 

![image](https://user-images.githubusercontent.com/7337691/101892118-a8a89900-3bab-11eb-874b-40e062ac896a.png)

2) This is what I got when I opened `localhost:9000`:

![image](https://user-images.githubusercontent.com/7337691/101892218-caa21b80-3bab-11eb-8076-59d29ec8cb69.png)

**Comment by VictorMontenegro** [comment]
Sorry, can you try this?:

1.- Install differents application. Execute npm install in folders:
     1.- microfrontends/
     2.- microfrontends_angular_11/
     3.- shell/
2.- Serve the different applications. Execute npm startin folders:
     1.- microfrontends/
     2.- microfrontends_angular_11/
     3.- shell/
3.- Browse to http://localhost:9000/

Also, I uploaded a video to show the example with the error:

https://youtu.be/54Mo95zHX2E

**Comment by mattsmith-finocomp** [comment]
I have what sounds like a similar issue. I have an application which has two React applications and and one Angular 11 application. Navigating away from the Angular application keeps the application mounted and throws this error in the console:

![image](https://user-images.githubusercontent.com/67079762/102960847-fa034180-4536-11eb-97bf-07412d15a232.png)

I should also note that I am using module federation as an alternative to SystemJS.

Here is a repo that demonstrates the problem if it helps - https://github.com/mdsmith00/single-spa-module-federation-react-and-angular

**Comment by mdsmith00** [comment]
I have what sounds like a similar issue. I have an application which has two React applications and and one Angular 11 application. Navigating away from the Angular application keeps the application mounted and throws this error in the console:

![image](https://user-images.githubusercontent.com/2611203/102961249-ec9a8700-4537-11eb-8590-52f860978828.png)

I should also note that I am using module federation as an alternative to SystemJS.

Here is a repo that demonstrates the problem if it helps - https://github.com/mdsmith00/single-spa-module-federation-react-and-angular.

It seems related to this issue which was previously resolved https://github.com/single-spa/single-spa-angular/issues/48

**Comment by mattsmith-finocomp** [comment]
> I have what sounds like a similar issue. I have an application which has two React applications and and one Angular 11 application. Navigating away from the Angular application keeps the application mounted and throws this error in the console:
> 
> ![image](https://user-images.githubusercontent.com/2611203/102961249-ec9a8700-4537-11eb-8590-52f860978828.png)
> 
> I should also note that I am using module federation as an alternative to SystemJS.
> 
> Here is a repo that demonstrates the problem if it helps - https://github.com/mdsmith00/single-spa-module-federation-react-and-angular.
> 
> It seems symptomatically related to this issue which was previously resolved #48

I was at least able to solve my issue by importing the `BrowserAnimationsModule` within my `app.module.ts` - https://github.com/mdsmith00/single-spa-module-federation-react-and-angular/commit/c618be67c4651ccd985db4cbb7cebfd19f5004b4

**Comment by DmitryBrus** [comment]
> I was at least able to solve my issue by importing the `BrowserAnimationsModule` within my `app.module.ts` - [mdsmith00/single-spa-module-federation-react-and-angular@c618be6](https://github.com/mdsmith00/single-spa-module-federation-react-and-angular/commit/c618be67c4651ccd985db4cbb7cebfd19f5004b4)

Same here, adding into `BrowserAnimationsModule` within my `app.module.ts`  **resolved the issue**
I've two apps: angular 10 and 11 with systemjs loader.
