### ISSUE TITLE
How to share dependency with `angular-cli`  to `single-spa-angular` parcel? 

### ISSUE THREAD

**Issue by 3gwebtrain** [single-spa/single-spa-angular#322]
I am using `angular-cli` with `single-spa` ( not single-spa-angualr) to load the `single-spa-angular` bundles. now I start to share the dependencies from `angular-cli` to `single-spa-parcels` but getting error. there is a way to do this (https://github.com/polyglot-microfrontends/shared-dependencies ) using common 'root-html` file.

But my case I could not use that. because `authentications` and other angular dependency added with my current `angular\cli` app.

To get the `shared-dependency` from my `angular-app` I am declaring the following with my `child1` apps `extra-webpack.config` file as follows:

```
const singleSpaAngularWebpack = require("single-spa-angular/lib/webpack")
  .default;

module.exports = (angularWebpackConfig, options) => {
  const singleSpaWebpackConfig = singleSpaAngularWebpack(
    angularWebpackConfig,
    options
  );

  singleSpaWebpackConfig.externals = [
    /^rxjs$/,
    /^rxjs\/operators$/,

    /^zone\.js$/,
    /^@angular\/router$/,
    /^@angular\/compiler$/,
    /^@angular\/common$/,
    /^@angualr\/core$/,
    /^@angular\/platform-browser$/,
  ];
  // Feel free to modify this webpack config however you'd like to
  return singleSpaWebpackConfig;
};

```
it works. it's expects the `dependency from outside` But I unable to provide them from `index.html` ( my case angualr/cli index.html) in the index.html I importing all required script through cdn. all or impots.

But my child1 app not able to pick up / snyc with loaded script in `index.html`. I do not have any idea to add push the `externals` from angular app to `child1` app. how to handle this? here is my `index.html` file in `host` .

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Container</title>
    <base href="/" />
    <meta name="importmap-type" content="systemjs-importmap" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/x-icon" href="favicon.ico" />

    <script type="systemjs-importmap" src="/assets/import-map.json"></script>
    <script src="https://npmcdn.com/systemjs@0.19.27/dist/system.src.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/zone.js@0.9.1/dist/zone.min.js"></script>
    <script src="https://unpkg.com/import-map-overrides@1.5.0/dist/import-map-overrides.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/3.1.6/system.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/3.1.6/extras/amd.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/3.1.6/extras/named-exports.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/3.1.6/extras/named-register.min.js"></script>

    <script type="systemjs-importmap">
      {
        "imports": {
          "single-spa": "https://cdn.jsdelivr.net/npm/single-spa@5.8.2/lib/umd/single-spa.min.js",
          "@angular/core": "https://cdn.jsdelivr.net/npm/@angular/core@8.2.0/bundles/core.umd.min.js",
          "@angular/common": "https://cdn.jsdelivr.net/npm/@angular/common@8.2.0/bundles/common.umd.min.js",
          "@angular/compiler": "https://cdn.jsdelivr.net/npm/@angular/compiler@8.2.0/bundles/compiler.umd.min.js",
          "@angular/platform-browser": "https://cdn.jsdelivr.net/npm/@angular/platform-browser@8.2.1/bundles/platform-browser.umd.min.js",
          "@angular/router": "https://cdn.jsdelivr.net/npm/@angular/router@8.2.0/bundles/router.umd.min.js",
          "rxjs": "https://cdn.jsdelivr.net/npm/rxjs@6.4.0/bundles/rxjs.umd.min.js",
          "rxjs/operators": "https://cdn.jsdelivr.net/npm/@esm-bundle/rxjs@6.6.3/system/es5/rxjs-operators.min.js"
        }
      }
    </script>
  </head>
  <body>
    <app-root></app-root>
    <!-- <import-map-overrides-full></import-map-overrides-full> -->
  </body>
</html>
```

If I remove  **singleSpaWebpackConfig.externals** from child1 app, all works fine. But dependency not shared. But I am looking a solution for sharing dependency between `angular/cli` app with `single-spa-angular`.

Here is the [repo](https://github.com/3gwebtrain/single-spa-shared-dependency.git) for detailed issue findings.

Thanks in advance.

**Comment by 3gwebtrain** [comment]
at present I am getting this error:

```
Uncaught TypeError: Cannot read property 'share' of undefined
    at new ApplicationRef (core.js:40966)
    at _createClass (core.js:30472)
    at _createProviderInstance (core.js:30426)
    at initNgModule (core.js:30332)
    at new NgModuleRef_ (core.js:31561)
    at createNgModuleRef (core.js:31544)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:44911)
    at NgModuleFactory_.create (core.js:46088)
    at core.js:40535
    at e.invoke (zone.min.js:1)
```

**Comment by joeldenning** [comment]
If you're using Ivy Compiler, you can only share the angular core libs by creating your own custom builds of the angular core libraries, by making each a webpack entry and running angular compiler on them.

**Comment by 3gwebtrain** [comment]
thanks joel. do you have any sample work or detailed description about it? if so let me try and post the status here. may be I require your support to complete this task.

**Comment by joeldenning** [comment]
> do you have any sample work or detailed description about it?

No I haven't had time to put together an example. However, you can see some community members working on it at https://github.com/single-spa/single-spa-angular/issues/303

> will this help for us: https://www.npmjs.com/package/@angular-architects/module-federation -?

You can use module federation if you'd like - it requires not using Angular CLI since it requires webpack 5. See https://single-spa.js.org/docs/recommended-setup#sharing-with-module-federation for some details.

**Comment by arturovt** [comment]
Closing the issue since it was implemented, see this guide: https://single-spa.js.org/docs/ecosystem-angular/#shared-angular.
