### ISSUE TITLE
Angular Modal Parcel Example

### ISSUE THREAD

**Issue by troissant** [single-spa/single-spa-angular#337]
Hi Everyone, 

I'm developing a large scale application using MFE's at my job and we've encountered a little problem with 2 of our micro fronts.

1- Menu Micro Front
2- Info Micro Front

The problem is: 

At the Menu Micro Front we have a Angular Material Card  (Mat-Card) who has an icon on it, the expected behaviour is when the user clicks on it, it should call the Angular Material Dialog (Mat-Dialog) from the Info Micro Front, they're in separate git repos tho, we're not using mono repos (don't know if it is a problem to use with Parcels, since with my research, i only found examples with mono repos).

First, i tried to open the modal via Pathing (RouterAcvitated) but since they're separate fronts it didn't work, so i found Parcels.

I searched online after reading the article (https://single-spa.js.org/docs/parcels-overview/) for Modals examples, but got nothing, also saw this one (https://github.com/single-spa/single-spa-angular/tree/master/apps/parcel) so i'm gently asking...

Can anyone help me with a simple Modal example ? I only found examples with entire applications.

P.S. I'm not that PRO with Micro Fronts and Single-Spa (i guess these 2 links could help me, but i tried and got nothing).

Thank you!!

Angular Version - 9.2

**Comment by filoxo** [comment]
We provide a very basic Angular Parcel here: https://single-spa.js.org/docs/ecosystem-angular/#parcels
It's not as specific as you're asking but we can't provide custom solutions or cover every single use case.

**Comment by joeldenning** [comment]
Also here's another parcel example: https://github.com/single-spa/single-spa-angular/tree/master/apps/parcel.

Agreed with @filoxo - we can't create an example for every situation.
