### ISSUE TITLE
Passing custom props from Angular application to React parcel

### ISSUE THREAD

**Issue by bullypb23** [single-spa/single-spa-angular#338]
Hi,

How can I pass random props from angular application to react parcel application inside?

![image](https://user-images.githubusercontent.com/55666396/107368781-46074700-6ae1-11eb-9202-f2421c27b68a.png)

![image](https://user-images.githubusercontent.com/55666396/107368875-5ddecb00-6ae1-11eb-8386-4a4f8dbaef99.png)

**Comment by joeldenning** [comment]
The `customProps` binding is the way to pass custom props to parcels. See https://github.com/single-spa/single-spa-angular/blob/f64a5bd07d83de3d1c962c9736460fe4dede9fd4/libs/single-spa-angular/parcel/src/parcel.component.ts#L28, https://github.com/single-spa/single-spa-angular/blob/f64a5bd07d83de3d1c962c9736460fe4dede9fd4/libs/single-spa-angular/parcel/src/parcel.component.ts#L43, and https://github.com/single-spa/single-spa-angular/blob/f64a5bd07d83de3d1c962c9736460fe4dede9fd4/libs/single-spa-angular/parcel/src/parcel.component.ts#L65

The `random` binding is not accepted by the `<parcel />` component - all extra props should be in the `customProps` object.

**Comment by bullypb23** [comment]
Hi,

Still can't access `customProps` in react parcel app. I deleted random value from the picture above. My react parcel app looks like this:

Root.component.js
![image](https://user-images.githubusercontent.com/55666396/107483786-d6956400-6b81-11eb-9f5c-2d1fab321403.png)

react-test.js
![image](https://user-images.githubusercontent.com/55666396/107483838-e7de7080-6b81-11eb-8e2d-1527b66c8fa8.png)

**Comment by joeldenning** [comment]
I've created https://github.com/single-spa/single-spa-angular/pull/339 which demonstrates that props are passed successfully.

![image](https://user-images.githubusercontent.com/5524384/107816380-e81d6e00-6d31-11eb-9c68-78ccd0b6b096.png)

**Comment by joeldenning** [comment]
Closing this since #339 demonstrates that custom props are working.

**Comment by bullypb23** [comment]
Thank you @joeldenning for your response. I was able to solve this. The problem was that I named the props that I wanted to pass to parcel component name and that props name is already taken and when I changed the name of the props it worked. :D
