### ISSUE TITLE
 ERROR in getInternalNameOfClass() called on a non-ES5 class: expected SingleSpaPlatformLocation to have an inner class declaration

### ISSUE THREAD

**Issue by diangongdianzi** [single-spa/single-spa-angular#340]
### Demonstration
The preceding error is reported when target is set to es5 in the tsconfig.json file.

**Comment by joeldenning** [comment]
Please provide a repository that demonstrates the issue.

**Comment by engg-aruny** [comment]
Is this issue resolved. I have same problem on installing "single-spa-angular": "4.9.2" to existing project.
Compiling single-spa-angular/parcel : module as esm5
Warning: Invalid constructor parameter decorator in C:/xx/xx/xx/multiple-microfrontends/xx/node_modules/single-spa-angular/fesm2015/single-spa-angular-parcel.js:
 () => [
    { type: ElementRef }
]
