### ISSUE TITLE
Broken default app

### ISSUE THREAD

**Issue by Booster2ooo** [single-spa/single-spa-angular#341]
### Demonstration

Create a new angular app with `npx create-single-spa --moduleType app-parcel`.
- Directory for new project **.**
- Which framework do you want to use? **angular**
- Project name (can use letters, numbers, dash or underscore) **sample**
- Do you want to enforce stricter type checking and stricter bundle budgets in the workspace? **Yes**
- Would you like to add Angular routing? **Yes**
- Which stylesheet format would you like to use? **SCSS**
- Does your application use Angular routing? **Yes**
- Does your application use BrowserAnimationsModule? **No**

Run `npm install` in the created directory (even if I specified the directory should be `.`)
Run `npm run serve:single-spa:app-exams`

### Env
```
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 11.1.4
Node: 10.23.1
OS: win32 x64

Angular: 11.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.4
@angular-devkit/build-angular   0.1101.4
@angular-devkit/core            11.1.4
@angular-devkit/schematics      11.1.4
@angular/cli                    11.1.4
@schematics/angular             11.1.4
@schematics/update              0.1101.4
rxjs                            6.6.6
typescript                      4.1.5
```

### Expected Behavior

A working app.

### Actual Behavior

If I visit `http://localhost:4200/` I see a white page (empty app-root) and nothing in the console.

If I visit `http://single-spa-playground.org/playground/instant-test?name=app-exams&url=%2F%2Flocalhost%3A4200%2Fmain.js&framework=angular` I see a white page with the following errors in the console:
```
Uncaught TypeError: Cannot read property 'injector' of null
    at single-spa-angular.js:235
    at Generator.next (<anonymous>)
    at tslib.es6.js:76
    at new ZoneAwarePromise (zone.js:1340)
    at __awaiter (tslib.es6.js:72)
    at unmount (single-spa-angular.js:232)
    at lifecycle.helpers.js:26
    at ZoneDelegate.invoke (zone.js:400)
    at Zone.run (zone.js:160)
    at zone.js:1318
(anonymous) @ single-spa-angular.js:235
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
__awaiter @ tslib.es6.js:72
unmount @ single-spa-angular.js:232
(anonymous) @ lifecycle.helpers.js:26
ZoneDelegate.invoke @ zone.js:400
Zone.run @ zone.js:160
(anonymous) @ zone.js:1318
ZoneDelegate.invokeTask @ zone.js:434
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:620
ZoneTask.invokeTask @ zone.js:520
invokeTask @ zone.js:1656
globalZoneAwareCallback @ zone.js:1682
setTimeout (async)
scheduleTask @ zone.js:3065
ZoneDelegate.scheduleTask @ zone.js:421
Zone.scheduleTask @ zone.js:248
Zone.scheduleMacroTask @ zone.js:271
scheduleMacroTaskWithCurrentZone @ zone.js:716
(anonymous) @ zone.js:3107
proto.<computed> @ zone.js:1015
u @ app-errors.js:11
(anonymous) @ unmount.js:51
ZoneDelegate.invoke @ zone.js:400
Zone.run @ zone.js:160
(anonymous) @ zone.js:1318
ZoneDelegate.invokeTask @ zone.js:434
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:620
ZoneTask.invokeTask @ zone.js:520
invokeTask @ zone.js:1656
globalZoneAwareCallback @ zone.js:1682
load (async)
customScheduleGlobal @ zone.js:1808
ZoneDelegate.scheduleTask @ zone.js:421
Zone.scheduleTask @ zone.js:248
Zone.scheduleEventTask @ zone.js:274
(anonymous) @ zone.js:1965
(anonymous) @ system.js:639
ZoneAwarePromise @ zone.js:1340
systemJSPrototype.instantiate @ system.js:634
systemJSPrototype.instantiate @ system.js:672
systemJSPrototype.instantiate @ system.js:708
systemPrototype.instantiate @ amd.js:85
systemJSPrototype.instantiate @ named-register.js:61
(anonymous) @ system.js:283
ZoneDelegate.invoke @ zone.js:400
Zone.run @ zone.js:160
(anonymous) @ zone.js:1318
ZoneDelegate.invokeTask @ zone.js:434
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:620
Promise.then (async)
scheduleMicroTask @ zone.js:603
ZoneDelegate.scheduleTask @ zone.js:424
Zone.scheduleTask @ zone.js:248
Zone.scheduleMicroTask @ zone.js:268
scheduleResolveOrReject @ zone.js:1308
resolvePromise @ zone.js:1246
(anonymous) @ zone.js:1162
Promise.then (async)
(anonymous) @ zone.js:1514
ZoneAwarePromise @ zone.js:1340
Ctor.then @ zone.js:1513
resolvePromise @ zone.js:1213
ZoneAwarePromise.resolve @ zone.js:1350
systemJSPrototype.import @ system.js:225
systemJSPrototype.import @ system.js:775
rt @ import-app.js:5
(anonymous) @ root.component.js:57
(anonymous) @ load.js:39
ZoneDelegate.invoke @ zone.js:400
Zone.run @ zone.js:160
(anonymous) @ zone.js:1318
ZoneDelegate.invokeTask @ zone.js:434
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:620
Promise.then (async)
scheduleMicroTask @ zone.js:603
ZoneDelegate.scheduleTask @ zone.js:424
Zone.scheduleTask @ zone.js:248
Zone.scheduleMicroTask @ zone.js:268
scheduleResolveOrReject @ zone.js:1308
ZoneAwarePromise.then @ zone.js:1466
(anonymous) @ root.component.js:50
il @ react-dom.production.min.js:211
Su @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
Va @ react-dom.production.min.js:122
xu @ react-dom.production.min.js:257
(anonymous) @ react-dom.production.min.js:256
F @ scheduler.production.min.js:17
x.port1.onmessage @ scheduler.production.min.js:14
```
```
zone.js:209 Uncaught Error: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
    at new PathLocationStrategy (common.js:378)
    at Object.provideLocationStrategy [as useFactory] (router.js:5725)
    at Object.factory (core.js:11442)
    at R3Injector.hydrate (core.js:11353)
    at R3Injector.get (core.js:11174)
    at injectInjectorOnly (core.js:4715)
    at Module.ɵɵinject (core.js:4719)
    at Object.Location_Factory [as factory] (common.js:695)
    at R3Injector.hydrate (core.js:11353)
    at R3Injector.get (core.js:11174)
```

**Comment by arturovt** [comment]
Could you provide a minimal reproducible example?

The error description seems to be obvious, you have to provide `APP_BASE_HREF` value.

**Comment by Booster2ooo** [comment]
> Could you provide a minimal reproducible example?
> 
> The error description seems to be obvious, you have to provide `APP_BASE_HREF` value.

I'll do but as I described, it's just the "out of the box" app, I didn't touch a single line.

**Comment by arturovt** [comment]
I ran your example and as I said the error is obvious. You have to `provide: APP_BASE_HREF`. More information in our guide https://single-spa.js.org/docs/ecosystem-angular/#routing.

![image](https://user-images.githubusercontent.com/7337691/109423600-bc181300-79e8-11eb-9f29-0f851a8546d0.png)

**Comment by Booster2ooo** [comment]
Thank you for clarifying, I mixed up `APP_BASE_HREF` and `BASE_HREF`. In despair, I was trying to provide them both as static providers in `platformBrowserDynamic` but it didn't work, obviously.

As the CLI asks if the user want to rely on Angular routing, maybe it would be nice to add a warning or a clear message about this. I saw `For further routing setup, see https://single-spa.js.org/docs/ecosystem-angular#configure-routes` but it looks like something you'd read once you see the app running and you want to tweak the config, not a mandatory step. Maybe a message between those two choices would be nice:
```
? Does your application use Angular routing? Yes
Warning: An additional manual configuration will be required, see https://single-spa.js.org/docs/ecosystem-angular/#configure-routes
? Does your application use BrowserAnimationsModule? No
```

Anyway, thanks for your help, I should have RTFM.

**Comment by arturovt** [comment]
Umm, that makes sense. @joeldenning what do you think? Should we show that message during setup?

**Comment by arturovt** [comment]
@Booster2ooo could you have a look at this (https://github.com/single-spa/single-spa-angular/pull/343) PR? I'm not a native speaker so it'll be great if someone corrects the message.

**Comment by Booster2ooo** [comment]
I'm not a native speaker neither so I'm not the best suited for this review. I think I would let go with "the" and "therefore an": 

Warning: Since ~~the~~ routing is enabled ~~therefore an~~ additional manual configuration will be required, see https://single-spa.js.org/docs/ecosystem-angular/#configure-routes

But that's a detail, thanks for this new feature :)

**Comment by joeldenning** [comment]
Agreed about the small grammar changes - I've reviewed the PR. Thanks @arturovt for your help with this.
