### ISSUE TITLE
Angular Router and Route Resolvers interaction when using Single-spa

### ISSUE THREAD

**Issue by Jadamae77** [single-spa/single-spa-angular#350]
### Question

How does the Router and Route Resolvers interact with the various apps tied together by single-spa? I have a few resolvers in some of my microfrontends, and I am facing an issue where the user initiates a route but if while the data is resolving they navigate to another view, once the data is received from the server they will be forced back to the first page they tried to access. To fix this, I was trying to listen to the Router events, but they are out of order. 

Primarily, I am seeing events from Navigation Start through Navigation End before the resolver for a route is ever called, but in a a normal environment the resolver would be called after Resolve Start and before Resolve End.

### Environment

<pre><code>
Libs:
- @angular/core version: 11.2.4
- single-spa-angular version: 5.9.2

Others:

</code></pre>

**Comment by joeldenning** [comment]
Each single-spa application is its own angular application, that is bootstrapped separately from all others. It's possible to have a shared instance of angular or to not have a shared instance. However, the applications are independent.

I do not know much about Angular router - generally it has been difficult to get to work with single-spa although my understanding is that it's in a pretty good spot now. So I can't answer your question about NavigationStart and NavigationEnd, because I don't know the answer. @arturovt might know, though.

**Comment by arturovt** [comment]
@Jadamae77 could you provide a minimal reproducible example?

**Comment by Jadamae77** [comment]
It's pretty involved...does this help at all?

The blue line at the top is a navbar in an app titled 'landing app', and everything else is part of an app titled 'manifest app'.


https://user-images.githubusercontent.com/63246953/115065331-00d60b80-9ebc-11eb-8e14-38bd47a24f84.mp4

The operation on the click is 

          this.router.navigate([`app/manifest/${id}`]);

Resolver
          
            {
            path: 'app/manifest/:id',
            component: ManifestDetailComponent,
            resolve: { manifest: ManifestResolver },
            },

```
    resolve(route: ActivatedRouteSnapshot): Observable<Manifest | Error> {
        console.log('MANIFEST RESOLVER CALLED');
        return this.manifestService.getManifest(route.params.id).pipe(map(res => {
                console.log('MANIFEST RESOLVER RESOLVED');
                return res;
        }));

    }
```

App registration in Single spa index html


          System.import("single-spa").then(function (singleSpa) {

          singleSpa.registerApplication(
           "Navbar-App",

          function () {
            return System.import("Navbar-App");
          },

          function (location) {
            return location.pathname.startsWith("/");
          }

          );


        singleSpa.registerApplication(
        "Manifest-App",
          function () {
            return System.import("Manifest-App");
          },
          function (location) {
            if ( location.pathname.startsWith("/app/manifest") ||
            location.pathname.startsWith("/app/appointments") ||
            location.pathname.startsWith("/app/terminal")) {
                return true;
            }else {
                return false;
            }
          }
         );


The console logs are coming from services injected into the app.component of both apps.

```

export class NavigationSpyService {
  constructor(public router: Router) {
    this.watchNavigationChanges();
   }

   watchNavigationChanges(): void {
     this.router.events.subscribe({next: e => {
      if (e instanceof NavigationStart) {
        console.log("MANIFEST APP - Navigation Start", e);
      } else if (e instanceof ActivationStart) {
        console.log("MANIFEST APP - Activation Start", e);
      } else if (e instanceof ResolveStart) {
        console.log("MANIFEST APP - Resolve Start", e);
      } else if (e instanceof ResolveEnd) {
        console.log("MANIFEST APP - Resolve End", e);
      } else if (e instanceof ActivationEnd) {
        console.log("MANIFEST APP - Activation End", e);
      } else if (e instanceof NavigationEnd) {
        console.log("MANIFEST APP - Navigation End", e);
      }
     }});
   }
}
```


I am just trying to understand how single-spa works with the router. I would have thought the events would be fired one after each other. (i.e. MANIFEST APP - navigation start, LANDING APP - navigation start, etc.)
