### ISSUE TITLE
How to allow CORS when mount the micro frontend 

### ISSUE THREAD

**Issue by sylvester-x** [single-spa/single-spa-angular#352]
### Environment

Libs:
- @angular/core version: 10.0.6
- single-spa-angular version: 4.6.0
![image](https://user-images.githubusercontent.com/45072247/115262671-54b84d00-a167-11eb-8960-c6c3ad9a53b5.png)

Environment
-Docker with nginx

**Comment by joeldenning** [comment]
If main.js is hosted by nginx, you should configure nginx to send an appropriate Access-Control-Allow-Origin HTTP response header when serving all the files, including main.js.

CORS is unrelated to single-spa or single-spa-angular, so I'm closing this issue. Here's a resource where you can read more about nginx and cors: https://enable-cors.org/server_nginx.html
