### ISSUE TITLE
browser refresh issue in angular10+single-spa

### ISSUE THREAD

**Issue by anandcgopal** [single-spa/single-spa-angular#354]
I recently used Single-spa with angular 10 and created 4 microapps(header,footer, nav-bar, coreapp). Followed all the steps given in single-spa and performed production build and copied the dist folders of all the microapps in IIS and NGINX servers and the apps are working fine in both the webservers as expected but if I click on the browser refresh, I am getting a blank screen. I noticed that the main.js of the microapp which was appearing in the URL context is getting accessed and it renders a blank screen without any error. 
Please note that this issue is not occurring when I run the app using NodeJS. 

I saw the same issue in the community example https://angular.microfrontends.app/  where the browser refresh throws errors and forces you to manually go back to the root context to bring back the app

Can anyone point out where I am going wrong and let me know how to fix this issue?

**Comment by arturovt** [comment]
Can you provide a minimal reproducible example?

**Comment by marhuero** [comment]
Hi @anandcgopal,
Have you redirect IIS trafic like in this article https://indepth.dev/posts/1239/deploy-an-angular-application-to-iis ? 
If i use the community example IIS look for file or directory in the server  when you refresh url https://angular.microfrontends.app/stats

**Comment by arturovt** [comment]
I’ll close since there’s no reproducible example.
