### ISSUE TITLE
Angular main bundles

### ISSUE THREAD

**Issue by yugakiran** [single-spa/single-spa-angular#356]
I am using single spa angular, when we build the child apps as ng build — prod ,  main-es5.js and main-es2015.js bundles are getting created in dist folder. 

Now we would like to support both modern and old browsers, how to configure import-maps in root app? 
If I just mention es2015 it only works on modern browser and if mention as es5 main module it works only in older browsers. 
`{
"imports":{
"app1":"https://my-app1-dev1.net/main-es2015.js",
"app2":"https://my-app2-dev2.net/main-es2015.js"
}
}`

How to create common main.js to support ES5 and ES6? Can some suggest how create common bundle or how to configure import-maps?

**Comment by ajaykrishnan33** [comment]
@yugakiran The es5 bundle will work with both older and newer browsers right?

I was interested in exploring if it was possible to specify both ES2015 and ES5 module types in the importmap and have SystemJS automatically load the ES5 versions incase the browser doesn't support ES2015.

Technically, this should be acheivable by having 2 importmaps in your index.ejs file  - one with all of your ES2015 imports and another with all of your ES5 imports, and you can then add a script in your index.ejs file to delete one of them after detecting browser support for ES5 (before the SystemJS script has been loaded).

Something like this:

```html
<script data-ecmascript-version="es2015" type="systemjs-importmap">
    {
        "imports": {
            "app1": "//localhost:4200/main-es2015.js",
            "app2":"//localhost:4300/main-es2015.js"
        }
    }
</script>

<script data-ecmascript-version="es5" type="systemjs-importmap">
    {
        "imports": {
            "app1": "//localhost:4200/main-es5.js",
            "app2":"//localhost:4300/main-es5.js"
        }
    }
</script>

<script>
    // detect es5 or es2015 browser support here
    var es2015Supported = false;

    var es2015Scripts = document.querySelectorAll("[data-ecmascript-version=es2015]");

    if (!es2015Supported) {
          es2015Scripts.forEach(function(script){
            script.parentNode.removeChild(script);
          });
    }
</script>

<script src="https://cdn.jsdelivr.net/npm/systemjs@6.8.3/dist/system.min.js"></script>
```

I tried this out and it works for me. However, I am unaware if SystemJS already supports something like this by default in a better way. At least I couldn't find it by looking at their docs.

Note that if you are sharing dependencies, then you will need to also ensure that you are using the correct ES5/ES2015 versions of those dependencies as well, or you might run into issues like this: https://github.com/single-spa/single-spa-angular/issues/370

**Comment by arturovt** [comment]
I’ll close the issue since Angular dropped the support for IE11 and now it emits only evergreen bundles.
