### ISSUE TITLE
Uncaught Error: application '@single-spa/first-app' died in status SKIP_BECAUSE_BROKEN: In this configuration Angular requires Zone.js

### ISSUE THREAD

**Issue by JakobBablitschky** [single-spa/single-spa-angular#357]
I tried to setup a single-spa project featuring angular projects locally. I created a new root-config and a new angular project, following the Quickstart manual.

I get following error, when trying to mount the angular application:

Uncaught Error: application '@single-spa/first-app' died in status SKIP_BECAUSE_BROKEN: In this configuration Angular requires Zone.js

I realize that there's been a similar bug before, where the zone version was faulty. That's why I tried multiple Zone versions (also 0.10.3), but the error persisted.

Since I got the issue while trying to set up a really basic project, maybe this is a general issue right now and not my fault?
If you can think of anything I might've done wrong, please let me know.

Like I said, I didn't change anything code wise. Just used the default projects, created with "npx create-single-spa"

Any help, greatly appreciated

**Comment by arturovt** [comment]
Please, provide a minimal reproducible example.

**Comment by JakobBablitschky** [comment]
sure.. Steps to reproduce:

I followed the Quickstart guide here: https://single-spa.js.org/docs/getting-started-overview#quick-start
to create a new root-config.

- npx create-single-spa --moduleType root-config

Then I created a new angular app using

- npx create-single-spa --moduleType app-parcel

In the root-config project I reference my angular app in the "index.ejs" like this:

 

```
 <% if (isLocal) { %>
   <script type="systemjs-importmap">
     {
       "imports": {
         "@single-spa/welcome": "https://unpkg.com/single-spa-welcome/dist/single-spa-welcome.js",
        "@single-spa/first-app": "//localhost:4200/main.js",
        "@SRSNG/root-config": "//localhost:9000/SRSNG-root-config.js"
       }
     }
  </script>
   <% } %>
```


and in the microfrontend-layout.html I add this:

<application `name="@single-spa/first-app"></application>


I boot the angular app and check if the main.js is available. It is there

Then I boot the root-config app and get a blank page, with the mentioned error in the console.

**Comment by JakobBablitschky** [comment]
Also additional note: If I do the same things, using a react app instead of a angular app (also created with the command), everything works as expected.

**Comment by JakobBablitschky** [comment]
Update: I just found that there's a line in the index.ejs in root-config, that needs to be uncommented, to make it work with angular apps (<script src="https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js"></script>)

It's also described in a comment above the line, so my fault for not seeing that.
After uncommenting it and adding <base href="/"> to the top of the file, my angular app is being served.

Sorry for trouble. and thanks for response.
