### ISSUE TITLE
Unable to load migrated angular8 application on browser

### ISSUE THREAD

**Issue by bawatrader** [single-spa/single-spa-angular#376]
We have application developed in angular8 and used single-spa-angular to make our application singple-spa compatible.

Migration was successful using single-spa-angular and we were able to create the build also. 

Got it deployed on apache.

After deployment we hit the URL and nothing loads 

We tried to verify the application on single spa playground also and got error at step 4.

Snap for same is as below

![image](https://user-images.githubusercontent.com/74675840/123536875-652e0a80-d74a-11eb-9bbc-f42a95b68f1c.png)

Tried to google and get the answer but no luck.

Can someone pls help (we have demo scheduled coming with on single-spa)

**Comment by joeldenning** [comment]
The screenshot isn't enough to diagnose the issue - the browser console would contain a full stacktrace that would be more helpful. Even better though for diagnosing would be to create a github repo demonstrating the problem. Generally problems related to dev vs build are related to webpack public path (`--deploy-url`)

**Comment by arturovt** [comment]
Closing due to the lack of information.
