### ISSUE TITLE
SubRouter Angular SPA

### ISSUE THREAD

**Issue by checho1213** [single-spa/single-spa-angular#377]
hello, I'm trying to start using microfrontends with Angular SPA, for this I download the repository "Coexisting Angula MicroFrontends", I have added a new component to the app1 project and I want to route it from the navbar but it has not succeeded in getting the component to load correctly, I have tried adding the route as a child: const routes: Routes = [
  {
    path: "**",
    component: EmptyRouteComponent,
    children: [{ path: "data1", component: Pruebadata1Component }],
  },
  
];  and as a parent route: const routes: Routes = [
  {
    path: "**",
    component: EmptyRouteComponent,
    children: [],
  },
  { path: "data1", component: Pruebadata1Component }
]; but it doesn't work, which I'm doing wrong

**Comment by joeldenning** [comment]
The coexisting-angular-microfrontends repo is the older example. https://github.com/angular-microfrontends is the newer one. Here's some documentation that talks about routing: https://single-spa.js.org/docs/ecosystem-angular#configure-routes
