### ISSUE TITLE
single-spa latests and angular 12, fails to compile: Invalid parser object...

### ISSUE THREAD

**Issue by pgarzina** [single-spa/single-spa-angular#379]
### Demonstration

We have updated one of our microfrontend apps to single-spa latest and angular 12, and it stoped compiling.

the issue comes down to our ` environment.ts` file:

```
declare var require: any;

export const environment = {
  production: false,
  API_URL: '',
  API_STATIC_URL: '',
  ...
  app_version: require('../../package.json').version,
  library_version: require('../../node_modules/@cognism/app-library/package.json').version,
};
```

We read both our current app and our lib version from their package.json files. And that worked fine until updating both the single spa single spa dependencies to latest and angular to 12.

We also created a blank angular 12 project, and reading from package.json works just fine. After adding single-spa `ng add single-spa-angular`, it does not compile anymore and throws an error, which seems like the issue lies somewhere in single-spa or some of its dependencies.

We tried importing with `import` along with `allowSyntheticDefaultImports` and `resolveJsonModule` but that fails as well.

During the update we moved from
`"single-spa": "^5.9.1"` -> `"single-spa": "^5.9.3"`,
`"single-spa-angular": "^4.9.1"` -> `"single-spa-angular": "^5.0.1"`,
`"@angular-builders/custom-webpack": "^10"` -> `"@angular-builders/custom-webpack": "^12.1.0"`,
`"webpack-merge": "^5.7.3"` -> `"webpack-merge": "^5.8.0"`

Feel free to ask any additional info if needed.
Thanks

### Expected Behavior

The application should compile.

### Actual Behavior

The application does not compile and throws an error

```
./src/environments/environment.ts:4:0-41 - Error: Module not found: ValidationError: Invalid parser object. Json Modules Plugin has been initialized using a parser object that does not match the API schema.
 - parser has an unknown property 'system'. These properties are valid:
   object { parse? }

```

**Comment by pgarzina** [comment]
the compiler throws an error in this case as well
```
import { version as libVersion } from '../../node_modules/@cognism/app-library/package.json';
import { version as appVersion } from '../../package.json';

@Component({
  selector: 'app-search-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  constructor(private renderer: Renderer2) {
    console.log(`appVersion `, appVersion);
    console.log(`libVersion `, libVersion);
  }
```

**Comment by joeldenning** [comment]
I don't spend much time supporting Angular anymore, so if others watching are able to comment that would be helpful. A github repository demonstrating the issue would also be helpful.

**Comment by OriolInvernonLlaneza** [comment]
Hi! I'm stuck with the same error.
From what I understand, that parser option has been removed from Webpack 5 and "@angular-builders/custom-webpack" forces that version on the projecto, so the error gets thrown.
I saw [this issue](https://github.com/single-spa/single-spa/issues/698) on the single-spa repo, however the webpack-config that filoxo links is still in beta and is only for React.
I guess we need to fix the webpack config from single-spa-angular.

**Comment by OriolInvernonLlaneza** [comment]
> I guess we need to fix ([this rule here](https://github.com/single-spa/single-spa-angular/blob/1c5de4d72b44ed150616ec0734a6e6e419374e7e/libs/single-spa-angular/webpack/index.ts#L46)?) the webpack config from single-spa-angular.

I tried in local and it seems to work removing that parser rule.

**Comment by OriolInvernonLlaneza** [comment]
I have put the changes that got it working for me in a PR. I ran and passed all the tests. I hope I didn't make any mistakes as it is my first time contributing.

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/single-spa-angular/releases/tag/v5.0.2
