### ISSUE TITLE
Getting Error while integrating plotly js with single-spa-angular

### ISSUE THREAD

**Issue by murugan1992info** [single-spa/single-spa-angular#383]
While trying to integrate plotly js with single-spa-angular, in a browser console i'm getting an error, but if I try with standalone angular app, it's working fine. I have raised a [stackoverflow ](https://stackoverflow.com/questions/68743298/getting-error-while-trying-plotly-js-with-single-spa-angular?noredirect=1#comment121490762_68743298) issue on that.

In that issue I have tried with angular 11 with related dependencies version, even I tried with latest version of dependencies with angular 12 but no luck getting same error only.

Please help me to solve this issue. Thanks.

**Comment by joeldenning** [comment]
I don't spend much time on maintaining single-spa-angular, so if others can help with this one that would be appreciated.
