### ISSUE TITLE
Nav app is getting replaced by the route app in the dom sometimes on page load

### ISSUE THREAD

**Issue by amoghh** [single-spa/single-spa-angular#388]
I have 2 angular 12 apps as parcels created using single spa generator
i use one of the app in 'NAV' and the other one in a 'Route'
the issue that i am coming across is sometimes the app which is supposed to load for the route replaces the app which is supposed to load in the nav in the dom. Why is this happening.
This issue can be reproduced by creating new angular apps via the generator

**Comment by amoghh** [comment]
Attached the video here
[](url)

https://user-images.githubusercontent.com/16559388/135027750-d0080e29-42ec-486d-9c93-3e893947e736.mp4

**Comment by joeldenning** [comment]
I don't spend much time maintaining single-spa-angular, but welcome pull requests to address any issues. There are a few others who occasionally help in maintaining it, but they are not very active right now in doing so. I'll keep this issue open for others to comment on - the most helpful thing you can do would be to provide a github repository demonstrating the issue. A screen recording is not sufficient to diagnose issues in a lot of cases.

**Comment by amoghh** [comment]
I figured out the issue. This was caused because both the applications have the same prefix "app" . The prefixes need to different if two angular apps need to run simultaneously in the DOM. Yes it is present in the documentation, but since i generated these projects using "create-single-spa" generator i dont have control over how the angular project is created and specify my own prefix while creation. I think there should be an option to allow to enter the project prefix in the create-single-spa generator for Angular framework.

**Comment by joeldenning** [comment]
Closing since you found a fix
