### ISSUE TITLE
Startup swallows errors

### ISSUE THREAD

**Issue by werpu** [single-spa/single-spa-angular#390]
### Demonstration

The single spa angular startup swallows errors, this was not a problem until Angular12 where the startup is refused due to missing routes.
The problem is that in the bootstrapfunction a normal startup is performed on a promise but in case of an error an no log is sent to the browser console. This results in a swallowed error and a white screen.
The fix is to wrap the error handling into a promise like this:

return new Promise((resolve, reject) => {
platformBrowserDynamic(getSingleSpaExtraProviders().bootstrapModule(AppModule)
.then(data => resolve(data))
.catch(error => {
console.log(error);
reject(error)
})
 

### Expected Behavior

In case of an angular init the error should not be swallowed

### Actual Behavior
silent fail

I could reproduce this behavior by generating a new angular 12 application and then running single-spa-anagular init on top of it. The final result produced errors because no base href and routes were set, but those errors were silently swallowed.

**Comment by joeldenning** [comment]
This repository doesn't have many active maintainers. I do not spend much time on it and don't know when anyone will get to it.

**Comment by arturovt** [comment]
The code to bootstrap the application is on your side, not on the single-spa-angular side, so it's your responsibility for how errors are handled. Angular doesn't swallow errors. They might be swallowed by single-spa itself:

https://github.com/single-spa/single-spa/blob/f28b5963be1484583a072c8145ac0b5a28d91235/src/lifecycles/mount.js#L48

So you need to add your own error handler through `import { addErrorHandler } from 'single-spa'`.
