### ISSUE TITLE
Single-spa angular app child routing doesn't work

### ISSUE THREAD

**Issue by Karthickg2274** [single-spa/single-spa-angular#404]
I am working on a project where I have  to implement micro-frontend architecture , currently I have 3 projects

1. root-app.
2. app1(this is in angular, when I see localhost:5000/app1 I am able to load the app, but when I want to do routing with in app1 like localhost:5000/app1/sub-route, its not working)
3. app2

**Comment by OriolInvernonLlaneza** [comment]
Could you provide an example repo?
Also check the routing part of Angular docs: https://single-spa.js.org/docs/ecosystem-angular#routing

**Comment by Karthickg2274** [comment]
> Could you provide an example repo? Also check the routing part of Angular docs: https://single-spa.js.org/docs/ecosystem-angular#routing

This is my root app => https://github.com/Karthickg2274/micro-root
This is one of child app => https://github.com/Karthickg2274/micro-dashboard
 It that child app .. i have a menu button .. on clicking that it has to go to  its menu component, but itsn't
 like while clicking the button in this page http://localhost:4200/dashboard, its going to http://localhost:4200/menu and 
http://localhost:4200/dashbord/menu also comes blank page, evn though i have that component

**Comment by OriolInvernonLlaneza** [comment]
It could be that you are not setting up main.single-spa.ts correctly. You are missing the SingleSpaExtraProviders and NavigationStart on your lifecycles in. See: https://single-spa.js.org/docs/ecosystem-angular/#api-updates

**Comment by Karthickg2274** [comment]
thank you!!
