### ISSUE TITLE
DOM isn't unmounted when app uses `BrowserAnimationsModule` + `APP_INITIALIZER` + `RendererFactory2`

### ISSUE THREAD

**Issue by Den-dp** [single-spa/single-spa-angular#407]
I found that this combination https://github.com/Den-dp/single-spa-angular-unmount-issue/commit/259d59fdd9c9a1ca2f436094005299bc135ddcc4 of `BrowserAnimationsModule` + `APP_INITIALIZER` + `RendererFactory2` breaks unmounting in Angular 13.

### Demonstration
https://github.com/Den-dp/single-spa-angular-unmount-issue (steps in Readme)

### Expected Behavior
app should be unmounted

### Actual Behavior
styles are removed from the DOM but HTML elements are not.

![C9ecXgLNgl](https://user-images.githubusercontent.com/1770529/151609038-5483b9d4-d55a-4563-9bff-629f7067fca6.gif)

PS: a use case in my reproduction may look meaningless, but in reality, I encountered this issue by importing CoreModule with `APP_INITIALIZER` from `@alfresco/core` library
https://github.com/Alfresco/alfresco-ng2-components/blob/3aa629d4be9865bb84fd13c045c6c1488fa41c6a/lib/core/core.module.ts#L151-L156
which internally uses `RendererFactory2`
https://github.com/Alfresco/alfresco-ng2-components/blob/3aa629d4be9865bb84fd13c045c6c1488fa41c6a/lib/core/services/directionality-config.service.ts#L29

**Comment by arturovt** [comment]
I created an issue in the Angular repository.

**Comment by Den-dp** [comment]
Very appreciate you taking care of this!

Also adding a link for those who may wonder https://github.com/angular/angular/issues/45108

**Comment by arturovt** [comment]
Closing since the fix has been merged into Angular repository.
