### ISSUE TITLE
ng add single-spa-angular errors with Angular 13

### ISSUE THREAD

**Issue by Nimzi-Git** [single-spa/single-spa-angular#415]
Hi,
I am getting the below error while running 'ng add single-spa-angular' command in Angular 13
Error: Cannot find module '@angular-devkit/core'
Require stack:
- /node_modules/single-spa-angular/schematics/ng-add/index.js
- /node_modules/@angular-devkit/schematics/tools/export-ref.js
- /node_modules/@angular-devkit/schematics/tools/index.js
- /node_modules/@angular/cli/utilities/json-schema.js
- /node_modules/@angular/cli/models/command-runner.js
- /node_modules/@angular/cli/lib/cli/index.js
- /node_modules/@angular/cli/lib/init.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/node_modules/single-spa-angular/schematics/ng-add/index.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)

Here is the Angular version I am using:
Angular CLI: 13.2.6
Node: 16.14.0
Package Manager: npm 8.3.1
OS: darwin x64

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.2.6
@angular-devkit/schematics      13.2.6
@schematics/angular             13.2.6
rxjs                            7.5.5
typescript                      4.5.5

**Comment by arturovt** [comment]
This only may happen if there's an issue with your dependencies within the project. The `@angular/cli` depends on the `@angular-devkit/core`, so it should exist within the workspace.

I just created a barebones project through `ng new` and ran `ng add single-spa-angular`, it went w/o errors. My env is:
```
Angular CLI: 13.2.6
Node: 14.15.5
Package Manager: yarn 1.22.17
OS: darwin x64

Angular: 13.2.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.2.6
@angular-devkit/schematics      13.2.6
@schematics/angular             13.2.6
rxjs                            7.5.5
typescript                      4.5.5
```

**Comment by Nimzi-Git** [comment]
thank you @arturovt .. yes it seems the angular was not installed correctly

**Comment by tscislo** [comment]
Thank you @arturovt! I just tested 6.0.2 with Angular 13.2.x and it works fine. Keep safe @arturovt!
