### ISSUE TITLE
Sharing Angular 13 as webpack external

### ISSUE THREAD

**Issue by AlbaSS18** [single-spa/single-spa-angular#418]
### Question
Hi,

I'm trying to share Angular 13 like we used to do before Ivy. 

Before, with Angular 11, we were able to share Angular using the UMD bundles of Angular and single-spa-angular. However, as discussed on issue #370, Angular stopped supporting UMD. 

Now, we have updated to Angular 13 and we are still unable to share it because the published formats (fesm2015 and fesm2020) throw `import declarations may only appear at top level of a module` error. I guess we need the bundles to be on System format. Nevertheless, 
the angular esm-bundle is still on v12 (https://github.com/esm-bundle/angular__core/pull/228) and single-spa-angular is not exported in this format (https://github.com/esm-bundle/new-repo-instructions/issues/18).

Thank you for the quick support for Angular 13 and your work on this project.
### Environment

<pre><code>
Libs:
- @angular/core version: 13.3.0
- single-spa-angular version: 6.1.0

**Comment by arturovt** [comment]
Hey, I know this is an issue. I really would like to solve, I have enough knowledge in Angular but I don’t have enough knowledge in SystemJS and would like some external help in this.

**Comment by AlbaSS18** [comment]
Hello @arturovt,

The last time that we tried to fixed this, Joel Denning said that he would prefer to change ng-packagr's rollup configuration to export in system format (https://github.com/single-spa/single-spa-angular/issues/370#issuecomment-875290631). However, it seems that it is not possible because they strictly follow [Angular Package Format](https://angular.io/guide/angular-package-format#exports) and it says that the only available export formats are fesm2015 and fesm2020 as seen [here](https://github.com/ng-packagr/ng-packagr/blob/c50e6b755a2fd67a56d6d0ac778b7494f4dd93d4/src/lib/ng-package/entry-point/entry-point.ts#L7) and [here](https://github.com/ng-packagr/ng-packagr/blob/c50e6b755a2fd67a56d6d0ac778b7494f4dd93d4/src/lib/ng-package/entry-point/write-bundles.transform.ts#L22).

So, I guess that we have two options:

1. Patching ng-packagr to produce system bundles (because I don't think that they will accept changing the library if APF doesn't change too) like it was proposed for UMD (https://github.com/single-spa/single-spa-angular/pull/374).
2. Generating the bundles through the [esm-bundle](https://github.com/esm-bundle) repo like it is done with Angular.

I guess option 2 is more clean and should be preferred.

**Comment by arturovt** [comment]
So you basically need Angular 13 to be published in a SystemJS format like it's done for Angular 12 through the esm-bundle repo?

**Comment by AlbaSS18** [comment]
Yes, I think it is the best option because changing ng-packagr might not be possible for the reasons I gave in my last comment.

**Comment by AlbaSS18** [comment]
Thank you very much. 

We tried the Angular 13 files but it throws `ngDevMode is not defined` in the function singleSpaAngular of this library. I guess the error is caused because we aren't sharing it. Although you created the esm-bundle repo, it didn't publish anything on jsdelivr and unpkg. I think that the problem comes from not changing the template. Compare [single-spa-angular ]( https://github.com/esm-bundle/single-spa-angular/blob/7725c72de82f8f78ef7611926c32719087b66168/package.json#L2) with [angular__common](https://github.com/esm-bundle/angular__common/blob/main/package.json#L5)

**Comment by arturovt** [comment]
The single-spa-angular was created this night from the template, it’s not ready yet.

**Comment by AlbaSS18** [comment]
I have tried with the new single-spa-angular version that you just published and the `ngDevMode is not defined` error is fixed. Now we are back to [this error](https://github.com/single-spa/single-spa-angular/issues/288), so that means that we just need the esm-bundle to be able to share angular again. We will wait patiently until it's ready, so don't feel pressured. 

Thank you so much for your work and the quick answers. Stay safe :heart:

**Comment by arturovt** [comment]
The single-spa-angular has been published in System format: https://github.com/esm-bundle/single-spa-angular/blob/main/package.json#L2-L26

**Comment by AlbaSS18** [comment]
We have just tested and it works perfectly. Thank you very much :smile: !

**Comment by arturovt** [comment]
Great. Can we close the issue?

**Comment by AlbaSS18** [comment]
Yes 👍 . Thank you very much, Arturo 😄 !
