### ISSUE TITLE
mount application after another

### ISSUE THREAD

**Issue by youssefM95** [single-spa/single-spa-angular#422]
Hi
i'm trying to mount one application into another using **domElementGetter**, it works fine but when i do refresh the bootstrap function return error.
I want a way to mount App1 before App 2.
![image](https://user-images.githubusercontent.com/26021197/160285401-7fa5a7e2-c231-4c0d-aea6-7bed5cef61c2.png)

**Comment by filoxo** [comment]
You cannot accomplish this using donElementGetter. Single-spa makes no guarantees for load order and this is a bad practice. Use [cross microfrontend imports](https://single-spa.js.org/docs/recommended-setup/#cross-microfrontend-imports) for sharing ui that uses the same framework, or [single-spa Parcels](https://single-spa.js.org/docs/parcels-overview) for cross-framework interop.
