### ISSUE TITLE
Intercommunication between two anuglar application

### ISSUE THREAD

**Issue by walieddine** [single-spa/single-spa-angular#423]
I want to transmit data between two applications.  I used the event but the value sent from Angular R1 app to Angular R2 app is lost.

  Scanario:

  Angular app R1 is mounted under route '/r1'
  Angular R2 app is mounted under '/r2' route
  We are route r1 , so app R1 is mounted.  Here we send a custom event.
  Then we go to the /r2 route, so R1 is unmounted and R2 is mounted.  So, at the time the event is sent from R1, there is no R2 to listen to it.
  Can anyone help here.  Any help is much appreciated.

**Comment by filoxo** [comment]
This makes sense, this is how the browser event system works. It does not replay events for new subscribers. Rxjs is a solid option to accomplish this, and is documented here: https://single-spa.js.org/docs/ecosystem-angular/#inter-app-communication-via-rxjs

**Comment by filoxo** [comment]
Any other pub/sub library such as [mitt](https://github.com/developit/mitt) would also work. See also https://single-spa.js.org/docs/recommended-setup/#ui-state

**Comment by arturovt** [comment]
Yeah, RxJS completely solves the issues. You need an event bus that uses replay subject internally as a buffer:
```ts
export class EventBus {
  private buffer$: ReplaySubject<unknown>;

  constructor(private readonly bufferSize = 1) {
    this.buffer$ = new ReplaySubject(bufferSize);
  }

  send(event: unknown): void {
    this.buffer$.next(event);
  }

  clear(): void {
    this.buffer$.complete();
    this.buffer$ = new ReplaySubject(this.bufferSize);
  }

  getLatest() {
    return this.buffer$.pipe(take(1));
  }
}
```

Then you can attach an event bus to the global object:
```ts
declare global {
  interface Window {
    bus: EventBus;
  }
}

window.bus ??= new EventBus(1);
```

```ts
// app1
window.bus.send({ someData: 20 });
router.navigateByUrl('/app2');

// app2
window.bus.getLatest().subscribe(...);
```
