### ISSUE TITLE
External file with SystemJS

### ISSUE THREAD

**Issue by Eduk29** [single-spa/single-spa-angular#426]
### Question

Hi!

I would like to know if it is possible to use a systemjs.config.js file external to index.ejs? Has anyone been able to successfully complete this integration?

Thanks,

### Environment

<pre><code>
Libs:
- @angular/core version: 12.0.0
- single-spa-angular version: 6.0.0

Others:

</code></pre>

**Comment by filoxo** [comment]
The question isn't super clear. Are you referring to something like https://github.com/single-spa/single-spa-angular/issues/418?

**Comment by arturovt** [comment]
Hi @Eduk29 . I'm not sure what you're asking and I'm not sure what means _external to index.ejs_.

**Comment by Eduk29** [comment]
Ok,

I want to create an systemjs.config.js file with imports-map configuration in root directory and I want to configure index.ejs to push imports-map configuration from this file.

**Comment by arturovt** [comment]
Alright, so my next question would be how is this related to single-spa-angular?

**Comment by Eduk29** [comment]
@arturovt 

Knowing that single-spa uses systemJs as a module loader, I want to know if it is possible to configure the imports-map with this approach (as is done in systemjs without using single-spa).

**Comment by arturovt** [comment]
I cannot answer if it's possible or not. This is better to ask the question in the SystemJS repository.

**Comment by Eduk29** [comment]
@arturovt 

Ok, I understood that the configuration of the index.ejs file was a single-spa thing and not a SystemJS thing. Forgive the mistake.

**Comment by arturovt** [comment]
I’ll close the issue since it’s better to ask the question in single-spa or SystemJS repository.
