### ISSUE TITLE
[Brainstorming] sharing @angular/material between microservices

### ISSUE THREAD

**Issue by StevenKolamkuzhiyil** [single-spa/single-spa-angular#433]
### Question
Is it possible to share `@angular/material` between microservices? 

By following this [example](https://github.com/lqc/spa-test) I was able to share Angular dependencies between microservices.
But when I tried to share `@angular/material` I got following error in the application where I was using `@angular/material` as external:
```
ERROR Error: Could not find HttpClient provider for use with Angular Material icons. Please include the HttpClientModule from @angular/common/http in your app imports.
    at p (@angular__material__icon.js:727:3216)
    at g._fetchIcon (@angular__material__icon.js:727:8373)
    at g._loadSvgIconFromConfig (@angular__material__icon.js:727:6880)
    at g._getSvgFromConfig (@angular__material__icon.js:727:6022)
    at getNamedSvgIcon (@angular__material__icon.js:727:5573)
    at O._updateSvgIcon (@angular__material__icon.js:734:4965)
    at O.set svgIcon [as svgIcon] (@angular__material__icon.js:734:2070)
    at yc (@angular__core.js:572:21212)
    at @angular__core.js:572:12339
    at Ka (@angular__core.js:572:12381)
```

[Generated Angular CDNs with @angular/material](https://github.com/StevenKolamkuzhiyil/spa-shared-angular)

I was able to create a workaround by manually instantiating the MatIconRegistry and providing it in the AppModule. But this solution doesn't seem to be usable since other modules might have the same issue.
I don't understand why the shared scripts don't have access to the providers in the AppModule and would be thankful if someone could help me understand or solve this issue.

Kind regards,
Steven

### Environment

<pre><code>
Libs:
- @angular/core version: 11.2.14
- @angular/material version: 11.2.13
- single-spa-angular version: 4.9.2
</code></pre>

**Comment by arturovt** [comment]
This is possible to share dependencies out of the box with single-spa-angular, but only single-spa-angular@6.2.0+ supports it (see the guide: https://single-spa.js.org/docs/ecosystem-angular/#shared-angular).

`@angular/cdk` and `@angular/material` packages are published in SystemJS format in in this repos:
- https://github.com/esm-bundle/angular__cdk
- https://github.com/esm-bundle/angular__material

But they're published for Angular 14. Angular 11 is deprecated long time ago and there's no reason to support it. Consider upgrading your application to the latest Angular version to get latest features.
