### ISSUE TITLE
Massive increase in "ng serve" time due to different static content root

### ISSUE THREAD

**Issue by nomnom88** [single-spa/single-spa-angular#435]
I'm currently on my government related dev machine which can't push to Github so apologies that I don't have a forked repo with fix.

To reproduce (with angular 13):
1. ng new whatever
2.  ng add single-spa-angular
3. ng serve

### Expected Behavior
Fast build of minimal app

### Actual Behavior
Slow build.

The cause is the following change:
libs/single-spa-angular/webpack/index.ts in https://github.com/single-spa/single-spa-angular/pull/398/files

By changing the static document root to the root of the angular project we are also including "node_modules". This drastically increases the number of files that the Express HTTP server watches and slows the build down by a huge degree. Disabling the server (static=false) or just the watch functionality (static.watch=false) alleviates the problem.

I'm not quite sure what the point is of this server if the document root can be changed from "./src" to "./" without repercussions...?

**Comment by arturovt** [comment]
Hey, I've removed that property completely. I've tested its removal with integration apps in this repository and I didn't encounter any issues. The fix is published in `6.3.1`.

**Comment by nomnom88** [comment]
awesome, thank you
