### ISSUE TITLE
Build error after update to Angular 14 with 'single-spa-angular' v7.0.0

### ISSUE THREAD

**Issue by akhila2708** [single-spa/single-spa-angular#443]
Issue:
Error: node_modules/single-spa-angular/src/public_api.d.ts:2:34 - error TS2307: Cannot find module './single-spa-angular' or its corresponding type declarations.
2 export { singleSpaAngular } from './single-spa-angular';

Steps to reproduce:
Step1: Created a brand new Angular 14 application.
Step2: Installed single-spa into application of version '5.9.3' using command 'npm i single-spa@5.9.3'
Step2 : Installed single-spa-angular with version 7.0.0 using command 'npm i single-spa-angular@7.0.0'
Step3: Tried to compile the application using 'ng serve'
Step4: compilation failed with below error:

Issue:
Error: node_modules/single-spa-angular/src/public_api.d.ts:2:34 - error TS2307: Cannot find module './single-spa-angular' or its corresponding type declarations.
2 export { singleSpaAngular } from './single-spa-angular';

### Expected Behavior
Application should be build/compiled successfully

### Actual Behavior
Build error in application

Analysis:

When i did 'npm i single-spa-angular' it downloaded single-spa-angular having src file only below 4 items
node_modules\single-spa-angular\src\extra-providers.d.ts,
node_modules\single-spa-angular\src\prod-mode.d.ts,
node_modules\single-spa-angular\src\public_api.d.ts,
node_modules\single-spa-angular\src\types.d.ts

but if we see the code of public.api.d.ts file it has reference for singleSpaAngular as below
export { enableProdMode } from './prod-mode';
export { singleSpaAngular } from './single-spa-angular';
export { getSingleSpaExtraProviders } from './extra-providers';

but there is no file downloaded with name singleSpaAngular in node_modules\single-spa-angular\src location.

When i check the GIT location https://github.com/single-spa/single-spa-angular/tree/master/libs/single-spa-angular/src i found the the file single-spa-angular.ts which didn't come with npm install.

I did the work around. Just copy pasted this file manually and Issue Fixed !!! Application started.

But definitely there is some issue in npm install.

**Comment by arturovt** [comment]
As I told you in the previous issue I can’t do more than guessing what might happened. I also asked to re-open the previous issue if you have a reproduction provided, but not opening the new one since it’s impossible to track the same issue with multiple ones.

**Comment by arturovt** [comment]
I have published 7.0.1. This has been a regression in ng-packagr itself. I closed the issue because I wasn't able to replicate this behavior in the current workspace. Sorry for the inconvenience.
