### ISSUE TITLE
Type declarations missing on single-spa-angular 7.0.0

### ISSUE THREAD

**Issue by joopip** [single-spa/single-spa-angular#447]
### Demonstration

I installed single-spa-angular on a clean new angular 14 project, but cannot compile and throws me an error with missing type declarations.

using single-spa-angular 7.0.0, angular 14.0.4

### Actual Behavior

Cannot find module './single-spa-angular' or its corresponding type declarations.

**Comment by josemn24** [comment]
I have the same problem. So, at the moment I have downgraded the version to angular 13 :(

**Comment by arturovt** [comment]
Ok, this is really weird. I have created an issue in the `ng-packagr` repository, waiting for their reply and then will make necessary changes.

**Comment by arturovt** [comment]
This is a regression in ng-packagr itself, I will republish a new single-spa-angular version once new ng-packagr version is available.

**Comment by arturovt** [comment]
I have published 7.0.1.
