### ISSUE TITLE
Question/Issue: Should style-loader be a dev dependency?

### ISSUE THREAD

**Issue by dkwakkel** [single-spa/single-spa-angular#451]
**Describe the bug or question**
There is a CVE for terser, and through terser-webpack-plugin - webpack - style-loader dependencies it is part of single-spa-angular@6.0.1.
I am not good in npm dependencies, but I expected webpack to be a dev dependency (by which the CVE is no longer a problem).
Am I right, and if so can this be fixed?

**To Reproduce**
 npm list --production --all
├─┬ single-spa-angular@6.0.1
│ ├── @angular/core@13.2.3 deduped
│ ├── json5@2.2.1
│ ├── single-spa@5.9.3 deduped
│ ├─┬ style-loader@3.3.1
...
│ │   ├─┬ terser-webpack-plugin@5.3.1
...
│ │   │ ├─┬ terser@5.10.0

**Expected behavior**
webpack (and terser) not being a production dependency.

**Comment by arturovt** [comment]
Yes, it should, because `style-loader` is not a part of the Angular CLI.
