### ISSUE TITLE
Critical Error: Vue-Router error when navigating from a Angular app

### ISSUE THREAD

**Issue by brunomartinspro** [single-spa/single-spa-angular#452]
### Demonstration
When going from a Vue app to an Angular app, and then returning to the root i get the error:
![error](https://user-images.githubusercontent.com/7645736/185186256-bca0c12a-ee1e-4bb0-823f-92f64ad59fd9.png)

Complete Demonstration
![error](https://user-images.githubusercontent.com/7645736/185185787-7bd59540-99a0-4ba7-8f19-ab6f881129a6.gif)

The error can be reproduced using this repository https://github.com/brunomartinspro/single-spa (the README includes instructions for reproducing this)

#### Possible Vue-Router fix
The possible correction for this behavior was created on https://github.com/vuejs/router/pull/1502

### Expected Behavior
I can navigate back to the root from another angular app

### Actual Behavior
I get an error in the Vue-Router, and it prevents me from returning to the root

Thank you!

**Comment by arturovt** [comment]
I'm not knowledgeable in Vue.js and how to debug/fix it.
