### ISSUE TITLE
 single-spa-angular@5 ng update schematic

### ISSUE THREAD

**Issue by manbearwiz** [single-spa/single-spa-angular#455]
### Description of Proposed Feature

Create update schematic to remove `AnimationEngine` to automatically fix [this breaking change](https://github.com/single-spa/single-spa-angular/pull/362#discussion_r640970908).

### In what way would you use it?

I have a lot of ng11 micro frontends that teams will be upgrading from ng11/single-spa4 to ng12/single-spa5 and I am trying to automate as much of the process as possible.

The result of `ng update single-spa-angular@5` should result in the following changes

![image](https://user-images.githubusercontent.com/3688847/188007041-87c34bc4-beb6-43cb-94ab-2f218f011e22.png)

I already wrote the schematic to do this. Just trying to gauge interest in this feature before creating a PR.

**Comment by arturovt** [comment]
hey @manbearwiz . I don't mind if you make a PR with this change, I don't have enough time to maintain it so the external support is appreciated.

**Comment by arturovt** [comment]
the issue is that we don't have the `5.x` branch for `5.x` versions, I prolly need to create a branch from the latest commit related to 5.x, because we can't merge this change into the master.

**Comment by manbearwiz** [comment]
Yeah I was going to ask about that. Its not going to hurt anything being in master, but then it would only work for users upgrading straight from 4 to 7. Do we merge to master and then cherry-pick into a 5 branch? 

I have my changes [in this branch](https://github.com/single-spa/single-spa-angular/compare/master...manbearwiz:single-spa-angular:feat/v5-update-schematic). Everything in `ng-update/index.ts` is tested and working on my projects locally; however, due to the nature of upgrade schematics, I'm not sure its possible to do a full integration test locally. We might need to publish an alpha package.

**Comment by arturovt** [comment]
I've created a branch called `5.x` from the latest commit before Angular 13 upgrade

**Comment by arturovt** [comment]
Closing this issue as stale and there’s no work going to be done on this.

**Comment by manbearwiz** [comment]
Sorry, ended up handling this with schematics on my end and forgot to come back to finish this up. I was able to validate it though and migrated a bunch of projects pretty painlessly. Would you still want a PR for this? Assuming you would want me to rebase off of the 5.x branch and target that?
