### ISSUE TITLE
SingleSpaAngularOptions's NgZone property - accepting a promise

### ISSUE THREAD

**Issue by KrzysztofJaneczko** [single-spa/single-spa-angular#456]
#### Background
My team supplies an Angular-based remote to another application (which in turn is based on React) which is maintained by another team. Recently we've been asked whether we could load Zone.js on our own. The reason being that they don't want to load any dependencies that might not be required by the user. I support rationale behind the idea - their application loads micro frontend remotes from multiple suppliers and not all of them use Angular. There's no reason to load Zone.js for users who never stumble upon the module we're developing. In short, all remotes should be self-sufficient when it comes to dependencies. The slightly prolonged loading time is an acceptable tradeoff.

#### The problem
Loading Zone.js is not a problem on its own, rather the timing. The `singleSpaAngular` function requires a Zone.js instance to be present at the very moment it's called - which is too late for us. We need a way to postpone the execution of logic that depends on Zone.

#### The proposal
Apart from `NgZone` and `'noop'`, the `NgZone` property could also accept `Promise<NgZone>`. The `bootstrap` function is already asynchronous, which makes adding handling such case fairly simple.

### In what way would you use it?
Instead of just passing `NgZone` to the function, We would pass a promise that would resolve once Zone.js is loaded.

Do you think it makes sense? If yes, then I'd like to create a PR. If you see a better way of dealing with this issue, please leave a comment. I'll be happy to discuss. Thanks!

**Comment by arturovt** [comment]
I don't think it makes sense to bring it into the codebase just for your specific case. Well, I could think of other ways to fix it. The `singleSpaAngular` doesn't require zone.js. It requires `NgZone` class to be provided, but `NgZone` class doesn't do assertions until it's created, it's created when the root module is bootstrapped and throws:
```js
if (typeof Zone == 'undefined') {
            throw new Error(`In this configuration Angular requires Zone.js`);
        }
```
You can load zone.js on demand through the `script`:
```js
script = createElement('script')
script.src = 'https://.../zone.min.js'
script.onload = () => resolvePromsie()
```

You can load the script before bootstrapping the `AppModule`:
```js
let zoneJsLoaded = false;
async function loadZoneJs() {
  if (zoneJsLoaded) return

  await new Promise(resolve => {
    const script = document.createElement('script')
    script.src = '...'
    script.addEventListener('load', () => {
      zoneJsLoaded = true
      resolve()
    })
    document.head.appendChild(script)
  })
}

bootstrapFunction: async () => {
  await loadZoneJs()
  return platformBrowserDynamic().bootstrapModule(AppModule)
}
```
