### ISSUE TITLE
Angular Cli 15: Remove the new `StylesWebpackPlugin`

### ISSUE THREAD

**Issue by jogelin** [single-spa/single-spa-angular#463]
#### Before/Now: 
- The styles are taken from the Angular Cli Config and added as an entry. 
- Single Spa Angular will merge this entry with the main to have only one bundle
- Single Spa Angular will add a style loader to be sure that the style is part of the bundle
- Single Spa Angular will remove `MiniCssExtractPlugin`

**Since Angular Cli 15, there is a new way to manage `styles`. A plugin named `StylesWebpackPlugin` will add the style entry during the Webpack compilation. All steps above are then useless.**

#### Futur/Idea:
- Add Again the styles to the list of entries and let Single Spa Angular work in the same way.

#### Manual approach (used on our project):
-  I can remove the plugin `StylesWebpackPlugin` and 
 - Add the styles manually to the list of entries

#### Re-use the plugin:
- I can execute the plugin before but I don't know how
- or simply get the options and duplicate the plugin code

#### Create a Webpack new plugin: Maybe we should consider having a real Webpack plugin for Single Spa Angular that will be able to do the job when all plugins are done.

What do you think?

@arturovt

**Comment by arturovt** [comment]
@jogelin you're welcome to make a pull request, but we need first to migrate this workspace to Angular 15. So I'd do this in 2 separate PRs (the migration and the plugin removal). I'm not sure if I'll have time until these weekends to make a migration.

**Comment by NicmeisteR** [comment]
@jogelin can I ask how you fixed it for yourself? I'm currently working on a project and the styles not loading is breaking a lot of things for me at the moment. Thanks in advance!

**Comment by jogelin** [comment]
@NicmeisteR for the moment we just reverted what `Angular cli` did to be able to have `single-spa` working correctly:

Application `webpack.config.js`
```javascript
const singleSpaWebpackConfig = require('../../../tools/single-spa/webpack.config');

module.exports = (config, options) => {
  const singleSpaConfig = singleSpaWebpackConfig(config, { ...options, projectDirName: __dirname });
  return singleSpaConfig;
};
```

Our Global single-spa `webpack.config`:
```javascript
const singleSpaAngularWebpack = require('single-spa-angular/lib/webpack').default;

function removePluginByName(plugins, name) {
  const pluginIndex = plugins.findIndex((plugin) => plugin.constructor.name === name);
  if (pluginIndex > -1) {
    plugins.splice(pluginIndex, 1);
  }
}

module.exports = (config, options) => {
  config.entry = { main: config.entry['main'], styles: [require('path').join(options.projectDirName, '/src/styles.scss?ngGlobalStyle')] };
  removePluginByName(config.plugins, 'StylesWebpackPlugin');

  const singleSpaWebpackConfig = singleSpaAngularWebpack(config, {
    ...options,
    customWebpackConfig: { libraryTarget: 'system' },
  });

  return singleSpaWebpackConfig;
};
```

As you can see, we just remove the Angular Cli plugin but I am not really happy with that solution because we could miss some improvement from Angular Team. I would prefer that we create a plugin for Single Spa to be able to change the configuration later, after the plugin of Angular Cli

**Comment by NicmeisteR** [comment]
Thank you for the response @jogelin! I'm going to give this a try and see if it fixes my issue too. This has to be implemented in a lot of my projects unfortunately so was also hoping there was a Single Spa fix releasing soon so I can just update the dependencies.

Appreciate the help!

**Comment by ibamohamed** [comment]
@jogelin @NicmeisteR is there any change to be done in applications extra-webpack.config.ts to solve this issue? or we need to wait for a merge PR?

**Comment by dbpieter** [comment]
`/// @ts-ignore
require('./scss/styles.scss?ngGlobalStyle');`

Can also be 'fixed' with a require statement (placed it in main.ts) and without modifying webpack.config.

**Comment by NicmeisteR** [comment]
> `/// @ts-ignore` `require('./scss/styles.scss?ngGlobalStyle');`
> 
> Can also be 'fixed' with a require statement (placed it in main.ts) and without modifying webpack.config.

I'm thinking this might be the better solution, any progress on an Single-Spa update to resolve the issue yet or not really?

**Comment by Harsh8Mel** [comment]
@joeldenning are you looking into this yet?

**Comment by JanK-Qics** [comment]
I'm unable to make any of the suggested workarounds work. 

Context:
We are loading a single-spa-angular app into our legacy AngularJS old app. We don't have a single-spa-root, for BIG dependencies in the old code. The only working workaround for us is loading the CSS on the old side, however, that is avery untidy solution for us.

Do you have any suggestions for how to maybe load the styles.js/scripts.js that get compiled along the main.js that we load?

**Comment by jogelin** [comment]
@Harsh8Mel JoelDenning is not supporting Angular library. He already has a lot of work on other libraries and doesn't get money for it. I think a PR is welcome ;)

**Comment by jogelin** [comment]
@JanK-Qics 

The styles from Angular apps are parts of the `main.js` bundle because of `style-loader`.
By default, Angular CLI creates a separate file for the style but because it is a micro frontend architecture, you want to have everything in one bundle (theoretically). This is why single-spa replaces `MiniCssExtractPlugin` with `style-loader`.

So if you were not able to integrate your styles before, this issue will not help. You should first work on having your styles in your Angular bundle. You can use a custom Webpack config or the @dbpieter approach.

One tip, scope your angularjs styles and your Angular styles to avoid conflicts.

**Comment by JanK-Qics** [comment]
Thanks for the quick reply. 
So I guess we will try to make it work the new way. 
Do you have any leading examples of how to load a basic CSS to the extra-webpack.config.js

**Comment by jogelin** [comment]
This is extract of our configs:

`extra-webpack.config.js` in each micro-frontend
```javascript
const singleSpaWebpackConfig = require('../../../tools/single-spa/webpack.config');

module.exports = (config, options) => {
  const singleSpaConfig = singleSpaWebpackConfig(config, { ...options, projectDirName: __dirname });

  return singleSpaConfig;
};

```

`tools/single-spa/webpack.config`
```javascript
const singleSpaAngularWebpack = require('single-spa-angular/lib/webpack').default;
const { merge } = require('webpack-merge');
const SystemJSPublicPathPlugin = require('systemjs-webpack-interop/SystemJSPublicPathWebpackPlugin');

function removePluginByName(plugins, name) {
  const pluginIndex = plugins.findIndex((plugin) => plugin.constructor.name === name);
  if (pluginIndex > -1) {
    plugins.splice(pluginIndex, 1);
  }
}

module.exports = (config, options) => {
  config.entry = { main: config.entry['main'], styles: [require('path').join(options.projectDirName, '/src/styles.scss?ngGlobalStyle')] };
  removePluginByName(config.plugins, 'StylesWebpackPlugin');

  const singleSpaWebpackConfig = singleSpaAngularWebpack(config, {
    ...options,
    customWebpackConfig: { libraryTarget: 'system', libraryName: config.output.uniqueName },
  });
  const externals = [
    {
      ...require('./npm-dependencies').npmDependenciesExternals,
    },
  ];
  const plugins = [
    new SystemJSPublicPathPlugin({
      systemjsModuleName: `@selligent/${config.output.uniqueName}`,
    }),
  ];

  return merge(singleSpaWebpackConfig, { externals, plugins });
};

```

As you can see, we are hacking the current configuration of Angular to remove their plugin and add again the style to the list of entries to allow single-spa to do the replacement.

**Comment by JanK-Qics** [comment]
Yes, I saw this workaround and did not manage to make it work.
Maybe I missed something, I'm gonna give it another try :D.

**Comment by OrShalmayev** [comment]
> `/// @ts-ignore` `require('./scss/styles.scss?ngGlobalStyle');`
> 
> Can also be 'fixed' with a require statement (placed it in main.ts) and without modifying webpack.config.

Tried this one and the style breaks when I switch to another micro frontend

אי

**Comment by Pho3njx** [comment]
Another workaround that worked for me is to set the global styles file in every component. 
I know that's really dirty. But if you just need a temporary workaround and just have a small bunch of components it could help.

```typescript
@Component({
  selector: 'input-field',
  templateUrl: './input-field.component.html',
  styleUrls: ['../path/to/your/styles.scss', './input-field.component.scss'],
})
export class InputFieldComponent {
  // ...
}
```

**Comment by guiroco** [comment]
Hi! Any updates on this? I just migrated my application to Angular 15 along the upgrade of `single-spa-angular` to its latest version (`8.1.0`) and all my global styles coming from third party libraries are not being applied anymore.

**Comment by Fulvia1989** [comment]
> `/// @ts-ignore` `require('./scss/styles.scss?ngGlobalStyle');`
> 
> Can also be 'fixed' with a require statement (placed it in main.ts) and without modifying webpack.config.

This actually helped me.
I had to add these two lines:

`/// @ts-ignore` 
`require('src/styles.css?ngGlobalStyle');`

to both `main.ts` and `main.single-spa.ts`, plus importing the material core theme (one of the pre-built ones, in my case) :
`@import url('node_modules/@angular/material/prebuilt-themes/pink-bluegrey.css');`

 in the global `style.css` of each microfrontend.

I am just a beginner, I'll ask my senior friend to help me understand (and make it work, hopefully) the edit-webpack-config 
 proposed [here](https://github.com/single-spa/single-spa-angular/issues/463#issuecomment-1496047272).

For now I'll go with this temporary fix.
 
Thanks a lot.

**Comment by Alessandroinfo** [comment]
It's possibile to have all the assets in main and main.single-spa?

**Comment by Fulvia1989** [comment]
> It's possibile to have all the assets in main and main.single-spa?

I am afraid this is not related to the issue, but I'll leave here my two cents.

As far as I know, no you can't. You can import single files, not folders.

And you shouldn't anyway.
In single-spa, the assets need to be loaded from a dynamic location,and they use webpack public path. They also offer an easy method to do so.

You can import the function `assetsUrl` from the file `assets-url.ts` (whitch is automatically generated when you add single-spa to your project) in any component, assign the value to a variable and use it in the template:
`imageUrl: string = assetUrl('image.png');`

Check one of the official examples [here](https://github.com/daniloesk/single-spa-examples/blob/v20201211-registration/app11/src/app/home/home.component.ts)

**Comment by Pradeepshivaram** [comment]
> @NicmeisteR for the moment we just reverted what `Angular cli` did to be able to have `single-spa` working correctly:
> 
> Application `webpack.config.js`
> 
> ```js
> const singleSpaWebpackConfig = require('../../../tools/single-spa/webpack.config');
> 
> module.exports = (config, options) => {
>   const singleSpaConfig = singleSpaWebpackConfig(config, { ...options, projectDirName: __dirname });
>   return singleSpaConfig;
> };
> ```
> 
> Our Global single-spa `webpack.config`:
> 
> ```js
> const singleSpaAngularWebpack = require('single-spa-angular/lib/webpack').default;
> 
> function removePluginByName(plugins, name) {
>   const pluginIndex = plugins.findIndex((plugin) => plugin.constructor.name === name);
>   if (pluginIndex > -1) {
>     plugins.splice(pluginIndex, 1);
>   }
> }
> 
> module.exports = (config, options) => {
>   config.entry = { main: config.entry['main'], styles: [require('path').join(options.projectDirName, '/src/styles.scss?ngGlobalStyle')] };
>   removePluginByName(config.plugins, 'StylesWebpackPlugin');
> 
>   const singleSpaWebpackConfig = singleSpaAngularWebpack(config, {
>     ...options,
>     customWebpackConfig: { libraryTarget: 'system' },
>   });
> 
>   return singleSpaWebpackConfig;
> };
> ```
> 
> As you can see, we just remove the Angular Cli plugin but I am not really happy with that solution because we could miss some improvement from Angular Team. I would prefer that we create a plugin for Single Spa to be able to change the configuration later, after the plugin of Angular Cli

Thanks a lot. It has worked 👍

**Comment by arturovt** [comment]
I've published `single-spa-angular@9.0.1-alpha` with a fix. Can anyone test this version and see if the issue is resolved or not?

**Comment by JanK-Qics** [comment]
> I've published `single-spa-angular@9.0.1-alpha` with a fix. Can anyone test this version and see if the issue is resolved or not?

Tried it out, styles are bundled in the main.js and work fine.

**Comment by Alessandroinfo** [comment]
> I've published `single-spa-angular@9.0.1-alpha` with a fix. Can anyone test this version and see if the issue is resolved or not?

But this version is not compatible with Angular 15.

**Comment by arturovt** [comment]
No, it's not. But you can forcely install it, because there're no changes compared to version 8, I'm just aligning version with every Angular major release. I will backport it to version 8 if it resolves the issue.

**Comment by Alessandroinfo** [comment]
> No, it's not. But you can forcely install it, because there're no changes compared to version 8, I'm just aligning version with every Angular major release. I will backport it to version 8 if it resolves the issue.

Sure it's possible but it's a problem if you have configured CI/CD.

**Comment by arturovt** [comment]
You can use the `patch-package` to avoid interrupting the CI/CD, update the `lib/lib/webpack/index.js` with the following:
```js
if (Array.isArray(mergedConfig.entry.styles)) {
    // We want the global styles to be part of the "main" entry. The order of strings in this array
    // matters -- only the last item in the array will have its exports become the exports for the entire
    // webpack bundle
    mergedConfig.entry.main = [...mergedConfig.entry.styles, ...mergedConfig.entry.main];
}
else {
    // The `entry` doesn't have a `styles` property, which means we're on the Angular
    // 15+ version where `StylesWebpackPlugin` was introduced to resolve module resolution
    // issues related to Yarn PNP.
    const stylesWebpackPluginName = 'StylesWebpackPlugin';
    const stylesWebpackPlugin = mergedConfig.plugins.find((plugin) => plugin.constructor.name === stylesWebpackPluginName);
    const entryPoints = (_e = stylesWebpackPlugin === null || stylesWebpackPlugin === void 0 ? void 0 : stylesWebpackPlugin.options) === null || _e === void 0 ? void 0 : _e.entryPoints;
    if (entryPoints) {
        // The `ngGlobalStyle` is a Webpack query required by Angular to
        // apply a specific list of Webpack loaders to these files. There
        // are only two queries available: `ngGlobalStyle` and `ngResource`
        // (used for component styles).
        // Webpack would then do the following:
        // `{ use: globalStyleLoaders, resourceQuery: /\?ngGlobalStyle/ }`
        const query = `?ngGlobalStyle`;
        Object.keys(entryPoints).forEach(entryPoint => {
            // `styles` is the primary styles that must be loaded with the main entry point.
            if (entryPoint === 'styles') {
                const styles = entryPoints.styles.map(path => `${path}${query}`);
                mergedConfig.entry.main = [...styles, ...mergedConfig.entry.main];
            }
            else {
                // Other entry points (which are lazy bundles) must be a part of entries to resolve
                // to separate JS files.
                mergedConfig.entry[entryPoint] = entryPoints[entryPoint].map(path => `${path}${query}`);
            }
        });
        removePluginByName(mergedConfig.plugins, stylesWebpackPluginName);
    }
}
```

**Comment by Fulvia1989** [comment]
> I've published `single-spa-angular@9.0.1-alpha` with a fix. Can anyone test this version and see if the issue is resolved or not?

Worked for me on Angular 16.

It seems to work for Angular 15 too, by forcely installing it (but I only tried running the projecy locally)

**Comment by arturovt** [comment]
@Alessandroinfo `single-spa-angular@8.1.1`.

**Comment by arturovt** [comment]
`single-spa-angular@9.0.1` has been released.

**Comment by Fulvia1989** [comment]
I am noticing several warning in the terminal after build, similar to the ones I usally see for CommonJs dependencies. 

![warnings](https://github.com/single-spa/single-spa-angular/assets/55705411/926cf4e6-3b47-41c6-be8e-e69929bd82d8)

Unfortunately, adding those to the  `"allowedCommonJsDependencies"`  array in the `angular.json` file doesn´t seem to have any effect (warnings do not disappear).

Any suggestion?

**Comment by Fulvia1989** [comment]
> @Fulvia1989 you can actually remove the warnings by adding them into angular.json `"allowedCommonJsDependencies"` array i.e. `"allowedCommonJsDependencies": [ "quill", "quill-paste-smart", "konva", "crypto-js", "!../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js", "!../node_modules/style-loader/dist/runtime/insertBySelector.js", "!../node_modules/style-loader/dist/runtime/insertStyleElement.js", "!../node_modules/style-loader/dist/runtime/setAttributesWithoutAttributes.js", "!../node_modules/style-loader/dist/runtime/styleDomAPI.js", "!../node_modules/style-loader/dist/runtime/styleTagTransform.js" ],`
> 
> You have to add the same path as it is mentioned in the warning in `"allowedCommonJsDependencies"` array.
> 
> Hope this helps :)

YES! Thank you very much. I did not thought that the correct way to import those files was to add the entire path, and not only the filename...seems quite obvious right now...
Anyhow, it did work, of course.

Thanks!
