### ISSUE TITLE
Support Angular 15's standalone API?

### ISSUE THREAD

**Issue by LMFinney** [single-spa/single-spa-angular#469]
### Question

I would like to switch my application to use bootstrapApplication instead of platformBrowserDynamic().bootstrapModule(). Is this possible with single-spa-angular? Are there any examples of what main.ts should look like with that API?

### Environment

<pre><code>
Libs:
- @angular/core version: X.Y.Z
- single-spa-angular version: X.Y.Z

Others:

</code></pre>

**Comment by arturovt** [comment]
The `bootstrapFunction` supports returning `ApplicationRef` (which `bootstrapApplication` returns). So you need to do it in the same way as you do `bootstrapModule()`. Here's an example: https://github.com/single-spa/single-spa-angular/blob/master/apps/standalone/src/main.single-spa.ts#L16-L31

**Comment by LMFinney** [comment]
Thanks!
