### ISSUE TITLE
Global styles no more loaded by single-spa-angular's webpack config on Angular 15

### ISSUE THREAD

**Issue by traycold** [single-spa/single-spa-angular#471]
### Demonstration

- Create a new Angular 15 webapp (options used: routing/scss):
`npx -p @angular/cli ng new testapp`
- Add single-spa-angular (current latest version v8.0.1):
`npx ng add single-spa-angular --project testapp`
- Add any style in `src/styles.scss`, for instance:
```
.test-style-global{
  color:red !important;
}
```
- Modify default template `src/app.component.html` to use this style, for instance:
```
<p class="test-style-global">hello</p>
```
- Fix the routing for single-spa according to [official documentation](https://single-spa.js.org/docs/ecosystem-angular#configure-routes)
- Remove references to `environment` in `src/main.single-spa.ts` (apparently the environment files are not generated anymore with Angular 15)
- serve the single-spa app with command:
`npm run serve:single-spa:testapp`
- test on [Playground](http://single-spa-playground.org/)

### Expected Behavior
The global style is applied i.e. you can see the string _hello_ in red.

### Actual Behavior
The global style is NOT applied i.e. you can see the string _hello_ in black (default color).

### Older versions (Angular 14)
If you repeat the same steps, but using Angular 14:
`npx -p @angular/cli@14.2.10 ng new mypay`
`npx ng add single-spa-angular@7.1.0 --project mypay` (if using v8.0.1 an unmet-dependencies warning is issued)
the actual behaviour is the correct one (i.e. the global style is applied).

**Comment by dbpieter** [comment]
This is already being tracked in #463

**Comment by Harsh8Mel** [comment]
Facing the same issues as my global styles are not fetched.

**Comment by TomislavMedved** [comment]
+1, same issue

**Comment by gonznicolas** [comment]
+1, same issue

**Comment by AlbaSS18** [comment]
Hello, in my company we are having the same problems. We have trying the answers suggested by @jogelin and @dbpieter in this issue #463 but nothing worked. Any updates on this?

**Comment by OrShalmayev** [comment]
+1, same issue

**Comment by txc111** [comment]
+2, same issue. just found the issue may caused by the new styles.js file

previous only have main.js
<script src="http://localhost:4201/main.js" type="module"></script>

currently
<script src="http://localhost:4201/styles.js" defer></script><script src="http://localhost:4201/main.js" type="module"></script>

try to config extra-webpack.config.js , failed..

**Comment by AdibW** [comment]
same Issue in my project, 
my project A is the container of single-spa 
project B that imported into the project A.
All classes and @import() integrated in styles.scss of project B is not scooped and i can't see any modification in the server.
for exmaple, to integrae ng-select in project B, ishoulf integrate classes that i should import into the project A ( the container ).

**Comment by pgarzina** [comment]
hey, any news on this, we are experiencing the same issue, thx!

**Comment by JanK-Qics** [comment]
check out my "workaround", it may help

https://github.com/single-spa/single-spa-angular/issues/463#issuecomment-1582486882

**Comment by Fulvia1989** [comment]
Same Issue.
This is causing serious problems even with Angular Material, or any other third-party libraries.
Any workaround suggested  in #463 did not work for me.  
I hope there will be updates on this soon...

**Comment by Alessandroinfo** [comment]
It's possibile to have all the assets in main and main.single-spa?

**Comment by AntonGrekov** [comment]
Agree on this. Same here. Styles are now bundled in separate styles.js file. If anyone know how to bundle styles as before(in main.js) please tell the instuctrions
