### ISSUE TITLE
Multiple Store is being created while navigating back to the Angular MFE

### ISSUE THREAD

**Issue by devprasenjitsaha** [single-spa/single-spa-angular#476]
### Demonstration
I am using NgRx to implement the sate management in my Angular (using version 15, same tried with lower version also) MFE. It is working fine if I am within the MFE but if I navigate to other MFE and if I come back again to the Angular MFE then I cannot access the previous stored data, instead of that in Redux Devtool I can see fresh store is being created every time if re-render the Angular MFE.

![image](https://user-images.githubusercontent.com/49550690/221809068-49613f79-fb87-49f2-b1c1-004b7b388967.png)

### Expected Behavior
There should be only one store for that MFE.

### Actual Behavior
It is creating multiple stores.

**Comment by arturovt** [comment]
Create a minimal reproducible example. Feel free to reopen once it’s provided.
