### ISSUE TITLE
how to use global css and icons from library, bundled in main.js used in angular components.

### ISSUE THREAD

**Issue by LindaSebastian** [single-spa/single-spa-angular#486]
### Environment
Primeng and primenicons are used. primeicons are not loading. Its inserted in styles in angular.json. Bundled in to main.js
how to extract css from main.js bundled.
Libs:
- @angular/core version: 14.3.0
- single-spa-angular version: 7.1.0

**Comment by arturovt** [comment]
Provide a minimal reproducible example.
