### ISSUE TITLE
deploy-url is  deprecated

### ISSUE THREAD

**Issue by MzoroHaHa** [single-spa/single-spa-angular#487]
### Question
deploy-url is  deprecated in v15 , is there any other config item to tell angular where to load lazy module?
### Environment

<pre><code>
Libs:
- @angular/core version: X.Y.Z
- single-spa-angular version: X.Y.Z

Others:

</code></pre>

**Comment by arturovt** [comment]
No, there isn't. When the `deployUrl` is provided in the Angular configuration, it does the following:

1) updates urls in `index.html` as thus `<script src="vendor.js"` becomes `<script src="http://localhost:4300/vendor.js`
2) sets `__webpack_require__.p = "http://localhost:4300/";`

`__webpack_require__.p` is a `__webpack_public_path__` (https://webpack.js.org/guides/public-path).
