### ISSUE TITLE
Angular 17

### ISSUE THREAD

**Issue by kuamatzin** [single-spa/single-spa-angular#501]
My Angular 17 is running with npm run serve:single-spa:application-name

But when I try to run the root app is giving me this error:

![CleanShot 2023-12-13 at 17 12 24@2x](https://github.com/single-spa/single-spa-angular/assets/5751439/c15685b2-cd1c-4b8b-adae-86375a6cceaf)

I already applied this config (https://github.com/single-spa/single-spa-angular/issues/484) in the main.single-spa.js file

**Comment by arturovt** [comment]
Provide a minimal reproducible example please, feel free to reopen once you have it.
