### ISSUE TITLE
ERROR Error: NG0909: Expected to be in Angular Zone, but it is not!

### ISSUE THREAD

**Issue by D-Studio-21th** [single-spa/single-spa-angular#510]
### Demonstration
This issue happens when upgrading the system to Angular is older than 17.04 

### Actual Behavior
[localhost-1713262609482.zip](https://github.com/single-spa/single-spa-angular/files/14995370/localhost-1713262609482.zip)

**Comment by szymonworld** [comment]
#511 It's might be similar problem.
For my application => 17.0.8 breaks Angular Zone.
