### ISSUE TITLE
Error: NG0909: Expected to be in Angular Zone, but it is not!

### ISSUE THREAD

**Issue by szymonworld** [single-spa/single-spa-angular#511]
### Demonstration

I'm upgrading my application by each version from Angular 13 to Angular 17 and everything was going well until upgrade from v16 to v17.
The "Error: NG0909: Expected to be in Angular Zone, but it is not!" appears per each micro-frontend app.

That's how I bootstrap apps:
const lifecycles = singleSpaAngular({
    bootstrapFunction: singleSpaProps => {
        singleSpaPropsSubject.next(singleSpaProps);
        return platformBrowserDynamic(
            getSingleSpaExtraProviders()
        ).bootstrapModule(AppModule);
    },
    template: '<x1-root class="site-root"></x1-root>',
    Router,
    NgZone
}); 

Updated package.json:
  "dependencies": {
    "@angular/animations": "17.3.4",
    "@angular/cdk": "17.3.4",
    "@angular/common": "17.3.4",
    "@angular/compiler": "17.3.4",
    "@angular/core": "17.3.4",
    "@angular/forms": "17.3.4",
    "@angular/localize": "17.3.4",
    "@angular/material": "17.3.4",
    "@angular/platform-browser": "17.3.4",
    "@angular/platform-browser-dynamic": "17.3.4",
    "@angular/router": "17.3.4",
    "@ng-bootstrap/ng-bootstrap": "^16.0.0",
    "rxjs": "7.5.5",
    "single-spa": "6.0.1",
    "single-spa-angular": "9.1.0",
    "zone.js": "0.14.4"

  "devDependencies": {
    "@angular-builders/custom-webpack": "17.0.2",
    "@angular-devkit/build-angular": "17.3.4",
    "@angular/cli": "17.3.4",
    "@angular/compiler-cli": "17.3.4",
    "typescript": "5.4.5"

I was trying with zone.js: 0.13.3, rxjs: 6.x, single-spa: 5.9.x and single-spa-angular: 8.1.x - there is the same error with Angular 17.

// EDIT
I found that there is a problem with @angular/compiler >= 17.0.8
And that commit might be a problem with additional Intercept any overridden globals: https://github.com/angular/angular/commit/de5c9ca8e9a026ad752aab348bd137f647cc3cc9#diff-0d3035937352a0ed7d0bf6597e98807e6ae6dc132ccf95fd9503dffdad4319cb
And Single-Spa-Angular use that for:
"This is a hack, since NgZone doesn't allow you to configure the property that identifies your zone."

### Expected Behavior

Fix for that error.

### Actual Behavior

ERROR Error: NG0909: Expected to be in Angular Zone, but it is not!
    at NgZone.assertInAngularZone (core.mjs:14709:19)
    at Object.next (core.mjs:31990:20)
    at ConsumerObserver.next (Subscriber.js:91:33)
    at SafeSubscriber._next (Subscriber.js:60:26)
    at SafeSubscriber.next (Subscriber.js:31:18)
    at Subject.js:34:30
    at errorContext (errorContext.js:19:9)
    at EventEmitter_.next (Subject.js:27:21)
    at EventEmitter_.emit (core.mjs:6845:19)
    at onEnter (core.mjs:14927:25)

**Comment by arturovt** [comment]
`assertInAngularZone` is a static property on the class and we can change the code to do nothing like `assertInAngularZone = () => {}`, because there's no option to know under what app this function is executed, especially when deps are shared.

**Comment by arturovt** [comment]
Ok, I’ll change it to the noop function, there’s no reason to do any other changes with it.

**Comment by arturovt** [comment]
`single-spa-angular@9.1.1`.

**Comment by Hootlook** [comment]
I pulled the last version but now i have the issue for this function too 
![image](https://github.com/single-spa/single-spa-angular/assets/42444823/9091dd37-753f-488b-8e40-772192512d93)

i saw the changes in the PR: https://github.com/single-spa/single-spa-angular/pull/512/commits/57515a689776cc170bf2930f0c52eb0d61b5030f

Should "options.NgZone.assertNotInAngularZone = () => {};" be added aswell ?

**Comment by arturovt** [comment]
`9.1.2`
