### ISSUE TITLE
Error: Framework 'svelte' is not yet supported for utility microfrontends. Try creating a vanilla utility module (no framework) in the meantime, which are usable by all frameworks.

### ISSUE THREAD

**Issue by Ecarch** [single-spa/single-spa-angular#514]
Hi everyone, I need some help! 
I'm trying to create a project following the steps according to the documentation:
- npx create-single-spa.
- write the name of the project.
- select single-spa application/ parcel
and I choose Angular framework 
And I'm getting the following error that mentions the Svelte framework, but it's weird because it always comes out the same if I select any other framework like React or Vue and not necessarily with Angular, as opposed to if I generate in a Vanilla way. Can anyone tell me if I'm making a mistake?
I have Angular V17.3.2 and Node V20.12.0
<img width="460" alt="Screenshot 2024-04-29 101024" src="https://github.com/single-spa/single-spa-angular/assets/137192114/8ece371c-290f-4cc5-a001-db46ec73450c">

**Comment by webJose** [comment]
Sounds like a bug in the create-single-spa package, not single-spa-angular.

**Comment by arturovt** [comment]
Closing since not related to that repository.
