### ISSUE TITLE
Single-spa CLI Angular v17 Application Installation Failure

### ISSUE THREAD

**Issue by dcgallo93** [single-spa/single-spa-angular#523]
After running the 'create-single-spa' command, and following the prompt, once I select the angular application and indicate the name of the project, the process stops the process stops without generating the angular application. Is this a known bug, and if so is there a fix?

**Comment by eironman** [comment]
Hi @dcgallo93, I was experiencing the same problem and I ended up solving it using the node version 18.19.1 (after trying several other versions)
I use windows and nvm for windows.
Hope it helps
