### ISSUE TITLE
Angular 18 - Status of the project

### ISSUE THREAD

**Issue by leogouveia** [single-spa/single-spa-angular#524]
### Question

Are there any plans to update the project to Angular version 18?
Is the project still active, or are you waiting for new maintainers?

**Comment by soumenpalsentientgeeks** [comment]
I want to use single spa to create micro frontend project (angular 18 and angular 14) is there any way to do this? because angular 18 is not opening in route url?

**Comment by arturovt** [comment]
The project is now using Angular 18. It was upgraded w/o any changes meaning that no changes required from the consumer side to use the latest single-spa-angular with Angular 18.
