### ISSUE TITLE
SkipNextPopState = true is preventing initial pushState to take place

### ISSUE THREAD

**Issue by greg-signi** [single-spa/single-spa-angular#526]
### Question
The first `history.pushState(..)` dispatched by other "mfe" is not being consumed by my angular spa, because of this snippet since
`skipNextPopState` is set to true. After that is false and I can already grab the same `history.pushState(..)` which is triggered by a Nav button. 

```
const onPopStateListener = (event) => {
            // The `LocationChangeEvent` doesn't have the `singleSpa` property, since it's added
            // by `single-spa` starting from `5.4` version. We need this check because we want
            // to skip "unnatural" PopStateEvents, the one caused by `single-spa`.
            const popStateEventWasDispatchedBySingleSpa = !!event
                .singleSpa;
            if (this.skipNextPopState && popStateEventWasDispatchedBySingleSpa) {
                // Enters here!
                this.skipNextPopState = false;
            }
            else {
                fn(event);
            }
        };
```

What can I do to stop prevent this behaviour ?

### Environment

<pre><code>
Libs:
- @angular/core version: 17.2.0
- single-spa-angular version: 9.0.1

**Comment by greg-signi** [comment]
Sorry for disturbing you @arturovt , but you seem to be the only help still around here 😨

**Comment by arturovt** [comment]
Is there a way to reproduce it in some playground?

**Comment by arturovt** [comment]
This was done to prevent infinite navigation loops because both single-spa and Angular listen to the popstate event. This simultaneous listening would trigger their internal navigation processes and history calls, potentially causing an infinite loop.

**Comment by greg-signi** [comment]
Okay, but how do you know you are not ignoring valid navigation events ? Should we just discard the first navigation event always ?

**Comment by arturovt** [comment]
No, this is only ignoring events dispatched by single-spa, and not the actual browser.

**Comment by greg-signi** [comment]
Okay this is what happens when I first try to click the button (That's in belongs to a different mfe), my mfe will get the event but gets stuck there

![image](https://github.com/user-attachments/assets/a181db0c-9c52-4716-9023-e341da6e7aab)

And I don't get what you mean that this was sent by a SPA, this **happened when I clicked and a `history.pushState()` event happened**.

This is the a snapshot of the `History` object

![image](https://github.com/user-attachments/assets/837dbfcd-a3e2-4c6a-b06c-84f70bbbd637)

This is the `PopStateEvent` received 

![image](https://github.com/user-attachments/assets/ba0fed0d-7cfd-46bf-8e20-0b4c084b2dff)

**Comment by greg-signi** [comment]
Well I managed to find a workaround with some insight found on this [thread ](https://github.com/single-spa/single-spa-angular/pull/235), but I still don't understand why is this was necessary in the first place...

So I added the `withDisabledInitialNavigation()` to stop the initial navigation that was triggering the [replaceState](https://github.com/single-spa/single-spa-angular/blob/e247aac039de811cbb6b7b71ea512ef31d1fd98e/libs/single-spa-angular/src/extra-providers.ts#L25)
```
providers: [
    provideRouter(APP_ROUTES, **withDisabledInitialNavigation()**),
    provideHttpClient(withInterceptors([antiforgeryTokenInterceptorFn]))
  ]
```

And in my initial navigation I refused to replace the history state, which avoided the `SkipNextPopState = true;` scenario I was having issues with:

```
this.router.navigate(['/'], { replaceUrl: false, skipLocationChange: true });
```

Now I wouldn't have issue with replaceState if not the case of `SkipNextPopState = true` and causing to always ignore the **second** navigation event it would follow after..

Any thoughts on the matter ? Why did I have to fallback to this ?

Thanks for your time!!
