### ISSUE TITLE
Coud you please update the docs? 

### ISSUE THREAD

**Issue by dipsx** [single-spa/single-spa-angular#527]
### Demonstration

The last version in the documentation is Angular 15.

![image](https://github.com/user-attachments/assets/f38f9ab4-5714-424a-8d1c-43f829ccce1e)

Angular 17 and 18, by default, create projects with standalone components (without a module), and the section "Configure routes" is outdated. Without this step, the application will not work at all.

![image](https://github.com/user-attachments/assets/5c7fb108-fd60-417f-8669-cbbddaa70262)

**Comment by joeldenning** [comment]
See https://github.com/single-spa/single-spa.js.org/pull/634
