### ISSUE TITLE
Nested routes don't work with BrowserAnimationsModule

### ISSUE THREAD

**Issue by joeldenning** [single-spa/single-spa-angular#60]
This issue was first reported as a comment to a separate issue. https://github.com/CanopyTax/single-spa/issues/289#issuecomment-483105297

It is from @jaspreet1234567

> Hi @joeldenning , I checked the above code looks that it resolve routing issue if we redirect one app to another app. But my issue is related to internal routing in one app.
>
> Suppose we have two routes in "app2", and we are using "BrowserAnimationsModule" in "app2", then internal routing is not working properly because here application is not unmounted only routing is happening is one application.
> 
> I think if we are able to resolve this issue then our second issue (datepicker position) should also be resolved.
>
> Here is the link of sample project ( https://github.com/jaspreet1234567/single-spa-internal-routing-issue ) I am using for internal routing test. I just did some modifications in your "coexisting-angular-microfrontends" application.
>
>To reproduce the issue, just go to app 2 and trying back/forward within sub routes using browser buttons.
>
> It is working fine in angular application if we don't use single-spa library.

**Comment by jaspreet1234567** [comment]
Hi,

Any update on this?

**Comment by joeldenning** [comment]
Hi @jaspreet1234567, I am working on https://github.com/CanopyTax/single-spa-angular/issues/44 and https://github.com/CanopyTax/single-spa-angular/issues/41 first before shifting attention to this bug.

**Comment by joeldenning** [comment]
oops accidentally closed. Reopening now

**Comment by HemendPatel63** [comment]
I  am getting the similar issue when same name module existing in two different apps with lazylaod (with BrowserAnimationsModule)

![image](https://user-images.githubusercontent.com/49240619/66285051-83761780-e890-11e9-9b66-e4782707d5fd.png)

Try to navigate from app1 to app2 having the same module with lazyloading.

**Comment by SunilManthenaG01** [comment]
When I have two different apps both where lazy loaded and using BrowserAnimationsModule and while navigating between each other have same module names errors the above errors for me as well.

**Comment by danyjaen** [comment]
Same error here.

When I navigate to a nested route and came back to a previous page, the change detection doesn't work, I have to manually put a detectChanges().

I'm using also Angular material and BrowserAnimationsModule and when I came back from another route I'm not able to use, for example, the datepicker. Things appear after a click event, but never automatically.

**Comment by arturovt** [comment]
@jaspreet1234567 I cloned your repo and the issue really presents there. But the issue disappeared when I upgraded `single-spa-angular` to `3.0.0`.

@HemTech @SunilManthenaG01 @danyjaen gentlemen, your issues are impossible to test and resolve unless you provide _minimal reproducible examples_.

**Comment by joeldenning** [comment]
Thanks @arturovt - I'm closing this issue as fixed in single-spa-angular@3. If that turns out not to be true, please provide a minimal reproducible example.
