### ISSUE TITLE
Implement generic component for rendering single-spa parcels.

### ISSUE THREAD

**Issue by joeldenning** [single-spa/single-spa-angular#98]
See https://single-spa.js.org/docs/ecosystem-react.html#parcels for how single-spa-react does this.

**Comment by joeldenning** [comment]
Community contributions welcome for this

**Comment by ricardofct** [comment]
> Community contributions welcome for this

Do you have any advice/ idea regarding the construction of generic component ?

**Comment by joeldenning** [comment]
I think the consumer of the component would want an API somewhat like this?

```html
<div>
  <parcel [config]="config" [prop1]="prop1"></parcel>
</div>
```

And would import that parcel component from single-spa-angular and register it in one of their modules.

The implementation of the parcel component would roughly be the following:

1. In ngOnInit, call single-spa's mountParcel() function
2. Whenever prop1 changes, call `parcel.update()`
3. In ngOnDestroy, call single-spa's parcel.unmount() function

**Comment by ricardofct** [comment]
I did first baby steps here: https://github.com/ricardofct/single-spa-angular/tree/angular-parcel

**Comment by ricardofct** [comment]
But I need to learn a lot to implement this, I think!

**Comment by joeldenning** [comment]
Could you please open this up as a PR?

**Comment by joeldenning** [comment]
Implemented in #122. This is now pending release

**Comment by joeldenning** [comment]
This has been released for some time. Still need to update the documentation for it in https://github.com/single-spa/single-spa.js.org/issues/199

**Comment by joeldenning** [comment]
An example of the parcel component is shown here: https://github.com/single-spa/single-spa-angular/releases/tag/v4.7.0

**Comment by joeldenning** [comment]
Documentation for parcels at https://single-spa.js.org/docs/ecosystem-angular#parcels
